### ISSUE TITLE
Client Allocation Request for: 河南中创算力

### ISSUE THREAD

**Issue by 1ane-1** [filecoin-project/filecoin-plus-client-onboarding#1024]
---

# Client Allocation Questions 

## Core Information
- Name: 河南中创算力
- Website / Social Media: Slack:ZhongchuangIPFS
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3th7dyfaaoiffrx3tkqoqfjsxqpv7drjtu4hxtzyf3cddnfnfiwhsuwtr2f4x335naxcmnrdjm5mkrdofhsda
- Notary Requested: MRJAVAZHAO

@1ane-1 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MRJAVAZHAO** [comment]
Hello, @1ane-1 
Please provide the following materials.

Organization name, business scale, social media accounts&follwers, and business license (could be sent by email); if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&follwers, and ID card (can be sent by email);

When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network?

Is there any law risk? What percentage of questions are yours?

Please describe your organization, such as established time, the number of employees, users volumn, the number of social media followers.

How about your data volume, source and later planning? Please describe the type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin.

In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.

Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.

**Comment by 1ane-1** [comment]
1.Zhongchuang was established in 2021, but our core developers have been devoted into this field for years. By employing various sets of systems like self-developed integrated micro cabinet for data storage, integrated refrigeration, monitors, fire protection, edge calculation, it now has realized one-stop data manipulation and operation management with monitoring system conducting integrated management on subsystem. The link of the team on Github:https://github.com/orgs/ipfs-zcsl/dashboard
2.We know filecoin from 2019, it is a decentralized storage network designed to store humanity’s most important information. Zhongchuang Power join the MinerX.2 Fellowship, the goals of this program are to build a solid foundation of globally distributed,reliable,long-term storage options to accelerate the development of tools and services in the ecosystem,while identifying areas to improve the experience of being a(lotus)miner in the Filecoin network. About nearXfilecoin, we already send the fip to join the competition.
3.No any law risk.
4.Zhongchuang was established in 2021, and there are 60 staffs. About 5000+ fans on our WeChat public account.
5.As for data, most of them come from our own surveillance videos. It is belongs to us with MP4 format and Storage capacity about can reach 10PIB . All of them may be not open for anyone.
6.It will be uesd in China, we only need one miner with ID F01164500. No other request at present.

**Comment by 1ane-1** [comment]
This is our business license.Anout other answers to your question have been sent on the Github.Pls check, thanks.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecoin-project/filecoin-plus-client-onboarding"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月1日(星期一) 上午9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filecoin-project/filecoin-plus-client-onboarding] Client Allocation Request for: 河南中创算力 (Issue #1024)





 
Hello, @1ane-1
 Please provide the following materials.
 
Organization name, business scale, social media accounts&amp;follwers, and business license (could be sent by email); if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&amp;follwers, and ID card (can be sent by email);
 
When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network?
 
Is there any law risk? What percentage of questions are yours?
 
Please describe your organization, such as established time, the number of employees, users volumn, the number of social media followers.
 
How about your data volume, source and later planning? Please describe the type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin.
 
In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.
 
Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MRJAVAZHAO** [comment]
Dear 河南中创算力,
I have not received your business license.
Please submit again.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecoin-project/filecoin-plus-client-onboarding"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月1日(星期一) 中午11:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filecoin-project/filecoin-plus-client-onboarding] Client Allocation Request for: 河南中创算力 (Issue #1024)





 This is our business license.Anout other answers to your question have been sent on the Github.Pls check, thanks. 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "filecoin-project/filecoin-plus-client-onboarding"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月1日(星期一) 上午9:30 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [filecoin-project/filecoin-plus-client-onboarding] Client Allocation Request for: 河南中创算力 (Issue #1024) 
 
 
 
 
 
   
 Hello, @1ane-1 
  Please provide the following materials. 
   
 Organization name, business scale, social media accounts&amp;amp;follwers, and business license (could be sent by email); if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&amp;amp;follwers, and ID card (can be sent by email); 
   
 When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network? 
   
 Is there any law risk? What percentage of questions are yours? 
   
 Please describe your organization, such as established time, the number of employees, users volumn, the number of social media followers. 
   
 How about your data volume, source and later planning? Please describe the type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin. 
   
 In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan. 
   
 Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time. 
   
 — 
 You are receiving this because you were mentioned. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1ane-1** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecoin-project/filecoin-plus-client-onboarding"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 中午1:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filecoin-project/filecoin-plus-client-onboarding] Client Allocation Request for: 河南中创算力 (Issue #1024)





 Dear 河南中创算力, 
 I have not received your business license. 
 Please submit again. 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "filecoin-project/filecoin-plus-client-onboarding"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月1日(星期一) 中午11:42 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [filecoin-project/filecoin-plus-client-onboarding] Client Allocation Request for: 河南中创算力 (Issue #1024) 
 
 
 
 
 
  This is our business license.Anout other answers to your question have been sent on the Github.Pls check, thanks.  
   
   
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "filecoin-project/filecoin-plus-client-onboarding"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年11月1日(星期一) 上午9:30  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [filecoin-project/filecoin-plus-client-onboarding] Client Allocation Request for: 河南中创算力 (Issue #1024)  
   
   
   
   
   
     
  Hello, @1ane-1  
   Please provide the following materials.  
     
  Organization name, business scale, social media accounts&amp;amp;amp;follwers, and business license (could be sent by email); if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&amp;amp;amp;follwers, and ID card (can be sent by email);  
     
  When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network?  
     
  Is there any law risk? What percentage of questions are yours?  
     
  Please describe your organization, such as established time, the number of employees, users volumn, the number of social media followers.  
     
  How about your data volume, source and later planning? Please describe the type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin.  
     
  In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.  
     
  Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.  
     
  —  
  You are receiving this because you were mentioned.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you were assigned. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1ane-1** [comment]
![营业执照](https://user-images.githubusercontent.com/91301211/139795207-471da380-3f33-4349-bf57-67b0099b2112.jpg)

**Comment by MRJAVAZHAO** [comment]
In addition, you only chose a storage provider, whether there is a relationship with it?&nbsp;&nbsp;Do you agree to choose multiple storage providers?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecoin-project/filecoin-plus-client-onboarding"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 下午2:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filecoin-project/filecoin-plus-client-onboarding] Client Allocation Request for: 河南中创算力 (Issue #1024)





 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "filecoin-project/filecoin-plus-client-onboarding"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月2日(星期二) 中午1:49 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [filecoin-project/filecoin-plus-client-onboarding] Client Allocation Request for: 河南中创算力 (Issue #1024) 
 
 
 
 
 
  Dear 河南中创算力,  
  I have not received your business license.  
  Please submit again.  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "filecoin-project/filecoin-plus-client-onboarding"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年11月1日(星期一) 中午11:42  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [filecoin-project/filecoin-plus-client-onboarding] Client Allocation Request for: 河南中创算力 (Issue #1024)  
   
   
   
   
   
   This is our business license.Anout other answers to your question have been sent on the Github.Pls check, thanks.   
     
     
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "filecoin-project/filecoin-plus-client-onboarding"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年11月1日(星期一) 上午9:30   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [filecoin-project/filecoin-plus-client-onboarding] Client Allocation Request for: 河南中创算力 (Issue #1024)   
     
     
     
     
     
       
   Hello, @1ane-1   
    Please provide the following materials.   
       
   Organization name, business scale, social media accounts&amp;amp;amp;amp;follwers, and business license (could be sent by email); if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&amp;amp;amp;amp;follwers, and ID card (can be sent by email);   
       
   When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network?   
       
   Is there any law risk? What percentage of questions are yours?   
       
   Please describe your organization, such as established time, the number of employees, users volumn, the number of social media followers.   
       
   How about your data volume, source and later planning? Please describe the type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin.   
       
   In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.   
       
   Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.   
       
   —   
   You are receiving this because you were mentioned.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
   Triage notifications on the go with GitHub Mobile for iOS or Android.   
  —  
  You are receiving this because you were assigned.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you were mentioned. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1ane-1** [comment]
yes，it is our own miner. So we just choose one.

**Comment by MRJAVAZHAO** [comment]
According to rule of https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview
No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.
So I can't grant DataCap for you.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
