### ISSUE TITLE
Client Allocation Request for: 深圳现代旗舰

### ISSUE THREAD

**Issue by earringsama** [filecoin-project/filecoin-plus-client-onboarding#103]
---

# Client Allocation Questions 

## Core Information
- Name: 深圳现代旗舰
- Website / Social Media: 18688828165
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3scnb4q4bx2wxwnfd4oljmm5itwgyzr2jmiqapyl4te7xmhx55svkmmukye4wbhvgajuxx5ckenke2bmbilhq
- Notary Requested: NeoGe-IPFSMain

**Comment by NeoGe-IPFSMain** [comment]
Hey @earringsama, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3. In which region(s) do you intend to use the DataCap? 
4. What is your use case for the DataCap being requested? 
5. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6. How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

Before starting to answer questions, I encourage you to take a look of our allocation strategy [here ](https://github.com/filecoin-project/notary-governance/issues/11)which shows how we utilize the assessment.

Thanks.

**Comment by neogeweb3** [comment]
Hey @earringsama, let me know if you require any assistance regarding my questions.

**Comment by neogeweb3** [comment]
Hey @earringsama, I will close this request as I haven't heard from you for more than 7 weeks. You could reopen this issue with answers. Thank you.
