### ISSUE TITLE
Client Allocation Request for: stariverpool

### ISSUE THREAD

**Issue by changlizhi** [filecoin-project/filecoin-plus-client-onboarding#1077]
---

# Client Allocation Questions 

## Core Information
- Name: stariverpool
- Website / Social Media: www.stariverpool.io
- Region: Greater China
- DataCap Requested: 20TiB
- Addresses to be Notarized: f01128320
- Notary Requested: neogeweb3

@changlizhi Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by neogeweb3** [comment]
Hey @changlizhi, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1.	Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2.	If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3.	In which region(s) do you intend to use the DataCap? 
4.	What is your use case for the DataCap being requested? 
5.	Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6.	How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7.	Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?

Moreover, I encourage you to take a look of my allocation [strategy ](https://github.com/filecoin-project/notary-governance/issues/11) and [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)which shows how I utilize the assessment. Thanks.

**Comment by changlizhi** [comment]
Dear notary:

1. My email is changlizhi@aliyun.com,my wechat is changlizhime,my github account is changlizhi
2. I'm a developer of Stariver Technology Co., Ltd. witch is based in Chengdu, Sichuan Province, China, and has 40 employees.you can find these informations in our official website https://www.stariverpool.io/contact.html
3. We apply datacap for our app "小龙云盘" ,witch can be used in all regions of global.
4. The app named “小龙云盘” is the product of the datacap will be used,you can install it from appstore(android in vivo store)or you can find it in our clouddisk websit https://www.stariverpan.com/ for pc client(mobile client too),this app is based on ipfs network,all of the datas on the app is uploaded to ipfs,you can verify any right cid by using our own gateway https://ipfsgw.stariverpan.com/ipfs/cid... (if you dont have any cid ,the app will give you one if you upload an asset,you can alse seach it on external ipfs gateway if you get one),and there is almost 2Tb data in it(we just put this app online for about 1 month)
5. I think that Allocating the assets of the app to filecoin is the advanced feature,so we are applying the datacap
6. 6-12 miners.but there are no specially designated miners now,we will find the miners on https://plus.fil.org/miners first
7. I agree. I will check it carefully
8. this is our Addresses to be Notarized（if f01128320 cant be Notarized）: f1fd7pgiygdwnsvxqj7n3f4ixuioq5btgok25mgzi

**Comment by neogeweb3** [comment]
Hey @changlizhi, thanks for the information. 

> 5. I think that Allocating the assets of the app to filecoin is the advanced feature,so we are applying the datacap

An advanced feature is the feature storage providers would offer, like fast retrieval to the clients with or without additional costs. It would be something you could discuss with storage providers. 

My allocation strategy is to build trust progressively. So I could allocate 100 GiB to you for the first time. Feel free to request more DataCap when you use up the allocation.

**Comment by neogeweb3** [comment]
@changlizhi do you mind describing the problem again? The allocation looks fine on my end: https://filfox.info/en/message/bafy2bzacebufzlvo7riwz5vt2y7brlq52q4dyt5jufwftgmfmrgy5xgvnvdya

If you use the glif (https://verify.glif.io/) to check the DataCap, it will say "f01128320 has 100 GiB of DataCap left." I am not familiar with the error you mentioned in #1097, maybe @dkkapur could help on that? Thanks!

**Comment by changlizhi** [comment]
@neogeweb3 @dkkapur . I made a deal by --from option like below,but got an error info,maybe the address must be a wallet address but mine is natoried to a miner address:
![errorInfo](https://user-images.githubusercontent.com/4144452/141393639-24459b55-b4b7-4bca-bf34-bc04a963682f.png)

For testing this, I applied another 32g with a wallet by github account auto from verify.glif.io  ,got the rigth info like below:
![rightInfo](https://user-images.githubusercontent.com/4144452/141393656-0ca018c0-9250-4231-8d66-567a4403bb86.png)

**Comment by changlizhi** [comment]
@neogeweb3 sorry to disterb ,but I really want the datacap asap,would you please verified another datacap in #1097 if this error need too much time to resolve.

**Comment by neogeweb3** [comment]
@changlizhi I understand your concern, however, I have to wait to see what is the outcome. 

The target address you provided in the current request is f01128320, I sent the Datacap to f01128320 as requested. The onchain data shows f01128320 still has 100GiB of DataCap left. So I won't be able to process the next Datacap request until the previous Datacap was successfully consumed or became unavailable to you. 

I will ask around to speed up the process. In the meantime, if you really need the DataCap asap, I encourage you to apply additional DataCaps from other Notaries.

**Comment by neogeweb3** [comment]
I will close this issue as noted in #1097
