### ISSUE TITLE
Client Allocation Request for: Paralym Art

### ISSUE THREAD

**Issue by kenparalymart** [filecoin-project/filecoin-plus-client-onboarding#113]
---

# Client Allocation Questions 

## Core Information
- Name: Paralym Art
- Website / Social Media: paralymart.or.jp
- Region: Asia excl. Greater China
- DataCap Requested: 120GiB
- Addresses to be Notarized: f3s4k4qjanlxpjh3ken7eqdnizlq3gors6tyoo33gxle7knnikp4oissy46mr3ujz3xs5s5dv2a55gb57ezzga
- Notary Requested: MasaakiNawatani

**Comment by MasaakiNawatani** [comment]
**Reputation
Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

"Please answer here"

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 

"Please answer here"

**Allocation Strategy
Do you intend to store your data in a single geography or many?

"Please answer here"

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

"Please answer here"

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

"Please answer here"

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

"Please answer here"

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

"Please answer here"

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

"Please answer here"

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

"Please answer here"

Are there any disputes open against you from your previous DataCap allocations?

"Please answer here"

Have you ever previously violated:

Your own attested allocation / audit plan?
Been found to be in violation of the Principles of Filecoin Plus?

"Please answer here"

**Comment by kenparalymart** [comment]
> Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.
> 
> ```
> Paralym Art is an organization that supports the financial independence of disabled artists by connecting them with companies and other organizations. We showcase original artworks by disabled artists to companies and other organizations and process the payment in a secured and efficient way. 
> ```
> 
> Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)?
> 
> ```
> No. This will be our first time to request.  
> ```
> 
> **Allocation Strategy
> Do you intend to store your data in a single geography or many?
> 
> ```
> Single. We prefer to work with a storage provider that exists or based in Japan.
> ```
> 
> Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?
> 
> ```
> If the storage provider has Fast retrieval, it will be fine.
> ```
> 
> How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
> 
> ```
> After we decide which storage provider we use then actually store our data. Then we will show our web page which you can see our data can be retrieved from storage provider.
> ```
> 
> Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?
> 
> ```
> So far we will use all DataCap to a single provider but if our business goes smoothly and expands, we may consider storing our data with another provider as backup.
> ```
> 
> For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?
> 
> ```
> N/A
> ```
> 
> Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?
> 
> ```
> Yes. We intend to fully abide by the rules and guidelines set forth. 
> ```
> 
> **Track Record
> Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.
> 
> ```
> None. This will be our first time. 
> ```
> 
> Are there any disputes open against you from your previous DataCap allocations?
> 
> ```
> None.
> ```
> 
> Have you ever previously violated:
> 
> Your own attested allocation / audit plan?
> Been found to be in violation of the Principles of Filecoin Plus?
> 
> ```
> We have no history of any sort of violation. This is our first time to submit a request.
> ```

**Comment by MasaakiNawatani** [comment]
Thank you for answering. But I would like to know much more about your business model and your company. Do you have any document which states about your business model and your company ? If you have, please give me download URL. And also please explain why you need 120Gb Data cap. Do you have any evidence that you now store how much data on your sever ?

**Comment by kenparalymart** [comment]
[パラリンアート世界大会（英語版）.pdf](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/5931746/default.pdf)

Please see attached file of our business model for reference. We plan to use storage and retrieval to create a more secured and cost-efficient means of file management since our business requires us to store hundreds to thousands of original artworks by disabled artists for a certain period of time. You may also check our website https://paralymart.or.jp

Thank you for your consideration.

**Comment by kenparalymart** [comment]
Also, please see attached screenshot of our file storage usage (170 gb already consumed and will only increase as time goes by). We plan to migrate our data away from Dropbox and into Filecoin network asap. Thank you for your consideration. 

![Client-dropbox (4)](https://user-images.githubusercontent.com/78209005/108139892-fd144b80-70fb-11eb-96d4-e65b7953b5d8.png)

**Comment by MasaakiNawatani** [comment]
Thank you providing me document. It seems to be no problem so I will push Data Cap soon.

**Comment by MasaakiNawatani** [comment]
Hello. We have had technical matter so please change your Data Cap request from 120GB to 120GiB. Sorry for your inconvenience. Then I will authorize your request.  Thank you.

**Comment by kenparalymart** [comment]
Thank you, I already changed it to 120 GiB

**Comment by MasaakiNawatani** [comment]
Hi @kenparalymart 

Thank you for your patience. Your request is still under review. Please allow 3-5 business days for a decision.

**Comment by MasaakiNawatani** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxmgnnmmyt55esycucnrbk5m2jfpzzpqlc65tad3wskbbx33fd6q 
#### Address 
> f3s4k4qjanlxpjh3ken7eqdnizlq3gors6tyoo33gxle7knnikp4oissy46mr3ujz3xs5s5dv2a55gb57ezzga
#### Datacap Allocated
> 120GiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxmgnnmmyt55esycucnrbk5m2jfpzzpqlc65tad3wskbbx33fd6q
