### ISSUE TITLE
Client Allocation Request for: LandSatFile / FilHub

### ISSUE THREAD

**Issue by hao1211** [filecoin-project/filecoin-plus-client-onboarding#115]
# Client Allocation Questions 

## Core Information
- Name:LandSatFile / FilHub
- Region: Greater China
- Website / Social Media:  http://preview.filhub.com
- DataCap Requested: 5 TiB
- Addresses to be Notarized: f3rikexkas2vxfhc6nbhla7hpunrp6as5msjx3wwndve6rfgzmyrliu2p3ypzdf74yzfwjhyqpnt6gj4xwzkoa

-----------------------------

**Comment by LandsatFile20** [comment]
1. yourself , e.g. include links to social media/news mentions, etc

Landsatfile team has been in Filecoin ecosystem from 2020-6-1, we established Fuzhou HaoNengCloud Technology Co., Ltd, and began to work as start-up company.
Since September 2020, we participated in Slingshot competition by Protocol Labs and developed an application named LandSatFile.
And then Start-up project: FilHub @ 2021-1-20  http://preview.filhub.com

Slingshot project link:https: //slingshot.filecoin.io/project/5fc274a7bb7b32dc2a0841d2
Project website: http://preview.filhub.com
Slack: @HaoChen-LandsatFile-FilHub

2.your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc

Participating in **Slingshot 2.2** with over **400 TiB data**
Participated in **Slingshot 2.1**
Eligible Data: over **100TiB**
Storage Awards: **2nd Place**


Start-up project: **FilHub** @2021-1-20  http://preview.filhub.com
@HaoChen-LandsatFile-FilHub  : **Actively help folks in the slack community, you can search for**.

3.type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data, etc

All of the data on Landsatfile are useful and valid, and from public datasets, which are on the list of Filecoin Slingshot curated datasets.
List of [Slingshot curated datasets](https://github.com/filecoin-project/slingshot/blob/master/datasets.md): 

4.your relationship with the data, especially with regard to copyright

All data are from public open datasets, as a result, there is no copyright issue involved.

5.how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Redundancy: at least 3 copies
Location: intend to store data in Asia now. and  our nodes in EU/NA, we can store data to EU/NA  before the middle of February 2021
Miner: have a great reputation and contribution in Filecoin Community, accept real data deals during Slingshot Competition, or are willing to store real data on Filecoin Network.
6.Would you be OK in posting deal transactions here?
Sure.

**Comment by philippbanhardt** [comment]
Hey @LandsatFile20 thanks for the additional information. Are you OK posting here transactions spending awarded datacap?

**Comment by LandsatFile20** [comment]
HI @philippbanhardt ,
from https://plus.fil.org/, only get 8g datacaps,
As our deals are 32g, so there is no transaction  (using awarded datacap ) record available.

here is our deals in slingshot 2.2:  https://slingshot.filecoin.io/project/5fc274a7bb7b32dc2a0841d2/deals?phase=2.2
In the future, when we apply for datacaps, we will effectively consider storing copies from different regions miners.

**Comment by philippbanhardt** [comment]
Hey @hao1211 would be great if you can insert here all future deals made as a verified client - thank you.

**Comment by philippbanhardt** [comment]
Also @hao1211 I just noticed that the address you listed here has already been awarded datacap. For me to be able to renew I need a new address.

**Comment by hao1211** [comment]
@philippbanhardt 

- new address :

f3rikexkas2vxfhc6nbhla7hpunrp6as5msjx3wwndve6rfgzmyrliu2p3ypzdf74yzfwjhyqpnt6gj4xwzkoa

- all future deals

1. Deal matchmaking between minerx Fellows and FilHubs.
2. Dataset (CCAFS-Climate Data) from  https://github.com/filecoin-project/slingshot/blob/master/datasets.md

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacednqy7pbj62bqsp27dej4mfp6y4jec35yqwrnqvyyeesoxxzkgihm 
#### Address 
> f3rikexkas2vxfhc6nbhla7hpunrp6as5msjx3wwndve6rfgzmyrliu2p3ypzdf74yzfwjhyqpnt6gj4xwzkoa
#### Datacap Allocated
> 5 TiB

**Comment by PatrickDeuse** [comment]
this data set gets sold on slack! great work

**Comment by LandsatFile20** [comment]
> this data cap gets sold on slack! great work

https://filecoinproject.slack.com/archives/C01KCAAURAN/p1613048550164000

**Comment by LandsatFile20** [comment]
### excel structure & links:

`deal_id | miner_id | payload_cid | filename | file_format | size_in_bytes | date | curated_dataset | deal_type | deal_cid | car_file | file_list_in_car | miner_location`

**It may take more than three days, miner download car files and import it**

1TiB filhub-cgiardata-f01240-slack@Wijnand Schouten.csv
https://drive.google.com/file/d/1JRH_n6o7977s9C71CDiMajsWC-iA7iRf/view?usp=sharing
1TiB filhub-cgiardata-f010479-slack@s0nik42.csv
https://drive.google.com/file/d/12WzgW5r9LohU22KF0lfvlP44GU19G-Fw/view?usp=sharing
1TiB filhub-cgiardata-f014768-slack@Funk.csv
https://drive.google.com/file/d/1DzOT0t2bqptVJNA1W7I7o6ySbffpF2ac/view?usp=sharing
1TiB filhub-cgiardata-f023467-slack@Phi-rjan.csv
https://drive.google.com/file/d/1DDOYR95Ut_FQ3Qx1lT8kGshXj9kNZ63U/view?usp=sharing
1TiB filhub-cgiardata-f047419-slack@DeeGee.csv
https://drive.google.com/file/d/1xNNnsVPWiQUeQlHH9VH9ONLvOrVhVNj2/view?usp=sharing
