### ISSUE TITLE
Client Allocation Request for: LG Whisen Dong-an Services

### ISSUE THREAD

**Issue by jpo92po** [filecoin-project/filecoin-plus-client-onboarding#1172]
# Client Allocation Questions 

## Core Information
- Name: LG Whisen Dong-an Services
- Website / Social Media: http://www.xn--lg-jw7jsd091c.com/
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3wltsiy2hntcezfl2d3smvbsiw22nz7zgltdvzpyysfbaqzlqdkqdufnehjgibkymr3vhhtjsmvcscnclzqmq
- Notary Requested: MasaakiNawatani

**Comment by MasaakiNawatani** [comment]
Hello @jpo92po 

Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

```
Please answer here.
```

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 

```
Please answer here.
```

**Allocation Strategy
Do you intend to store your data in a single geography or many?

```
Please answer here.
```

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

```
Please answer here.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
Please answer here.
```

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

```
Please answer here.
```

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

```
Please answer here.
```

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

```
Please answer here.
```

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

```
Please answer here.
```

Are there any disputes open against you from your previous DataCap allocations?

```
Please answer here.
```

**Comment by jpo92po** [comment]
Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

Hello.
I'm Sang Gyun, the software team leader.
LG Whisen has installed and processed air conditioners with a history of more than 20 years.
It is trusted and recognized by customers for its excellent technology in designing and installing air conditioners.
Major domestic construction companies such as Hyundai Engineering & Construction, GS Engineering & Construction, Ssangyong Engineering & Construction, etc.

The following are the cases where all online content generated during design work for installing system air conditioners is safely stored and provided to customers.
As a result of the meeting, we decided that the file coin project was suitable.
We are currently working to provide integrated management.

If you request data to be integrated into the FileCoin project, only some samples will be emailed.

Currently, the big data solution part is insufficient, but please help us become an innovative company that can take a leap forward.

Have you previously been approved for DataCap? If so, could you share the details of the last allocation decision (DataCap approver, usage plan, how to execute the plan)?

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)?

NO. First Time.

**Allocation Strategy
Do you intend to store your data in a single geography or many?

If the business is expanded starting with the An-yang data center, there are plans to store data in various countries.

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

Know about the quick search function. I plan to use it.

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

I am planning to manage it separately to protect the DataCap.

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

In order to safely store data, it will be distributed and stored among several miners.

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

100 TiB

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

We will abide by the rules and guidelines set out.

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

NO.

Are there any disputes open against you from your previous DataCap allocations?

NO.

Have you ever previously violated:

Your own attested allocation / audit plan?
Been found to be in violation of the Principles of Filecoin Plus?

NO.

**Comment by MasaakiNawatani** [comment]
Hi @jpo92po 

Thanks for your response. After reviewing the information you provided, I can provide datacap for you but the amount you are requesting is too large for a first time request. Please modify it to 1 TB.

**Comment by jpo92po** [comment]
I modified 1TB! Thank you

**Comment by MasaakiNawatani** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedo7hl2swpireonp3i6tz6rtm5h5fyqq6rooe5sny623gpqm5ozc6 
#### Address 
> f3wltsiy2hntcezfl2d3smvbsiw22nz7zgltdvzpyysfbaqzlqdkqdufnehjgibkymr3vhhtjsmvcscnclzqmq
#### Datacap Allocated
> NaNB
#### Signer Address
> f1fh53sdaie3yi25qxwcqxpt5h4naex5ibdaffibi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedo7hl2swpireonp3i6tz6rtm5h5fyqq6rooe5sny623gpqm5ozc6
