### ISSUE TITLE
Client Allocation Request for: Fivegives

### ISSUE THREAD

**Issue by fivegivesjp** [filecoin-project/filecoin-plus-client-onboarding#1188]
---

# Client Allocation Questions 

## Core Information
- Name: Fivegives
- Website / Social Media: https://fivegives.com
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f1efkgddkyruyu4dqxit5hiar6ttnzljmfxeyh7ty
- Notary Requested: MasaakiNawatani

@fivegivesjp Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MasaakiNawatani** [comment]
Hello @fivegivesjp 

Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

```
Please answer here.
```

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 

```
Please answer here.
```

**Allocation Strategy
Do you intend to store your data in a single geography or many?

```
Please answer here.
```

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

```
Please answer here.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
Please answer here.
```

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

```
Please answer here.
```

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

```
Please answer here.
```

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

```
Please answer here.
```

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

```
Please answer here.
```

Are there any disputes open against you from your previous DataCap allocations?

```
Please answer here.
```

**Comment by fivegivesjp** [comment]
> Hello @fivegivesjp
> 
> Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!
> 
> Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.
> 
> ```
>Established in 2011, FIVE GIVES Co., Ltd. provides influencer marketing utilizing social media and one-stop provision from planning to implementation of events regardless of offline / online. In order to provide the digital twin service, we hold a lot of photo data, spatial data, and document archive data. In recent years, we have managed about 800 game players as an NFT game operation consignment, and we are managing goals, achievements, and all data.

> ```
> 
> Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)?
> 
> ```
> This will be our first time to request for datacap.
> ```
> 
> **Allocation Strategy Do you intend to store your data in a single geography or many?
> 
> ```
> We intend to store data in regions where it is most needed. Mainly Japan and Philippines.

> ```
> 
> Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?
> 
> ```
> Yes. In fact, we are already building rich and robust API sets that can boost and make distributed storage a reality for all types of clients. 

> ```
> 
> How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
> 
> ```
> We are communicating some storage providers in Japan. We manage and maintain the storage with them and other storage providers in Japan first. Also, then we expand to other countries with very important data, we would store it in other countries by the data cap.

> ```
> 
> Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?
> 
> ```
> We intend to spread it across multiple miners who are willing to accept our deals.

> ```
> 
> For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?
> 
> ```
> We are applying as the client
> ```
> 
> Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?
> 
> ```
> Yes
> ```
> 
> **Track Record Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.
> 
> ```
>None
> ```
> 
> Are there any disputes open against you from your previous DataCap allocations?
> 
> ```
> None
> ```

**Comment by MasaakiNawatani** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatwtjwpnub6wjyin4okwcbyr4sfyf4ljlved2tx4bh6n6piww4hw 
#### Address 
> f1efkgddkyruyu4dqxit5hiar6ttnzljmfxeyh7ty
#### Datacap Allocated
> NaNB
#### Signer Address
> f1fh53sdaie3yi25qxwcqxpt5h4naex5ibdaffibi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatwtjwpnub6wjyin4okwcbyr4sfyf4ljlved2tx4bh6n6piww4hw
