### ISSUE TITLE
Client Allocation Request for: Codberg

### ISSUE THREAD

**Issue by jun950419** [filecoin-project/filecoin-plus-client-onboarding#1190]
Client Allocation Questions 
-----------------------------
Core Information
-----------------------------

- Name: Codberg

- Website / Social Media: https://codberg.co.kr

- Region: Asia excl. Greater China

- DataCap Requested: 1TiB

- Addresses to be Notarized: f01404908 

- Notary Requested: MasaakiNawatani

-----------------------------
Thank you.

**Comment by MasaakiNawatani** [comment]
Hello @jun950419 

Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

```
Please answer here.
```

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 

```
Please answer here.
```

**Allocation Strategy
Do you intend to store your data in a single geography or many?

```
Please answer here.
```

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

```
Please answer here.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
Please answer here.
```

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

```
Please answer here.
```

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

```
Please answer here.
```

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

```
Please answer here.
```

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

```
Please answer here.
```

Are there any disputes open against you from your previous DataCap allocations?

```
Please answer here.
```

**Comment by jay2400** [comment]
Hello @MasaakiNawatani 

Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!



Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

- Codeberg Co. Ltd is a core technology of the Fourth Industrial Revolution, augmented reality,
experience in developing various technologies such as artificial intelligence and blockchain, planning and developing platforms,
It is an IT R&D company with abundant operational experience.

We decided Filecoin project is suitable for protect our data asset.
In order to safely store the important data information of the services we provide, we believe that the FileCoin project is appropriate.

[Company Introduction-Codberg.pdf](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/7691117/Company.Introduction-Codberg.pdf)

Visit our Company Web 

https://codberg.co.kr/
https://filering.app/

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)?

- No. We have not been approved yet.
Its First apply.

**Allocation Strategy
Do you intend to store your data in a single geography or many?

- Single. We built a data center in Bucheon, Gyeonggi-do.

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

- Yeah, We deeply aware of Filecoin System, and we have prepared a plan.

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

- We will manage the fine Stringe separately to Protect the data cap.

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

- We will store in single miner.

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

- We request as clinet to seek  2TiB datacap.


Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

-  Yes. Sure.

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

- No.

Are there any disputes open against you from your previous DataCap allocations?

- No

**Comment by MasaakiNawatani** [comment]
Hi @jay2400 

I reviewed the information you provided and I'm ready to allocated datacap for you. However, please change your request from 10 TiB to 1 TiB. Thank you.

**Comment by jun950419** [comment]
@MasaakiNawatani

**Comment by jay2400** [comment]
Hi @MasaakiNawatani

I edit my document 10 TiB to 1TiB

Thank you!

sorry. Its my bad.
I use 2 account. One is my private the other is for company 
Sorry.

**Comment by MasaakiNawatani** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwr4yglfho7qipyfet64kpnqwap2pgbgqil6qwgj4xpfanc6mjqe 
#### Address 
> f01404908
#### Datacap Allocated
> NaNB
#### Signer Address
> f1fh53sdaie3yi25qxwcqxpt5h4naex5ibdaffibi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwr4yglfho7qipyfet64kpnqwap2pgbgqil6qwgj4xpfanc6mjqe
