### ISSUE TITLE
Client Allocation Request for: 北京远超敬邦科技发展有限公司

### ISSUE THREAD

**Issue by egwgrgreggrhhe** [filecoin-project/filecoin-plus-client-onboarding#1196]
---

# Client Allocation Questions 

## Core Information
- Name: 北京远超敬邦科技发展有限公司
- Website / Social Media: http://ycjb.fadonghui.com
- Region: Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3qiyu5tcfb5qbpynz36mzr7y5p72opqjzstctq65f7wpysk57ifre6hvizk2drfui74fs5xchlk42kxhhrekq
- Notary Requested: neogeweb3

@egwgrgreggrhhe Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by neogeweb3** [comment]
Hey @egwgrgreggrhhe, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1.	Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2.	If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3.	In which region(s) do you intend to use the DataCap? 
4.	What is your use case for the DataCap being requested? 
5.	Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6.	How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7.	Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?

Moreover, I encourage you to take a look of my allocation [strategy ](https://github.com/filecoin-project/notary-governance/issues/11) and [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)which shows how I utilize the assessment. Thanks.

**Comment by egwgrgreggrhhe** [comment]
Hello, Neo.
I am Chen Qiulin, the operation director of Beijing Yuanchao Jingbang Technology Development Co., LTD.  You can contact me by email at 2983207017@qq.com.  
 
Beijing Yuanchao Jingbang Technology Development Co., LTD.  is located in Beijing, China, is engaged in gas separation, industrial tail gas purification application research and technology transformation of science and technology company, the main direction is prepared by pressure swing adsorption method of industrial gas through a gas detection technology, preparation and collect data to monitor early warning of carbon dioxide and other greenhouse gases emissions,  So as to achieve carbon neutrality plan, early warning, plan.  The company is rooted in the field of industrial gas purification monitoring, focusing on energy conservation and environmental protection, carbon neutral supervision. In order to closely link with the forefront of industry technology, the company attaches importance to the application and development of new technology, and strives to build continuous listening products and services for the majority of industrial users.  
 
We plan to use these datacap in western China.  
 
These data are Internet open data, enterprise docking data and independent analysis data  
 
There is no advanced feature. 
 
More than 10 miners are working for us.  Right now it's randomly allocated to different miners.  
 
I'd love to.

**Comment by neogeweb3** [comment]
Hey @egwgrgreggrhhe, thanks for the information. My allocation strategy is to build trust progressively. So I could allocate 100 GiB to you for the first time. Feel free to request more DataCap when you use up the allocation.

**Comment by neogeweb3** [comment]
Allocation went through successfully: https://filfox.info/en/message/bafy2bzacedhpnqapvw7ronqzr3nrv6uuvith4t5w7yjknfspj5e55z3rhezjs
