### ISSUE TITLE
Client Allocation Request for: Opengate

### ISSUE THREAD

**Issue by jksfhajhflalf** [filecoin-project/filecoin-plus-client-onboarding#1211]
---

# Client Allocation Questions 

## Core Information
- Name: Opengate
- Website / Social Media: https://opengate.vip/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3u7sj4ffs45u2syntwqydlp23hlx2kdbuclvml3p4nx2cwjpuepc2nbifeuntuv2etqb2yjcmrlnnnytepybq
- Notary Requested: neogeweb3

@jksfhajhflalf Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by neogeweb3** [comment]
Hey @jksfhajhflalf, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1.	Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2.	If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3.	In which region(s) do you intend to use the DataCap? 
4.	What is your use case for the DataCap being requested? 
5.	Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6.	How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7.	Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?

Moreover, I encourage you to take a look of my allocation [strategy ](https://github.com/filecoin-project/notary-governance/issues/11) and [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)which shows how I utilize the assessment. Thanks.

**Comment by jksfhajhflalf** [comment]
1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.)
I am Qin Shishi, the main person in charge of publicity of OpenGate. I have rich artistic experience and am good at developing ideas or concepts into designs.  
Wechat id: QSS0823;  E-mail: 285198371 @qq.com  

2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
Introduction: OpenGate founded on December 31, 2020-20, OpenGate is an internationally renowned cryptographic digital art development agency. OpenGate is committed to "opening the door of the crypto art world and leading the Renaissance in the digital era", and is committed to promoting the development of the global crypto digital art market. The team is distributed in the United States, Canada, Australia, The United Kingdom, Beijing, Hong Kong, Guangzhou, Shenzhen and other countries and regions.
Wechat official account: 桥水相伴; Number of followers: 1000+
https://m.itouchtv.cn/article/08e093b76cbee97d874a00bfa7f0f495?shareId=ToxsMO3B

3. In which region(s) do you intend to use the DataCap?
We have no restrictions on storage areas.

4. What is your use case for the DataCap being requested?
Amount of data: about 20T
Data sources: videos created by the company and data stored by customers
Planning: The plan is to store all subsequent NFT works on the Filecoin network.
Data format: video, picture
All data is publicly available.

5. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
No advanced feature.

6. How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify.
We have cooperated with three miners, f01169692, f01308862, f01308857. And we will find more miners.

7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?
Yes.

**Comment by neogeweb3** [comment]
Hey @jksfhajhflalf, thanks for the information.  

> 3. In which region(s) do you intend to use the DataCap?
>    We have no restrictions on storage areas.

I am sure you don't have restrictions, but this is a question about DataCap allocation diversity. In the other word, where do you plan to use the DataCap? China, Europe, North America, etc. 
> 4. What is your use case for the DataCap being requested?
>    Amount of data: about 20T
>    Data sources: videos created by the company and data stored by customers
>    Planning: The plan is to store all subsequent NFT works on the Filecoin network.
>    Data format: video, picture
>    All data is publicly available.

For the large amount of DataCap requested, I highly recommend you to try the [LDN](https://github.com/filecoin-project/filecoin-plus-large-datasets), as I won't be able to provide this amount of DataCap to you at once.

**Comment by jksfhajhflalf** [comment]
We intend to store in China.
We only have 20 TB, and it is not enough to apply for LDN.

**Comment by neogeweb3** [comment]
Hey @jksfhajhflalf, I understood. My allocation strategy is to build trust progressively. So I could allocate 100 GiB to you for the first time. Feel free to request more DataCap when you use up the allocation.

**Comment by neogeweb3** [comment]
Allocation went through successfully: https://filfox.info/en/message/bafy2bzacec7use5ucwbr3qu3thzcmnicmsj3aici33bxucxoxtmf2zh36vnby
