### ISSUE TITLE
Client Allocation Request for: Yoshihito Kagami Photography

### ISSUE THREAD

**Issue by kagamiphoto** [filecoin-project/filecoin-plus-client-onboarding#1224]
---

# Client Allocation Questions 

## Core Information
- Name: Yoshihito Kagami Photography
- Website / Social Media: https://kagamiphoto.com
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f1pmvlr2vmc3f5mpketckupq6rmw674qdd2pnruny
- Notary Requested: MasaakiNawatani

@kagamiphoto Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

.

**Comment by MasaakiNawatani** [comment]
Hello @kagamiphoto 

Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

```
Please answer here.
```

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 

```
Please answer here.
```

**Allocation Strategy
Do you intend to store your data in a single geography or many?

```
Please answer here.
```

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

```
Please answer here.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
Please answer here.
```

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

```
Please answer here.
```

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

```
Please answer here.
```

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

```
Please answer here.
```

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

```
Please answer here.
```

Are there any disputes open against you from your previous DataCap allocations?

```
Please answer here.
```

**Comment by kagamiphoto** [comment]
> Hello @MasaakiNawatani 
> 
> 
> Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.
> 
> ```
> Since our establishment in 2013, we have always been thinking about "what is the photo that is transmitted to our clients?" , I have been making a living by taking photographs such as completed photographs of new houses, product photographs used in corporate advertisements and magazines, and portraits of managers. Since 2019, we have been providing digital twin services by "Matterport" listed on NASDAQ in the United States, and we are providing virtual showrooms using VR to major foreign automobile sales companies and major building material manufacturers. By combining the technologies of photography x VR x 3DCG, the handling of large data continues to increase in order to create not only "photographs that are transmitted" but also "visuals that are transmitted".

> ```
> 
> Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)?
> 
> ```
> No
> ```
> 
> **Allocation Strategy Do you intend to store your data in a single geography or many?
> 
> ```
> We plan to store in regions where it is most needed. Mainly in Japan. 
> ```
> 
> Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?
> 
> ```
> Yes, and we are in the process of developing APIs that can help ensure fast retrieval for the photos stored. 
> ```
> 
> How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
> 
> ```
>We are communicating some storage providers in Japan. We manage and maintain the storage with them and other storage providers in Japan first. Also, then we expand to other countries with very important data, we would store it in other countries by the data cap.
> ```
> 
> Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?
> 
> ```
> Multiple miners who will agree to deal with us. 
> ```
> 
> For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?
> 
> ```
> We are applying as the client
> ```
> 
> Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?
> 
> ```
> Yes
> ```
> 
> **Track Record Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.
> 
> ```
> No
> ```
> 
> Are there any disputes open against you from your previous DataCap allocations?
> 
> ```
> None
> ```

**Comment by MasaakiNawatani** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpccvxrpeuc7crmop4j557yyhg5xvjtgdiduycq36tf4ozju2p52 
#### Address 
> f1pmvlr2vmc3f5mpketckupq6rmw674qdd2pnruny
#### Datacap Allocated
> NaNB
#### Signer Address
> f1fh53sdaie3yi25qxwcqxpt5h4naex5ibdaffibi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpccvxrpeuc7crmop4j557yyhg5xvjtgdiduycq36tf4ozju2p52
