### ISSUE TITLE
Client Allocation Request for: Happy Future

### ISSUE THREAD

**Issue by lnrboss** [filecoin-project/filecoin-plus-client-onboarding#1233]
---

# Client Allocation Questions 

## Core Information
- Name: Joyful Future
- Website / Social Media: http://ecojf.com/index_.php
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3wulqe6ljt2ymj7ih6ydllgemx5vknfevg3s4ggbssnysi7lebsbzf3mxsrt2vsx7rxky665ncz7me5cjj7ha
- Notary Requested: MasaakiNawatani

@lnrboss Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MasaakiNawatani** [comment]
Hello @lnrboss 

Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

```
Please answer here.
```

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 

```
Please answer here.
```

**Allocation Strategy
Do you intend to store your data in a single geography or many?

```
Please answer here.
```

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

```
Please answer here.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
Please answer here.
```

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

```
Please answer here.
```

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

```
Please answer here.
```

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

```
Please answer here.
```

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

```
Please answer here.
```

Are there any disputes open against you from your previous DataCap allocations?

```
Please answer here.
```

**Comment by lnrboss** [comment]
> Hello @lnrboss
> 
> Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!
> 
> Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.
> 
> ```
> Please answer here.
   Our company was established in 2005 and currently has 30 employees. Our company has a patent for eco-friendly liquid deicing agent, and based on this, we have built a remote deicing disaster prevention system using IoT technology. It operates about 1,800 systems nationwide, and demand is expected in line with the eco-friendly ecosystem in the future more and more.
> ```
> 
> Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)?
> 
> ```
> Please answer here.
   No, We've never done that.
> ```
> 
> **Allocation Strategy Do you intend to store your data in a single geography or many?
> 
> ```
> Please answer here.
   It can be allocated to single geography (Korea).
> ```
> 
> Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?
> 
> ```
> Please answer here.
   Yes, We are aware of.
> ```
> 
> How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
> 
> ```
> Please answer here.
   One delegated person will manage DataCap allocations and the person in charge will control him.
> ```
> 
> Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?
> 
> ```
> Please answer here.
   If necessary, it can be allocated to several minor.
> ```
> 
> For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?
> 
> ```
> Please answer here.
   It’s not the case. We don’t allocate DataCaps for each user.
> ```
> 
> Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?
> 
> ```
> Please answer here.
   Yes, We do.
> ```
> 
> **Track Record Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.
> 
> ```
> Please answer here.
   No. We've never receiced it.
> ```
> 
> Are there any disputes open against you from your previous DataCap allocations?
> 
> ```
> Please answer here.
   No.
> ```
[JoyfulFuture_profile.pdf](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/7749896/JoyfulFuture_profile.pdf)

**Comment by lnrboss** [comment]
Sorry, I misunderstood.

**Comment by MasaakiNawatani** [comment]
I reviewed the information you provided and I edited your request to 1 TB. I will allocate that today.

**Comment by MasaakiNawatani** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwrrulxnqfgo4sgjl3e3qzczf6j7xwv72nh7hvzof7mz5ufawgui 
#### Address 
> f3wulqe6ljt2ymj7ih6ydllgemx5vknfevg3s4ggbssnysi7lebsbzf3mxsrt2vsx7rxky665ncz7me5cjj7ha
#### Datacap Allocated
> NaNB
#### Signer Address
> f1fh53sdaie3yi25qxwcqxpt5h4naex5ibdaffibi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwrrulxnqfgo4sgjl3e3qzczf6j7xwv72nh7hvzof7mz5ufawgui

**Comment by ujoonet** [comment]
Thank you!

**Comment by lnrboss** [comment]
Thank you !
