### ISSUE TITLE
Client Allocation Request for: jack&me

### ISSUE THREAD

**Issue by sghmok** [filecoin-project/filecoin-plus-client-onboarding#124]
---

# Client Allocation Questions 

## Core Information
- Name: jack&me
- Website / Social Media: https://www.jackandme.io/
- Region: Greater China
- DataCap Requested: 10GiB
- Addresses to be Notarized: f1x76c6drtrvt5wucoaool2rwl3v7l4g332xvgmbq
- Notary Requested: NeoGe-IPFSMain

**Comment by NeoGe-IPFSMain** [comment]
Hey @sghmok, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can.

1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.)
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3. In which region(s) do you intend to use the DataCap?
4. What is your use case for the DataCap being requested?
5. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
6. How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify.
7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

Before starting to answer questions, I encourage you to take a look of our allocation strategy here which shows how we utilize the assessment.

Thanks.

**Comment by sghmok** [comment]
Hello @NeoGe-IPFSMain.
I am the product algorithm director of jack&me. I have been working on algorithms for more than 5 years. I used to do algorithm research at China Advanced Technology Research Institute.
GitHub: @sghmok

We, Jack&Me, are an idle computing power integration platform that volunteers to contribute the integrated computing power to scientists and institutions in cutting-edge scientific research around the world.
We are committed to making it easy for ordinary people to contribute to cutting-edge science. At present, our integrated computing power exceeds 2TiB/day.

 Here are some reports from the media about the introduction and application of Jack&Me:
https://mp.weixin.qq.com/s/XzVZnWdb13fLuxf4I8maBQ
https://www.chainnode.com/post/503408
http://www.fjznews.com/html/health/1c84ff51e2a8db6ce993b659.html

We are going to use DataCap in China.

We are ready to store the original materials (pictures, videos, audio and other public data) participating in AI training into the Filecoin network.

We don't understand what advanced features are.

We are not going to designate specific miners who allocate DataCap.

Obviously, we are willing to post detailed transaction information here after storing the data.

 Thank you.

**Comment by NeoGe-IPFSMain** [comment]
Hey @sghmok, sorry for the delays during the holiday season, future requests would be processed at a faster pace. My allocation strategy is to build trust progressively. So I could allocate 10 GiB to you for the first time. Feel free to request more DataCap when you use up the allocation. 

To better understand how future allocation looks, please take a look [here ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)for my allocation process.

**Comment by NeoGe-IPFSMain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecaa4dzkmujvjn7sttqqsofnawzf6vk5duyqo625mro7rn6f76xco 
#### Address 
> f1x76c6drtrvt5wucoaool2rwl3v7l4g332xvgmbq
#### Datacap Allocated
> 10 GiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecaa4dzkmujvjn7sttqqsofnawzf6vk5duyqo625mro7rn6f76xco
