### ISSUE TITLE
Client Allocation Request for: Edenvalley Resort

### ISSUE THREAD

**Issue by frametable** [filecoin-project/filecoin-plus-client-onboarding#1467]
---

# Client Allocation Questions 

## Core Information
- Name: Edenvalley Resort
- Website / Social Media: http://edenvalley.co.kr/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3wkli64jh2oqnt47xni75hic2mbsodamwcrave5xqzf44jn3q3mk3pncylwzmgwxmsa3c5md23fw3o72wfysa
- Notary Requested: IreneYoung

@frametable Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IreneYoung** [comment]
Hi @frametable    - Thanks for your application. Please answer the following questions to let us know about you, your company, and further information about the DataCap allocation.

> ## Basic Info
1. What's your name and your position in your company?

2. Please introduce yourself and your team briefly. How many team members do you have in your R&D or core team? Could you provide several Github accounts or email addresses of them?

3. For your organization, Please describe its business, its history since inception, registration country, scale, employee counts, operation regions, named executive officers, relevant projects, industry reputation, etc.

4. Please show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links) to show your Web3 reputation or external reputation. 

5. Please provide your company's business registration license. If you have any presentation documents about your business, please provide them to us. And also could send me via email for privacy concerns. My contact: irene@12ships.com

6. How long have the team core members been engaged in development?

7. What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?

8. Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization?

9. Where is your data stored now? Whether the data is stored on a server or a cloud service provider?

> ## Track Record
1. Has your organization obtained DataCap before? if so, please answer the following sub-questions.
1.1 Please share all the links and recordings of your applications before.
1.2 How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?
1.3 What was your allocation strategy plan then and how did you execute it?

2. Are there any disputes open against you from your previous DataCap allocations? If any, please describe any of your honors or disputes in the field of Filecoin.

> ## Allocation Plan

1. Please describe your plan to use the DataCap as detailed as possible, including use case, amount, timespan, geography, storage providers, partners, etc. 

2. How many regions do you plan to store the data in? 

3. How many storage providers you intend to make dealing with?

4. Do you plan to record your allocation decisions and execution details in public? And how to realize it?

5. Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?

We may further ask some questions and then give an accurate score to the application. Thank you for your cooperation!

**Comment by frametable** [comment]
Hi Irene, happy lunar new year!

Thanks for getting back to me. I've been gathering up the requested information, and hopefully will get back to you shortly. 

Thanks and regards,
Brian

**Comment by frametable** [comment]
Hi Irene,
Please see below for the requested information and do let me know should you need additional information.

What's your name and your position in your company?
→  My name is Brian Bae; I head Edenvalley Resort’s new business development activities.

Please introduce yourself and your team briefly. How many team members do you have in your R&D or core team? Could you provide several Github accounts or email addresses of them?
→ I have 8 members in my team. Everyone in the team is considered as core members related to the current project. Please see below for the list of team members’ emails. 
Name			Email
Kim Jae-Ho		jhkim3311@edenvalley.co.kr 
Lee Sang-Won	swlee@edenvalley.co.kr
yun yoo-Gyung	ygyun@edenvalley.co.kr
Hwang Ah-Yeon	ayhwang@edenvalley.co.kr
Kim Ae-Ri		arkim@edenvalley.co.kr
Park Geun-Woo	gwpark@edenvalley.co.kr
Jeong Dong-Uk	dujeong@edenvalley.co.kr
Kim Sang-Hyun	shkim@edenvalley.co.kr


For your organization, Please describe its business, its history since inception, registration country, scale, employee counts, operation regions, named executive officers, relevant projects, industry reputation, etc.
→ Evenvalley Resort is a full scale leisure/sports experience resort registered and established in 2012, located in Yangsan, South Korea. Edenvalley provides various sporting activities such as golf, ski, luge, cart racing, ATV, mountain bike and many others all year round to its member clients. The number of employees counts around 350 and it varies seasonally. Edenvalley resort known to be the only resort that provides ski/snowboard services in the southern Gyunsang provinces in Korea.

Please show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links) to show your Web3 reputation or external reputation.
→ Please refer to the following links for Edenvalley’s web pages and blogs.
https://edenvalley.co.kr/
https://blog.naver.com/edenvalley
https://blog.naver.com/edenskischool
https://www.facebook.com/edenvalleya
https://www.instagram.com/_edenvalley_/
https://booking.naver.com/booking/5/bizes/599640
http://www.edenvalley.co.kr/edenvalley_luge/main.html
http://golf.edenvalley.co.kr/
http://edenvalley_moa.lscompany-coupon.com/
https://eden.ampass.kr/



Please provide your company's business registration license. If you have any presentation documents about your business, please provide them to us. And also could send me via email for privacy concerns. My contact: irene@12ships.com
→ Business registration will be emailed to irene@12ships.com

How long have the team core members been engaged in development?
→ 9 months

What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?
→ We are developing services that will integrate and store customers’ non-confidential data and activity history generated at the resort. We plan to store both files related to the operation of the service and the customers’ history. Files will be mostly pictures and video files that are taken as part of resort leisure activities. Customers valuable experience at the resort will be stored on Filecoin network with peace of mind. 

Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization?
→ Data is originated from Edenvalley's equipments and Edenvalley employees' equipments, gathered upon the client's consent. 

Where is your data stored now? Whether the data is stored on a server or a cloud service provider?
→ Local NAS.




Track Record
Has your organization obtained DataCap before? 
→ No

Are there any disputes open against you from your previous DataCap allocations? If any, please describe any of your honors or disputes in the field of Filecoin.
→ No




Allocation Plan
Please describe your plan to use the DataCap as detailed as possible, including use case, amount, timespan, geography, storage providers, partners, etc.
How many regions do you plan to store the data in?
--> One region (in Asia ex. China)

How many storage providers you intend to make dealing with?
--> One or two, depending on the needs

Do you plan to record your allocation decisions and execution details in public? And how to realize it?
--> If needed, yes.

Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?
--> Absolutely, yes.

**Comment by frametable** [comment]
Hi Irene,

Can you please let me know if you need additional information prior to approval, or you just need time to process?

Thanks and regards,
Brian

**Comment by IreneYoung** [comment]
Hi @frametable - Yes we are verifying the request, which is expected to get back to you within 1 day.

**Comment by frametable** [comment]
Thanks for the update, Irene. :)

**Comment by IreneYoung** [comment]
@frametable Thanks for your reply.

The initial score of your DataCap request is 4.
10TiB DataCap are being granted to you within 1 business day. Congratulate!
See more details here: https://docs.google.com/spreadsheets/d/1UYY7AcXMAy376kjqKcCgcwb4-WrTKBEshYgJllNQtlk/edit#gid=2145086174

**Comment by frametable** [comment]
Hi Irene,
Thanks very much for such a good news!

Have a happy friday.

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebe62fb4ewkukhee4nzzhnbhhe3eueirvuhxgjv55mq72p6hg5472 
#### Address 
> f3wkli64jh2oqnt47xni75hic2mbsodamwcrave5xqzf44jn3q3mk3pncylwzmgwxmsa3c5md23fw3o72wfysa
#### Datacap Allocated
> 10.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebe62fb4ewkukhee4nzzhnbhhe3eueirvuhxgjv55mq72p6hg5472
