### ISSUE TITLE
Client Allocation Request for: Coresight

### ISSUE THREAD

**Issue by Coresight** [filecoin-project/filecoin-plus-client-onboarding#1515]
---

# Client Allocation Questions 

## Core Information
- Name: Coresight
- Website / Social Media: http://www.coresight.io/
- Region: Asia excl. Greater China
- DataCap Requested: 30TiB
- Addresses to be Notarized: f1fk4jpp6sn6tqxdnrsyppl6jdtymm3hharvzd7fi
- Notary Requested: ozhtdong

@Coresight Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
What's your name and your position in your company?

Please introduce yourself and your team briefly. How many team members do you have in your R&D or core team? Could you provide several Github accounts or email addresses of them?

For your organization, Please describe its business, its history since inception, registration country, scale, employee counts, operation regions, named executive officers, relevant projects, industry reputation, etc.

Please show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links) to show your Web3 reputation or external reputation.

Please provide your company's business registration license. If you have any presentation documents about your business, please provide them to us. 
How long have the team core members been engaged in development?

What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?

Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization?

Where is your data stored now? Whether the data is stored on a server or a cloud service provider?

**Comment by ozhtdong** [comment]
Please apply to your local notary.
