### ISSUE TITLE
Client Allocation Request for: NBFS Canada

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/filecoin-plus-client-onboarding#153]
---

# Client Allocation Questions 

## Core Information
- Name: NBFS Canada
- Website / Social Media: nbai.io
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3ufzpudvsjqyiholpxiqoomsd2svy26jvy4z4pzodikgovkhkp6ioxf5p4jbpnf7tgyg67dny4j75e7og7zeq
- Notary Requested: andrewxhill

**Comment by andrewxhill** [comment]
Hey @flyworker, thanks for the request. I have some questions regarding your request. I know some things about your work already, but it's helpful to have this all in a public records. Please provide as thorough of answers as you can. 

1. Can you introduce yourself? Where can I find you online? Examples include Github, Twitter, LinkedIn, WeChat, etc., and more than one is encouraged.
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3. In which region(s) do you intend to use the DataCap?
4. What is your use case for the DataCap being requested?
5. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
6. How many miners do you plan on allocating the DataCap? Please specify if you have a specific miner(s) you would like to allocate the DataCap.
7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing? If so, how will you plan to report it?
8. Will your organization be responsible for allocating the full DataCap? Examples where this might not be the case, include app builders where the application end-users may have access to storage backed by the DataCap. Please read our full proposal for details on this approach. It is not read today, but when it is, we will provider further documentation.

Thanks.
Andrew

**Comment by flyworker** [comment]
1.     Can you introduce yourself? Where can I find you online? Examples include Github, Twitter, LinkedIn, WeChat, etc., and more than one is encouraged.

Charles Cao, CEO of Nebula AI inc.
* History working on IPFS / Filecoin
Contributor to Calibration/SR1/SR2/Slingshot and multiple slack community champion
Integrate IPSF/Filecoin into GPU cloud computing platform Orion deep learning 
* Github: https://github.com/flyworker
* LinkedIn: https://www.linkedin.com/in/charles-cao-09a79526/

2.     If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?

NBFS Canada is a Filecoin mining brand owns by Nebula AI inc. Nebula AI inc. is registrated in November 2017 in Canada, head-office Montreal, Canada

* CEO Charles Cao
https://www.linkedin.com/in/charles-cao-09a79526/

* COO Rex Miller
https://www.linkedin.com/in/rexhold/

* Twitter: https://twitter.com/nbfscanada
* Linkedin: https://www.linkedin.com/company/nebula-ai
* website:
https://www.nbfspool.com/
https://nbai.io
https://www.cengn.ca/nebula-ai/
* YouTube: https://www.youtube.com/channel/UCWltsUAyiser4-_eLLGmpdg

3.     In which region(s) do you intend to use the DataCap?
Primary in North America,but also have backup copy in EU
4.     What is your use case for the DataCap being requested?
Data for Machine Learning

5.     Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
Offline deals transmission, data fast retrieval, data analysis platform 

6.     How many miners do you plan on allocating the DataCap? Please specify if you have a specific miner(s) you would like to allocate the DataCap.

We plan to locate data cap to 5 miners, they are miner in Canada, US and EU, e.g. f019104, f010617，f022142, f01278,f010446

7.     Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing? If so, how will you plan to report it?
Yes, we can publish the deals, miner id and data source.

8.     Will your organization be responsible for allocating the full DataCap? Examples where this might not be the case, include app builders where the application end-users may have access to storage backed by the DataCap. Please read our full proposal for details on this approach. It is not read today, but when it is, we will provider further documentation.
Yes, we will

**Comment by andrewxhill** [comment]
Hey @flyworker I forgot to ask, have you received datacap previously?

**Comment by flyworker** [comment]
Yes we have 5TB before.
Application history 
https://github.com/keyko-io/filecoin-clients-onboarding/issues/38

**Comment by andrewxhill** [comment]
hey @flyworker sorry, we attempted to finalize this yesterday but the address is the same as the one you submitted previously. it's not possible (yet) to gain datacap a second time for the same address. could you submit a fresh address for this time around?

**Comment by flyworker** [comment]
Hi @andrewxhill  Yes, we have a new one for it

f3tektw5tqjnxbcdybnp7kcskg7t3rndvvcu5w7usx7m3exqsfkxezncpefsf6fmianjvwkc2qw5qsiim6luua

Thanks

**Comment by andrewxhill** [comment]
okay, moving forward with `f3rkcl5lnoumsunl3grsy2b57z7zt6uoyvgnviz2dw3ir7sslnya2634as2ksfxzziuxzgubavqsb3s2fmofcq`

**Comment by andrewxhill** [comment]
Confirmed: https://filfox.info/en/message/bafy2bzaceawjv3ntsg5jfke32k7d3jiucckf7p74chcrtchpd6k4wkrwhbs6q
