### ISSUE TITLE
Client Allocation Request for: anne

### ISSUE THREAD

**Issue by 1ane-1** [filecoin-project/filecoin-plus-client-onboarding#1584]
---

# Client Allocation Questions 

## Core Information
- Name: anne
- Website / Social Media: https://sdcloud.on.fleek.co/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3ra4qdlsjp2nm5sji3p4fs2f5vnwn7yjgq43csz5low37s44lc3jyhec57kjonmfnjfrlwpx44bgwfr6hqboa
- Notary Requested: neogeweb3

@1ane-1 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by neogeweb3** [comment]
Hey @1ane-1, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1.	Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2.	If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3.	In which region(s) do you intend to use the DataCap? 
4.	What is your use case for the DataCap being requested? 
5.	Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6.	How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7.	Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?

Moreover, I encourage you to take a look of my allocation [strategy ](https://github.com/filecoin-project/notary-governance/issues/11) and [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)which shows how I utilize the assessment. Thanks.

**Comment by neogeweb3** [comment]
Since your company name is Zhongchuang power, do you recognize #606? Is this request from the same entity?

**Comment by 1ane-1** [comment]
> 

yes, it is from same company, but with different groups. we just want to seal our charity data.

**Comment by neogeweb3** [comment]
Hey @1ane-1, thanks for the clarification. Since you have requested DataCap from me before, I have some questions regarding your previous DataCap allocation. #606 
1.	How much cumulative DataCap was allocated to you from me?
2.	In which region(s) did you use the DataCap?
3.	What was your use case for the previous allocation? 
4.	Did you specify any advanced features for the previous allocation? 
5.	How many miners did you allocate the DataCap to? Please specify transaction links to the storage deals. 
6.	In your previous allocation, did you violent any community principles like excessive/unfair (20% of DataCap allocation) self-dealing?

**Comment by 1ane-1** [comment]
1. as for me, this is my first time apply datacap on IPFSMain. The other datacap that i knew was https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/606  that applied by other groups.
2.the datdacap mainly used in China
3.the previous use case was surveillance video
4.I didn't specify any advanced features.
5.maybe 3 miners, we have the deal list.
[realdata.txt](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/8249676/realdata.txt)
6.i didn't violent any community principles.

**Comment by neogeweb3** [comment]
Hey @1ane-1, thanks for waiting. I could allocate 100 GiB to you for the first time. Feel free to request more DataCap when you use up the allocation.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
