### ISSUE TITLE
Client Allocation Request for: Jonathan Victor

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/filecoin-plus-client-onboarding#160]
---

# Client Allocation Questions 

## Core Information
- Name: Jonathan Victor
- Website / Social Media: @jnthnvctr on Filecoin Slack
- Region: North America
- DataCap Requested: 100GiB
- Addresses to be Notarized: f1arlxnqbq2bpyw7wzcz7stnsr4v24xuwaj7p2uhq
- Notary Requested: andrewxhill

**Comment by jnthnvctr** [comment]
For some context - I'm hoping to get 100GiB of DataCap so we can start storing the FIL+ governance meetings on Filecoin! 

Game plan is to download the Zoom recordings, and store redundantly across 5ish miners post meeting. 
Since each meeting is 400-600MiB, I think this will last for quite a while. 

Info for retrieval will be posted into the Notary governance repo.

**Comment by andrewxhill** [comment]
Hey @jnthnvctr, thanks for the request. I have some questions regarding your request. I know we informally discussed some of these, but could you include details here. Please describe answers as much specificity as you can.

1. Can you introduce yourself? Where can I find you online? Examples include Github, Twitter, LinkedIn, WeChat, etc., and more than one is encouraged.
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3. In which region(s) do you intend to use the DataCap?
4. What is your use case for the DataCap being requested?
5. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
6. How many miners do you plan on allocating the DataCap? Please specify if you have a specific miner(s) you would like to allocate the DataCap.
7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing? If so, how will you plan to report it?
8. Will your organization be responsible for allocating the full DataCap? Examples where this might not be the case, include app builders where the application end-users may have access to storage backed by the DataCap. Please [read our full proposal](https://github.com/filecoin-project/notary-governance/issues/53) for details on this approach. Unfortunately, our proposed multisig enabled DataCap provider is not ready today, but when it is, we will provider further documentation.

Thanks,

Andrew

**Comment by jnthnvctr** [comment]
1. Hi - Yep, you can find me on linkedin [here](https://www.linkedin.com/in/jonathan-victor-69a44255/)
2. Protocol Labs, Registration is in the US, incepted in 2014, Juan Benet is the CEO
3. Intend to use this in the US
4. Use case: Primarily to store copies of the FIL+ meetings on FIL. Aim will be to make ~5 copies of the video with miners. 
5. Fast retrieval! Hopefully so folks can view the zoom meetings off FIL retrievals not just the Zoom cloud. 
6. Likely will do 5-6 at a time, and will likely do rotations of miners across geographies. 
7. Yep! I'll post the deal info (and retrieval info) in the Notary Governance repo so people can request it themselves. 
8. It will be PL managed - primarily by myself, @dkkapur, and potentially @ribasushi

**Comment by andrewxhill** [comment]
Thanks for the details. @jnthnvctr is already a known//verified member of the said organization. I'll allocate 100Gib today.

**Comment by jnthnvctr** [comment]
hi @andrewxhill  could we actually send that DataCap to this address: f1s566sc7nmxo7b7qml7m6s72uwmljg6k5orliolq

I think I may have blocked the last one with a previous verification from verify.glif.io

**Comment by andrewxhill** [comment]
Thanks. Confirmed https://filfox.info/en/message/bafy2bzacedvy7yhjhkj4jf4o6b7lglbv57fraue2pfxzuf2wnkjrm5g62zzce
