### ISSUE TITLE
Client Allocation Request for: BigD Exchange

### ISSUE THREAD

**Issue by JackFsy** [filecoin-project/filecoin-plus-client-onboarding#1741]
---

# Client Allocation Questions 

## Core Information
- Name: BigD Exchange
- Website / Social Media: www.bigd.exchange
- Region: Asia excl. Greater China
- DataCap Requested: 480TiB
- Addresses to be Notarized: f1cknbfzj656hmk6hqrblzs24ecv6ndg5pmxt5aka
- Notary Requested: IreneYoung

@JackFsy Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by JackFsy** [comment]
Hey @IreneYoung , BigData Exchange [www.bigd.exchange](url) is an auction style platform to connect clients with data and storage providers with storage capacity. With the current demand for Filecoin plus deals, we aim to create an innovative “**store-to-earn**” incentive structure to drive awareness and adoption of Filecoin. After product launch, we have onboarded 400TiB dataset to the product with competitive bids from different storage providers. We would like to apply for 200TiB DataCap for us to start several auctions next month. The dataset we use will be public open dataset stored in AWS S3 like https://registry.opendata.aws/noaa-gestofs/; https://registry.opendata.aws/paracrawl/;  https://registry.opendata.aws/noaa-cdr-fundamental/

Please kindly suggest if any other details are needed.

**Comment by IreneYoung** [comment]
Hi @JackFsy  Thanks for your application. Please answer the following questions to let us know about you, your company, and further information about the DataCap allocation.

Basic Info
What's your name and your position in your company?

Please introduce yourself and your team briefly. How many team members do you have in your R&D or core team? Could you provide several Github accounts or email addresses of them?

For your organization, Please describe its business, its history since inception, registration country, scale, employee counts, operation regions, named executive officers, relevant projects, industry reputation, etc.

Please show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links) to show your Web3 reputation or external reputation.

Please provide your company's business registration license. If you have any presentation documents about your business, please provide them to us. And also could send me via email for privacy concerns. My contact: [irene@12ships.com](mailto:irene@12ships.com)

What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?

Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization?

Track Record
Has your organization obtained DataCap before? if so, please answer the following sub-questions.
1.1 Please share all the links and recordings of your applications before.
1.2 How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?
1.3 What was your allocation strategy plan then and how did you execute it?

Are there any disputes open against you from your previous DataCap allocations? If any, please describe any of your honors or disputes in the field of Filecoin.

Allocation Plan
Please describe your plan to use the DataCap as detailed as possible, including use case, amount, timespan, geography, storage providers, partners, etc.

How many regions do you plan to store the data in?

Do you plan to record your allocation decisions and execution details in public? And how to realize it?

Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?

We may further ask some questions and then give an accurate score to the application. Thank you for your cooperation!

**Comment by JackFsy** [comment]
Hey @IreneYoung , please kindly see the responses below.

**Basic Info**
**What's your name and your position in your company?**
I am Jack Fan and I am currently in charge of product operations for BigData Exchange (https://www.bigd.exchange/). 
**Please introduce yourself and your team briefly. How many team members do you have in your R&D or core team? Could you provide several Github accounts or email addresses of them?**
We are a global team with over 30 team members. For BigData Exchange related issues, here is the email address for contact: info@bigd.exchange:
**For your organization, Please describe its business, its history since inception, registration country, scale, employee counts, operation regions, named executive officers, relevant projects, industry reputation, etc.**
BigData Exchange is an auction-style marketplace to connect clients with Fil+ data and storage providers with storage capacity. Headquartered and operated in Singapore, there are currently over 30 people globally in the core team. 
With the current demand for Filecoin plus deals, there are several benefits that BigData Exchange brings to the Filecoin network:

- An innovative storage platform to incentivize more people to source, migrate, and store valuable public data on Filecoin
- A transparent marketplace to connect Fil+ clients and storage providers, which adds visibility to the SP selection process and prevents potential self-dealing activities
- An index of public data stored on Filecoin, which paves the way to a vibrant retrieval and service market for Fil+ deals
**Please show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links) to show your Web3 reputation or external reputation.**
BigData Exchange: https://www.bigd.exchange/ 
BigData Exchange Twitter: https://twitter.com/BigD_Exchange 
**Please provide your company's business registration license. If you have any presentation documents about your business, please provide them to us. And also could send me via email for privacy concerns. My contact: [irene@12ships.com]****(mailto:irene@12ships.com)**
We are not required to have a licence. 
**What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?**
After product launch, we have onboarded 400TiB dataset to the product with competitive bids from multiple storage providers. We would like to apply for a 480TiB DataCap for us to start several auctions next month. The dataset we use will be public open dataset stored in AWS S3: https://registry.opendata.aws/noaa-gestofs/ (75TiB); https://registry.opendata.aws/wrf-se-alaska-snap/ (35TiB); https://registry.opendata.aws/wpto-pds-us-wave/ (50TiB)
We are planning to store 3 replicas for each dataset. Thus, we would like to apply for (75+35+50) x 3 = 480TiB of DataCap in this application. 
**Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization?**
The datasets used will be publicly accessible in AWS S3. Datasets’ URLs are listed above. 
**Track Record
Has your organization obtained DataCap before? if so, please answer the following sub-questions.**
**1.1 Please share all the links and recordings of your applications before.**
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1430
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1692 
**1.2 How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?**
The DataCap is used in auctions. We are currently working with storage providers who won the auctions on deal making. The auction links are listed below for reference:
https://www.bigd.exchange/detail/2
https://www.bigd.exchange/detail/1 
Several Fil+ clients are onboarding public data to BigData Exchange and they are currently in the midst of preparing dataset for auctions. Meanwhile, we would like to ensure there are sufficient Fil+ datasets in the auction listing to drive more awareness and adoption. We are seeing strong demand and would love to keep the momentum going. Thus, we hope you can grant us approval for 200TiB Datacap first, ideally by end of May so that we can continue to keep up with demand. 
**1.3 What was your allocation strategy plan then and how did you execute it?**
We will list the 3 datasets described above on BigData Exchange and await bids from storage providers. Once the auction ends, we will check SP’s bid price, reputation, geographic information, sealing speed, etc. to select the winning bidder.
**Are there any disputes open against you from your previous DataCap allocations? If any, please describe any of your honors or disputes in the field of Filecoin.**
No.
**Allocation Plan**
**Please describe your plan to use the DataCap as detailed as possible, including use case, amount, timespan, geography, storage providers, partners, etc.**
We will list the 3 datasets described above on BigData Exchange and await bids from storage providers. Once the auction ends, we will check SP’s bid price, reputation, geographic information, sealing speed, etc. to select the winning bidder.
**How many regions do you plan to store the data in?**
As we are storing different datasets with 3 replicas, we will store the data in three different regions.
**Do you plan to record your allocation decisions and execution details in public? And how to realize it?**
We are using smart contracts to record all auctions, bids, and transactions. The entire process with be transparent to the public. 
**Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?**
Yes

**Comment by IreneYoung** [comment]
Sorry @JackFsy, according to our scoring, you can't get that much datacap. I suggest you issue a large Dataset application. You can apply here: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues
