### ISSUE TITLE
Client Allocation Request for: THUNDER

### ISSUE THREAD

**Issue by rpnbxn** [filecoin-project/filecoin-plus-client-onboarding#1796]
---

# Client Allocation Questions 

## Core Information
- Name: THUNDER
- Website / Social Media: http://www.cdwdz.com/
- Region: Greater China
- DataCap Requested: 20TiB
- Addresses to be Notarized: f1xbruptksqtzjhqe2rlkjx7ampk23tdzpjwscqpy
- Notary Requested: neogeweb3

@rpnbxn Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by neogeweb3** [comment]
Hey @rpnbxn, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1.	Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2.	If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3.	In which region(s) do you intend to use the DataCap? 
4.	What is your use case for the DataCap being requested? 
5.	Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6.	How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7.	Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?

Moreover, I encourage you to take a look of my allocation [strategy ](https://github.com/filecoin-project/notary-governance/issues/11) and [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)which shows how I utilize the assessment. Thanks.

**Comment by rpnbxn** [comment]
1. IT of Thunder. From github rpnbxn.
2. Thunder. Founded in 1995, Wuxi Changde Microelectronics Co., Ltd. is a high-tech enterprise engaged in the design, research and development, production and sales of power semiconductor devices.
3. Mainly China.
4. For storing products' parameter files.
5. No.
6. 3 storage provides.
7. Yes, if need. I'll obey community's rule.

**Comment by rpnbxn** [comment]
@neogeweb3 chxiaojin@cdwdz.com

**Comment by neogeweb3** [comment]
@rpnbxn, the verification email was sent yesterday.
