### ISSUE TITLE
Client Allocation Request for: Haoseng Inductrial co.,Ltd.

### ISSUE THREAD

**Issue by Henryhaoseng** [filecoin-project/filecoin-plus-client-onboarding#1798]
---

# Client Allocation Questions 

## Core Information
- Name: Haoseng Inductrial co.,Ltd.
- Website / Social Media: http://www.haoseng.com.cn/
- Region: Greater China
- DataCap Requested: 30TiB
- Addresses to be Notarized: f1cu2yllfykl3fsnwm7cwdqe2p6o3kuutfa57voda
- Notary Requested: neogeweb3

@phvzej Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by neogeweb3** [comment]
Hey @Henryhaoseng, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1.	Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2.	If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3.	In which region(s) do you intend to use the DataCap? 
4.	What is your use case for the DataCap being requested? 
5.	Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6.	How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7.	Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?

Moreover, I encourage you to take a look of my allocation [strategy ](https://github.com/filecoin-project/notary-governance/issues/11) and [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)which shows how I utilize the assessment. Thanks.

**Comment by Henryhaoseng** [comment]
1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.)
Github: Henryhaoseng
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
Haoseng Industrial Co., Ltd. was established in Hong Kong in 1999 and set up a filiale in Shanghaiin in 2002. Haoseng is the exclusive agent of American K&S company's products in Chinese local markets. We sell fully automatic bonding machines, manual bonding machines and various spare parts in China. At the same time, we also sell various tools for semiconductor production produced by K&S, including CAPILLARY, grinding wheel scribing knife (BLADE) and semiconductor production materials - various specifications of gold wire, gold strip, aluminum wire, copper wire, platinum line etc.
3.In which region(s) do you intend to use the DataCap?
China.
4.What is your use case for the DataCap being requested?
Our data are lots of products' pictures and information documents.
5.Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
NO.
6.How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify.
3-4miners. We don't have any specific miner.
7.Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?
Of course!

**Comment by neogeweb3** [comment]
> 1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.)
>    Github: Henryhaoseng

Do you have other online identities I can verify?

Also, can you provide some proof of you are working for Haoseng Industrial co., Ltd? What would be the best email I could reach out to you, I will need a work email under the domain haoseng.com.cn, thanks.
