### ISSUE TITLE
Client Allocation Request for: BigData Exchange

### ISSUE THREAD

**Issue by JackFsy** [filecoin-project/filecoin-plus-client-onboarding#1851]
---

# Client Allocation Questions 

## Core Information
- Name: BigData Exchange
- Website / Social Media: www.bigd.exchange
- Region: Asia excl. Greater China
- DataCap Requested: 480TiB
- Addresses to be Notarized: f1cknbfzj656hmk6hqrblzs24ecv6ndg5pmxt5aka
- Notary Requested: neogeweb3

@JackFsy Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by neogeweb3** [comment]
Hey @JackFsy, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1.	Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2.	If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3.	In which region(s) do you intend to use the DataCap? 
4.	What is your use case for the DataCap being requested? 
5.	Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6.	How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7.	Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?

Moreover, I encourage you to take a look of my allocation [strategy ](https://github.com/filecoin-project/notary-governance/issues/11) and [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)which shows how I utilize the assessment. Thanks.

**Comment by JackFsy** [comment]
Hey @neogeweb3 , thanks for your response. Please see my reply below. 

**1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.)**
I am Jack Fan and I am currently in charge of product operations for BigData Exchange (https://www.bigd.exchange/). My Filecoin Slack ID is: @jack fan
**2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?**
BigData Exchange is an auction-style marketplace to connect clients with Fil+ data and storage providers with storage capacity. Headquartered and operated in Singapore, there are currently over 30 people globally in the core team.
With the current demand for Filecoin plus deals, there are several benefits that BigData Exchange brings to the Filecoin network:

- An innovative storage platform to incentivize more people to source, migrate, and store valuable public data on Filecoin
- A transparent marketplace to connect Fil+ clients and storage providers, which adds visibility to the SP selection process and prevents potential self-dealing activities
- An index of public data stored on Filecoin, which paves the way to a vibrant retrieval and service market for Fil+ deals

We came up with the concept in April, built the prototype and launched in May. We are still in the process of incorporating in Singapore and Filecoin Slack: @CB Tan is the named officer.

**3. In which region(s) do you intend to use the DataCap?**
We are storing different datasets with 3 replicas, we will store the data in three different regions.
**4. What is your use case for the DataCap being requested?**
After product launch, we have onboarded 1.5PiB dataset to the product with competitive bids from multiple storage providers. Several Fil+ clients are onboarding public data to BigData Exchange and they are currently in the midst of preparing dataset for auctions. Meanwhile, we would like to ensure there are sufficient Fil+ datasets in the auction listing to drive more awareness and adoption. We are seeing strong demand and would love to keep the momentum going. Thus, we hope you can grant us approval for 480TiB Datacap, ideally by **8th June** so that we can continue to keep up with demand. The dataset we use will be public open dataset stored in AWS S3: https://registry.opendata.aws/wpto-pds-us-wave/ (80TiB); https://registry.opendata.aws/targetepigenomics/ (30TiB); https://registry.opendata.aws/noaa-nwm-pds/ (50TiB)
We are planning to store 3 replicas for each dataset. Thus, we would like to apply for (80+30+50) x 3 = 480TiB of DataCap in this application. 
**5. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.**
The storage providers need to enable fast retrieval and the dataset should be retrievable in 18 months.
**6. How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify.**
We will list the 3 datasets described above on BigData Exchange and await bids from storage providers. Each dataset will have 3 replicas distributed to 3 storage providers. Once the auction ends, we will check SP’s bid price, reputation, geographic information, sealing speed, etc. to select the winning bidder.  
**7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?**
Yes. All transactions are transparent and we can ensure there is no self-dealing.

**Comment by neogeweb3** [comment]
As we discussed over slack and in-person meeting with your colleague CB, I will go ahead and close this allocation request. Let me know if you have any further questions. Thanks.
