### ISSUE TITLE
Client Allocation Request for: Shanghai Huiya

### ISSUE THREAD

**Issue by Huiya2** [filecoin-project/filecoin-plus-client-onboarding#1892]
---

# Client Allocation Questions 

## Core Information
- Name: Shanghai Huiya
- Website / Social Media: www.shhuiya.com
- Region: Greater China
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1dvqutfi4m53vl7wxl7xvdjk7fbcebk5hjzznxwi
- Notary Requested: neogeweb3

@Huiya2 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by neogeweb3** [comment]
Hey, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1.	Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2.	If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3.	In which region(s) do you intend to use the DataCap? 
4.	What is your use case for the DataCap being requested? 
5.	Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6.	How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7.	Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?

Moreover, I encourage you to take a look of my allocation [strategy ](https://github.com/filecoin-project/notary-governance/issues/11) and [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)which shows how I utilize the assessment. Thanks.

**Comment by Huiya2** [comment]
I'm Roger, CEO of Huiya. My Github: Huiya2
My company is Huiya. Shanghai Huiya Information Technology Co., Ltd. is a "double-software" software company recognized by the Shanghai Municipal of Economic and Informatization. My company was established in September 2007. In February 2012, my company obtained the "Huiya" and related LOGO trademark registration certificate. 
Mainly China, maybe other countries.
I want to store live videos.
NO.
4 miners.
OK, I'm agree with it.
@neogeweb3

**Comment by neogeweb3** [comment]
Can you provide some proof that you are the CEO of Huiya? What would be the best email I could reach out to you, I will need a work email under the domain shhuiya.com, thanks.

**Comment by Huiya2** [comment]
Sorry it took so long to see this,  this is my work email Roger@shhuiya.com

**Comment by neogeweb3** [comment]
Hi Roger, thanks for your email. Are you able to provide some clarity around the concerns raised in your LDN [request](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/354)? I will need these answers to process your allocation request.

**Comment by Huiya2** [comment]
f01870475
f01850141
f047666
f061666
@neogeweb3 We communicated with these SPs for application.

**Comment by neogeweb3** [comment]
Allocation was successful: https://filfox.info/en/message/bafy2bzaceauwkgkspzj2zv2y6awiiq4xqowpv64ddo2t6ucu6zb6nsiw3m7b6
