### ISSUE TITLE
Client Allocation Request for: Victor Chang Cardiac Research Institute 

### ISSUE THREAD

**Issue by DSS-AL** [filecoin-project/filecoin-plus-client-onboarding#1937]
---

# Client Allocation Questions 

## Core Information
- Name: Victor Chang Cardiac Research Institute 
- Website / Social Media: https://www.victorchang.edu.au/
- Region: Oceania
- DataCap Requested: 25TiB
- Addresses to be Notarized: f3qwluincblkdog6jovdcrv3yqqrlgxipnwv43un2iwbrofv63g6fmqogapwi3cf3fh4l3mdcrgtmfpbfphypa
- Notary Requested: MegTei

@DSS-AL Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MegTei** [comment]
HI @DSS-AL I'll run through some application triage questions with you, can you answer as best as possible, ping me if anything is unclear

DATACAP REQUEST

1. In which region(s) do you intend to use the DataCap?
2. How did you hear about the FIL+ program? Do you have a good understanding of the network and/or are involved in the web3.0 community?
3. What is your registered business name & address?
4. Provide a description of your business, the industry you work in and what you do.
5. What type/ category of data is being stored? (E.g Public data - back-up files, private encrypted files etc)
6. How much data will you onboard each week?
7. For how long do you intend to store your data with Filecoin?
8. Have you previously received DataCap? If so, please link to any previous requests/ github issues.
9. How frequently do you intend to retrieve data stored on Filecoin e.g. monthly, a couple times a year, infrequently.
MINER DETAILS
10. How many miners do you plan on using to distribute the data, providing their ID's?
11. Are any of those miners controlled by yourself / your organization and if so, what is the percentage?
12. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

**Comment by marshyonline** [comment]
Hi @MegTei, I will answer on behalf of @DSS-AL.
We, Distributed Storage Solutions(DSS) are acting as a proxy for the Victor Chang Cardiac Research Institute(VC).

1. Due to data sovereignty requirements, all data cap will be spent inside Australia
2. The VC became aware of the FiL+ Program when we approached them to offer our services in storing their data on the Filecoin Network. 
3. Victor Chang Cardiac Research Institute - 405 Liverpool St, Darlinghurst NSW 2010
4. The Victor Chang Cardiac Research Institute is an Australian non-profit medical research facility dedicated to finding cures for cardiovascular disease.
5. Private encrypted medical research data
6. Being a POC of only 5T - we expect this to be on board within a week
7. Indefinitely 
8. No
9. We expect the retrieval rate on this data to be very low - only a few times a year if any.
10. We intend to replicate this deal with 4 miners located in Australia.
11. f01746964, f01864434, f01157249 and 1 more TBC
12. Yes, 2 of these miners are controlled by us
13. Yes

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb64747dovltcphugymm3dc2aecsruzz42dsrl7huebewgmvozcqg 
#### Address 
> f3qwluincblkdog6jovdcrv3yqqrlgxipnwv43un2iwbrofv63g6fmqogapwi3cf3fh4l3mdcrgtmfpbfphypa
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb64747dovltcphugymm3dc2aecsruzz42dsrl7huebewgmvozcqg

**Comment by MegTei** [comment]
HI @DSS-AL  I have allocated DataCap to your project
Please remember the following:

1. DataCap should be used for material that is unencrypted and licensed to be distributed to the public - as this is private data we have just discussed due diligence now and I am satisfied for this POC
2. Please use your DataCap to make deals with more than one miner.
3. Use your DataCap for the public good!
Any questions, ping us on the Filecoin Project slack
