### ISSUE TITLE
Client Allocation Request for: guokai

### ISSUE THREAD

**Issue by guo-kai** [filecoin-project/filecoin-plus-client-onboarding#1965]
# Client Allocation Questions 

## Core Information
- Name: guokai
- Website / Social Media: guokai on slack
- Region: Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f1b2cs7m3dxgg2gsvkjg2yt6px34zeslcyuejurbq
- Notary Requested: neogeweb3

-------------------------

**Comment by neogeweb3** [comment]
Hey, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1.	Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2.	If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3.	In which region(s) do you intend to use the DataCap? 
4.	What is your use case for the DataCap being requested? 
5.	Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6.	How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7.	Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?

Moreover, I encourage you to take a look of my allocation [strategy ](https://github.com/filecoin-project/notary-governance/issues/11) and [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)which shows how I utilize the assessment. Thanks.

**Comment by guo-kai** [comment]
> Hey, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can.
> 
> 1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.)
    my github [https://github.com/guo-kai](url) slack@guokai
> 2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
I'm a personal developer and videographer in chain
> 3. In which region(s) do you intend to use the DataCap?
 Chain
> 4. What is your use case for the DataCap being requested?
 Save the 4k video I shot
> 5. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
no
> 6. How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify.
2 
> 7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?
yes
> Moreover, I encourage you to take a look of my allocation [strategy ](https://github.com/filecoin-project/notary-governance/issues/11) and [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)which shows how I utilize the assessment. Thanks.

**Comment by neogeweb3** [comment]
Do you have other online identities I can verify? Also, why did you apply for DataCap as an organization and delete it after? #1963

**Comment by guo-kai** [comment]
I wish to apply as an individual.

**Comment by neogeweb3** [comment]
Do you have other online identities I can verify?

**Comment by guo-kai** [comment]
![image](https://user-images.githubusercontent.com/10379742/178910252-a5acfcb6-6a70-4a26-a8f0-0e9cb91aebfc.png)
