### ISSUE TITLE
Client Allocation Request for: DIDIBOYU

### ISSUE THREAD

**Issue by wianeigniengggoe** [filecoin-project/filecoin-plus-client-onboarding#2117]
---

# Client Allocation Questions 

## Core Information
- Name: DIDIBOYU
- Website / Social Media: www.didiboyu.com
- Region: Asia (excl. Greater China)
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1kbd5gfrl7rnnfg7wzylsh2tuwcbtlik3usz244i
- Notary Requested: IreneYoung

@wianeigniengggoe Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by wianeigniengggoe** [comment]
@IreneYoung Hi plz check on this request and let me know if there is anything you need. Thx!

**Comment by IreneYoung** [comment]
Hi @wianeigniengggoe  - Thanks for your application. Please answer the following questions to let us know about you, your company, and further information about the DataCap allocation.

Basic Info
What's your name and your position in your company?

Please introduce yourself and your team briefly. How many team members do you have in your R&D or core team? Could you provide several Github accounts or email addresses of them?

For your organization, Please describe its business, its history since inception, registration country, scale, employee counts, operation regions, named executive officers, relevant projects, industry reputation, etc.

Please show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links) to show your Web3 reputation or external reputation.

Please provide your company's business registration license. If you have any presentation documents about your business, please provide them to us. And also could send me via email for privacy concerns. My contact: [irene@12ships.com](mailto:irene@12ships.com)

How long have the team core members been engaged in development?

What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?

Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization?

Where is your data stored now? Whether the data is stored on a server or a cloud service provider?

Track Record
Has your organization obtained DataCap before? if so, please answer the following sub-questions.
1.1 Please share all the links and recordings of your applications before.
1.2 How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?
1.3 What was your allocation strategy plan then and how did you execute it?

Are there any disputes open against you from your previous DataCap allocations? If any, please describe any of your honors or disputes in the field of Filecoin.

Allocation Plan
Please describe your plan to use the DataCap as detailed as possible, including use case, amount, timespan, geography, storage providers, partners, etc.

How many regions do you plan to store the data in?

How many storage providers you intend to make dealing with?

Do you plan to record your allocation decisions and execution details in public? And how to realize it?

Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?

We may further ask some questions and then give an accurate score to the application. Thank you for your cooperation!

**Comment by wianeigniengggoe** [comment]
@IreneYoung Hi! Thanks for the reply. Please refer to below and let me know if you need more information.

**Basic Info**
What's your name and your position in your company?
My name is Wayne Tang. Software developer.

Please introduce yourself and your team briefly. How many team members do you have in your R&D or core team? Could you provide several Github accounts or email addresses of them?
Our team has been dealing with IPFS/Filecoin related projects since 2020 and I am in charge of code optimization and performance improvement.
There are 6 members in our team.

For your organization, Please describe its business, its history since inception, registration country, scale, named executive officers, relevant projects, industry reputation, etc.
Located in South Korea, DIDIBOYU is dedicated to bringing sparkle into everyday life. We present jewelry with a message of respect and beauty to all possessors in the world We want to share the emotions contained within. DIDIBOYU's jewelry maximizes the beauty of the unique characteristics of metal. It is harmonized with various raw stones selected and imported by the designer and non-metallic materials such as glass, acrylic, and rubber. We want to create special jewelry that has never been seen anywhere else. 

Please show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links) to show your Web3 reputation or external reputation.
Instagram: https://www.instagram.com/didiboyu_/ 

Please provide your company's business registration license. If you have any presentation documents about your business, please provide them to us. And also could send me via email for privacy concerns. My contact: [irene@12ships.com](mailto:irene@12ships.com)
Business registration license: will send an email.

How long have the team core members been engaged in development?
2 years.

What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?
Mostly pictures and video files including commodity, advertisement (jpg).
10 TiB will be needed.
Sample data: will send an email.

Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization?
From our company’s public data.
Files will be stored on Filecoin network.

Where is your data stored now? Whether the data is stored on a server or a cloud service provider?
Company’s server.

**Track Record**
Has your organization obtained DataCap before? if so, please answer the following sub-questions.
2.1 Please share all the links and recordings of your applications before.
2.2 How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?
2.3 What was your allocation strategy plan then and how did you execute it?
No. It’s our first time working with Filecoin.

Are there any disputes open against you from your previous DataCap allocations? Please describe any of your honors or disputes in the field of Filecoin.
No.

**Allocation Plan**
Please describe your plan to use the DataCap as detailed as possible, including use case, amount, timespan, geography, storage providers, partners, etc.
Geography: Asia.
2 miners.
We currently store an amount of 10 TB.

How many regions do you plan to store the data in?
Only Asia.

How many storage providers you intend to make dealing with?
3 SPs.

Do you plan to record your allocation decisions and execution details in public? And how to realize it?
Yes. We will make our distribution records public in GitHub.

Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?
Absolutely.

We may further ask some questions and then give an accurate score to the application. Thank you for your cooperation!

**Comment by IreneYoung** [comment]
@wianeigniengggoe I have not received your company's business registration license, plz answer question: 1. When is your company registered? 2.How many employees in total?
