### ISSUE TITLE
Client Allocation Request for: 119REO

### ISSUE THREAD

**Issue by xieyuanyuanhahaha** [filecoin-project/filecoin-plus-client-onboarding#2148]
---

# Client Allocation Questions 

## Core Information
- Name: 119REO
- Website / Social Media: https://www.119reo.com/
- Region: Asia (excl. Greater China)
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1v6cvujoi6i7ooxgjzo5qbzj6sk2bfqihwadt7yq
- Notary Requested: IreneYoung

@xieyuanyuanhahaha Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IreneYoung** [comment]
Hi @xieyuanyuanhahaha  , thanks for your application. Please answer the following questions to let us know about you, your company, and further information about the DataCap allocation.

Basic Info
What's your name and your position in your company?

Please introduce yourself and your team briefly. How many team members do you have in your R&D or core team? Could you provide several Github accounts or email addresses of them?

For your organization, Please describe its business, its history since inception, registration country, scale, employee counts, operation regions, named executive officers, relevant projects, industry reputation, etc.

Please show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links) to show your Web3 reputation or external reputation.

Please provide your company's business registration license. If you have any presentation documents about your business, please provide them to us. And also could send me via email for privacy concerns. My contact: [irene@12ships.com](mailto:irene@12ships.com)

How long have the team core members been engaged in development?

What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?

Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization?

Where is your data stored now? Whether the data is stored on a server or a cloud service provider?

Track Record
Has your organization obtained DataCap before? if so, please answer the following sub-questions.
1.1 Please share all the links and recordings of your applications before.
1.2 How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?
1.3 What was your allocation strategy plan then and how did you execute it?

Are there any disputes open against you from your previous DataCap allocations? If any, please describe any of your honors or disputes in the field of Filecoin.

Allocation Plan
Please describe your plan to use the DataCap as detailed as possible, including use case, amount, timespan, geography, storage providers, partners, etc.

How many regions do you plan to store the data in?

How many storage providers you intend to make dealing with?

Do you plan to record your allocation decisions and execution details in public? And how to realize it?

Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?

We may further ask some questions and then give an accurate score to the application. Thank you for your cooperation!

**Comment by xieyuanyuanhahaha** [comment]
@IreneYoung Hi! Thanks for the reply. Please refer to below and let me know if you need more information.

**Basic Info**
What's your name and your position in your company?
Yasmine Xie. Manager.

Please introduce yourself and your team briefly. How many team members do you have in your R&D or core team? Could you provide several Github accounts or email addresses of them?
Our team has been upcycling life-saving fire safety equipment into products that save each other.
There are 10 members in our team. We produce and sell bags by upcycling used fire protection clothing, and use the proceeds to solve the problem of firefighters, creating a culture where firefighters are remembered. 

For your organization, Please describe its business, its history since inception, registration country, scale, named executive officers, relevant projects, industry reputation, etc.
Established in 2016 in Republic of Korea, 119REO is a social enterprise that sells products made by recycling expired fire suits and donates a portion of the proceeds to cancer-fighting firefighters. By linking the upcycling process with local self-help centers, we turn local waste into local resources. These resources are then made into new products in specialized factories. 50% of the sales proceeds are donated to firefighting organizations to help ensure the rights of firefighters. So far, we have donated a total of 80 million won to 13 cancer-fighting firefighters. 

Please show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links) to show your Web3 reputation or external reputation.
YouTube: https://www.youtube.com/c/119REO
Instagram: https://www.instagram.com/119reo/ 
Facebook: https://www.facebook.com/119reo/
Naver: https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=0&ie=utf8&query=119reo     

Please provide your company's business registration license. If you have any presentation documents about your business, please provide them to us. And also could send me via email for privacy concerns. My contact: [irene@12ships.com](mailto:irene@12ships.com)
Will send business registration license by email.

How long have the team core members been engaged in development?
5 years.

What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?
Mainly product pictures, promotional videos, customer’s data and media data. 10 TiB will be needed.
Sample data will be sent by email.

Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization?
From our company’s public data.

Where is your data stored now? Whether the data is stored on a server or a cloud service provider?
Company’s server.

**Track Record**
Has your organization obtained DataCap before? if so, please answer the following sub-questions.
2.1 Please share all the links and recordings of your applications before.
2.2 How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?
2.3 What was your allocation strategy plan then and how did you execute it?
No. It’s our first time working with Filecoin.

Are there any disputes open against you from your previous DataCap allocations? Please describe any of your honors or disputes in the field of Filecoin.
No.

**Allocation Plan**
Please describe your plan to use the DataCap as detailed as possible, including use case, amount, timespan, geography, storage providers, partners, etc.
Geographies: Asia.
3 miners with good reputation.
We currently store an amount of 10TB.

How many regions do you plan to store the data in?
Asia.

How many storage providers you intend to make dealing with?
3-4 SPs.

Do you plan to record your allocation decisions and execution details in public? And how to realize it?
Yes. We will make our distribution records public in GitHub.

Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?
Yes.

We may further ask some questions and then give an accurate score to the application. Thank you for your cooperation!

**Comment by IreneYoung** [comment]
@xieyuanyuanhahaha I have not received your company's business registration license. And how many employees in your company?

**Comment by IreneYoung** [comment]
Hi @xieyuanyuanhahaha, if you still need datacap, plz answer the additional question above.

**Comment by raghavrmadya** [comment]
No response. @xieyuanyuanhahaha please open a new application.
