### ISSUE TITLE
Client Allocation Request for: 北京托比咨询有限责任公司

### ISSUE THREAD

**Issue by jacky-zhangxueyou** [filecoin-project/filecoin-plus-client-onboarding#224]
---

# Client Allocation Questions 

## Core Information
- Name: 北京托比咨询有限责任公司
- Website / Social Media: http://www.2b.cn/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1g7ynmax7azy6kbeudidtcxzaljshauupl25itcq
- Notary Requested: NeoGe-IPFSMain

**Comment by neogeweb3** [comment]
Hey @jacky-zhangxueyou, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1.	Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2.	If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3.	In which region(s) do you intend to use the DataCap? 
4.	What is your use case for the DataCap being requested? 
5.	Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6.	How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7.	Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

Moreover, I encourage you to take a look of our allocation [strategy ](https://github.com/filecoin-project/notary-governance/issues/11) and [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)which shows how we utilize the assessment.

**Comment by jacky-zhangxueyou** [comment]
1.Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.)
This is Beijing Toby Consulting Co., Ltd found in 2014,We mainly provide Internet e-commerce services for corporate customers.

Official website：http://www.2b.cn/


2.If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
Our organization'name is Beijing Toby Consulting Co., Ltd,Registered In Beijing of China,started in 2014 and corporate representative is Ning-bo liu.


3.In which region(s) do you intend to use the DataCap?
China


4.What is your use case for the DataCap being requested?
We want to be able to help enterprise customers store some data backups (including video and pictures) more cheaply.


5.Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
We will transfer data with miners through offline deal.


6.How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify.
We plan 5-10 miners. We have no specific miner yet.


7.Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?
Yes. info including: deal_id, miner_id, address, dataCID, date etc.

**Comment by neogeweb3** [comment]
Hey @jacky-zhangxueyou, since my allocation strategy is to build trust progressively, I would allocate 100 GiB to you for the first time. Feel free to request more DataCap when you use up the allocation.

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4cnbja5pavk7c5ujpzk3y5ik5sjkdsgcriyufgqc5qs3nlxam54 
#### Address 
> f1g7ynmax7azy6kbeudidtcxzaljshauupl25itcq
#### Datacap Allocated
> 100GiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4cnbja5pavk7c5ujpzk3y5ik5sjkdsgcriyufgqc5qs3nlxam54
