### ISSUE TITLE
Client Allocation Request for: 上海赢科信息技术有限公司

### ISSUE THREAD

**Issue by dong199503** [filecoin-project/filecoin-plus-client-onboarding#231]
---

# Client Allocation Questions 

## Core Information
- Name: 上海赢科信息技术有限公司
- Website / Social Media: yingketech.com
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1fayarvpqi73lbbvxtgck53w5j346chk4kwz2jdq
- Notary Requested: NeoGe-IPFSMain

**Comment by neogeweb3** [comment]
Hey @dong199503, thanks for the request. Sorry for the delay, somehow this request fell off the filter. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1.	Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2.	If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3.	In which region(s) do you intend to use the DataCap? 
4.	What is your use case for the DataCap being requested? 
5.	Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6.	How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7.	Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

Moreover, I encourage you to take a look of our allocation [strategy ](https://github.com/filecoin-project/notary-governance/issues/11) and [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)which shows how we utilize the assessment. Thanks!

**Comment by neogeweb3** [comment]
@dong199503, I will close this request, but feel free to reopen or start a new allocation request when you are ready.
