### ISSUE TITLE
Client Allocation Request for: kims-korea

### ISSUE THREAD

**Issue by domms9911** [filecoin-project/filecoin-plus-client-onboarding#2315]
---

# Client Allocation Questions 

## Core Information
- Name: kims-korea
- Website / Social Media: www.kims-korea.co.kr
- Region: Asia (excl. Greater China)
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1isu6pa3pvbymukbloyger5lcy5gcifugiw5abzq
- Notary Requested: MasaakiNawatani

@domms9911 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MasaakiNawatani** [comment]
Hello @domms9911 

Thanks for reaching out! 

Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

```
Please answer here.
```

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 

```
Please answer here.
```

**Allocation Strategy
Do you intend to store your data in a single geography or many?

```
Please answer here.
```

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

```
Please answer here.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
Please answer here.
```

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

```
Please answer here.
```

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

```
Please answer here.
```

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

```
Please answer here.
```

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

```
Please answer here.
```

Are there any disputes open against you from your previous DataCap allocations?

```
Please answer here.
```

Have you ever previously violated:

- Your own attested allocation / audit plan?
- Been found to be in violation of the Principles of Filecoin Plus?

```
Please answer here.
```

**Comment by domms9911** [comment]
조직, 프로젝트 또는 사용 사례의 특성을 설명하십시오. 조직의 경우 조직과의 관계, 조직 규모, 설립 이후 경과 시간을 포함해 주십시오. 프로젝트 및 기타 사용 사례의 경우 관련 웹 페이지 또는 Github에 링크하십시오. 상황에 맞는 정보를 제공하기 위해 관련 세부 정보를 최대한 포함하십시오(외부 링크 포함). 귀하의 비즈니스에 대한 프레젠테이션 문서가 있으면 저에게 제공하십시오.

Our company was established in 2006 and has been managing computer service and CCTV in parallel. The number of people is 12, including the company's representative, and we store and manage the images of rivers, mountains, agricultural waterways, and rivers.

This is a sample material and is open for anyone to see.


이전에 DataCap에 대한 승인을 받은 적이 있습니까? 그렇다면 마지막 할당 결정에 대한 세부 정보를 공유할 수 있습니까?

There is not.

**할당 전략
데이터를 단일 지역 또는 여러 지역에 저장할 계획입니까?

We will store our data in Asia as far as possible.

스토리지 거래에 지정할 수 있는 기능(예: 빠른 검색)을 알고 있으며 사용할 의향이 있습니까?

For the time being, we plan to use Filecoin official search and develop an app for it.

조직(및 위임된 구성원)이 DataCap을 할당하도록 하기 위해 DataCap을 어떻게 보호할 계획입니까?


All data will be stored in the company's own storage and will be stored using a storage provider as a backup.

DataCap의 상당 부분을 단일 광부에 할당할 계획입니까, 아니면 여러 광부에 분산할 계획입니까?


I want to spread it out as much as possible, but I am currently planning to save it to 3 miners.

애플리케이션 개발자의 경우 사용자를 대신하여 클라이언트 역할을 하시겠습니까? 아니면 사용자를 대신하여 공증인으로 지원하시겠습니까? 그렇다면 승인을 원하는 사용자당 DataCap은 얼마입니까?

Apply as a client.

DataCap을 사용하여 현지 규정과 수신자 광부의 서비스 약관을 준수하는 데이터만 저장하는 데 동의하십니까?

YES.

**실적 기록
이전에 할당할 DataCap을 받은 적이 있습니까? 그렇다면 이전에 내린 결정에 연결하십시오.

NO.

이전 DataCap 할당에서 귀하에게 불리한 분쟁이 있습니까?

NO.

이전에 위반한 적이 있습니까?

자신의 증명된 할당/감사 계획?
Filecoin Plus의 원칙을 위반한 것으로 밝혀졌습니까?
NO.


Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

Our company was established in 2006 and has been managing computer service and CCTV in parallel. The number of people is 12, including the company's representative, and we store and manage the images of rivers, mountains, agricultural waterways, and rivers.

This is a sample material and is open for anyone to see.

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)?

There is not.


**Allocation Strategy
Do you intend to store your data in a single geography or many?

We will store our data in Asia as far as possible.

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

For the time being, we plan to use Filecoin official search and develop an app for it.

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

All data will be stored in the company's own storage and will be stored using a storage provider as a backup.

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

I want to spread it out as much as possible, but I am currently planning to save it to 3 miners.

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

Apply as a client.

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

yes.

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

no.

Are there any disputes open against you from your previous DataCap allocations?

no.

Have you ever previously violated:

Your own attested allocation / audit plan?
Been found to be in violation of the Principles of Filecoin Plus?

no.

**Comment by MasaakiNawatani** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmimr6tu4zklfxulbqsbc2vzam3mkxbisfzod2yrjmxymgaycmfk 
#### Address 
> f1isu6pa3pvbymukbloyger5lcy5gcifugiw5abzq
#### Datacap Allocated
> 5.00TiB
#### Signer Address
> f1ciu27vn3r7htmanzvwrm6ksx6y774gqsz3cot3i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmimr6tu4zklfxulbqsbc2vzam3mkxbisfzod2yrjmxymgaycmfk
