### ISSUE TITLE
Client Allocation Request for: Protocol Labs

### ISSUE THREAD

**Issue by mikeal** [filecoin-project/filecoin-plus-client-onboarding#237]
---

# Client Allocation Questions 

## Core Information
- Name: Protocol Labs
- Website / Social Media: nft.storage
- Region: North America
- DataCap Requested: 2TiB
- Addresses to be Notarized: f3qh7m6ul2n6pbko6bovtthogzv4qdu4bh6hlmbjw55khic6wegintl5ma55fwbxjzh5g4hweyj3n5j3lbd3ra
- Notary Requested: andrewxhill

**Comment by andrewxhill** [comment]
Hey @mikeal, thanks for the request. To help with the verification process, could you please provide as thorough of answers as you can to the following questions.

1. Can you introduce yourself? Where can I find you online? Examples include Github, Twitter, LinkedIn, WeChat, etc., and more than one is encouraged.
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3. In which region(s) do you intend to use the DataCap?
4. What is your use case for the DataCap being requested?
5. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
6. How many miners do you plan on allocating the DataCap? Please specify if you have a specific miner(s) you would like to allocate the DataCap.
7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing? If so, how will you plan to report it?
8. Will your organization be responsible for allocating the full DataCap? Examples where this might not be the case, include app builders where the application end-users may have access to storage backed by the DataCap. Please read our full proposal for details on this approach. Unfortunately, our proposed multisig enabled DataCap provider is not ready today, but when it is, we will provider further documentation.
9. If your org has received DataCap previously, could you share details on how this project differs or is an extension of those others. 

Thanks,

Andrew

**Comment by mikeal** [comment]
> Can you introduce yourself? Where can I find you online? Examples include Github, Twitter, LinkedIn, WeChat, etc., and more than one is encouraged.

Hiya, I’m Mikeal Rogers. I’m @mikeal on GitHub and Twitter. GitHub has roughly a decade of my work history in it so I can assure you I’m a real person ;)

> If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?

Protocol Labs, created and lead by Juan Benet :)

> In which region(s) do you intend to use the DataCap?

Our infra should be located in the US for now. I can check back in if that changes and we end up having infra in other jurisdictions.

> What is your use case for the DataCap being requested?

We’re creating a service for storing NFT data.

> Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.

Maybe? This is still being figured out and may actually change as we iterate on the product.

> How many miners do you plan on allocating the DataCap? Please specify if you have a specific miner(s) you would like to allocate the DataCap.

This is also something that may change as we iterate. Would you like me to provide you an expected range we’re considering?

> Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing? If so, how will you plan to report it?

We want to provide as much useful information as possible to this program, so yes. We’ll provide information however you’d like us to report it to maximize its usefulness :)

> Will your organization be responsible for allocating the full DataCap? Examples where this might not be the case, include app builders where the application end-users may have access to storage backed by the DataCap. Please read our full proposal for details on this approach. Unfortunately, our proposed multisig enabled DataCap provider is not ready today, but when it is, we will provider further documentation.

For this product, we’ll be sitting in-between users and Filecoin so we’ll be responsible.

> If your org has received DataCap previously, could you share details on how this project differs or is an extension of those others.

I’m not sure what other DataCap’s PL may have already received, but this is a new product specifically targeted at NFT’s and will be operated fairly independent from any other project that may have received DataCap.

**Comment by andrewxhill** [comment]
> Would you like me to provide you an expected range we’re considering?

Yep, any indication of you are thinking about using the network is helpful here.

> We’ll provide information however you’d like us to report it to maximize its usefulness :)

Cool! Nothing specific has been defined from the Notary side here. As an example, @jnthnvctr is using another datacap and creating a log of all deals on GitHub https://github.com/filecoin-project/notary-governance#recordings it could be a good model of not too onerous.

**Comment by andrewxhill** [comment]
ping @mikeal on first bullet on allocation plan

**Comment by mikeal** [comment]
> > 6. How many miners do you plan on allocating the DataCap? Please specify if you have a specific miner(s) you would like to allocate the DataCap.
>  Would you like me to provide you an expected range we’re considering?
Yep, any indication of you are thinking about using the network is helpful here.

We are almost certainly going to limit our storage selection to the MinerX fellows. Beyond that it is is too early to tell how many miners we will end up using, as we would need to balance the desire to store with as many miners as we can against the currently elevated deal costs.


> > 7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing? If so, how will you plan to report it?
> We want to provide as much useful information as possible to this program, so yes. We’ll provide information however you’d like us to report it to maximize its usefulness 🙂
Cool! Nothing specific has been defined from the Notary side here.

Right, we are certainly going to have some sort of programmatic access to this information, but are ourselves in the process of designing and implementing the underlying infrastructure.

**Comment by andrewxhill** [comment]
Perfect, thanks for those. We'll get your request signed by tomorrow.

**Comment by andrewxhill** [comment]
You're all set! 

https://filfox.info/en/message/bafy2bzaceajl4yynhbjzig35afpp4po6vyetju3g2maesird6p66ginpyjkau

you can verify on https://verify.glif.io/ with the "check" form.
