### ISSUE TITLE
Client Allocation Request for: HIMO

### ISSUE THREAD

**Issue by qiufuyang** [filecoin-project/filecoin-plus-client-onboarding#2380]
---

# Client Allocation Questions 

## Core Information
- Name: HIMO
- Website / Social Media:  http://www.haimati.cn/#/
- Region: Greater China Region
- DataCap Requested: 5TiB
- Addresses to be Notarized: f152laimpuls5cxt7qjqn7ses5e5k5bpr4yd5h5oy
- Notary Requested: steven004

@qiufuyang Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by qiufuyang** [comment]
@steven004 Hi Steven, we have run out of the datacap you allocated last time #2123. Thanks!

**Comment by steven004** [comment]
Hey @qiufuyang , would you please provide the deal list of #2123 ? 
I need to go through a validation process before moving forward.

**Comment by qiufuyang** [comment]
@steven004 
![image](https://user-images.githubusercontent.com/108446117/186860633-1a5cd4a1-7c9f-463a-a617-696c871dca30.png)

**Comment by steven004** [comment]
@qiufuyang you are not providing the deal list, but the provider list. 
And, most of the data is stored in one provider's facility. That is not recommended way to do it. It is required to save into stores provided by more than 3 storage providers, no more than 30% for each one.

**Comment by steven004** [comment]
Hey @qiufuyang , Thanks. 
We will go through a validation process of the deals. Please share me your wechat ID, so that we could talk more there. 
Before that, I would request you share me HIMO's business license for future allocation. 

For privacy perspective, you could provide me private information via slack (@Steven), or just send me an email. Thanks.
