### ISSUE TITLE
Client Allocation Request for: renderhelp

### ISSUE THREAD

**Issue by Cats-On-Mars** [filecoin-project/filecoin-plus-client-onboarding#2389]
---

# Client Allocation Questions 

## Core Information
- Name: renderhelp
- Website / Social Media: http://www.renderhelp.com
- Region: Greater China Region
- DataCap Requested: 3TiB
- Addresses to be Notarized: f17tfc4dkjfohvwwzlwnf5xuhqascym27puurrxea
- Notary Requested: neogeweb3

@Cats-On-Mars Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Alex11801** [comment]
@Cats-On-Mars Hi! Can you introduce your institution and project a little bit? Can't tell how you can apply the dataset from your website.

**Comment by neogeweb3** [comment]
Hey, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1.	Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2.	If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3.	In which region(s) do you intend to use the DataCap? 
4.	What is your use case for the DataCap being requested? 
5.	Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6.	How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7.	Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?

Moreover, I encourage you to take a look of my allocation [strategy ](https://github.com/filecoin-project/notary-governance/issues/11) and [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)which shows how I utilize the assessment. Thanks.

**Comment by Cats-On-Mars** [comment]
Hello, I'm so glad to receive your raply. 
1. I'm a member representing the company Shanghai IThelp Network Technology Co.
    My Wechat: qtum_rose
2. Shanghai IThelp Network Technology Co. is dedicated to integrating existing resources for users, from basic system 
maintenance, system integration, rendering number crunching to development advancement, we have our own unique and perfect solutions.
   IThelp Render Farm(http://www.renderhelp.com/index.html) is a platform with commercial cluster rendering capabilities, capable of developing specialized rendering solutions and writing special rendering control scripts according to the multiple rendering needs of different customers.
   Registration country: China
   Time since inception: 2004-02-16
   Named officers: Du Haineng
3. I intend to use the DataCap in China, USA and Vietnam etc.
4. I will use datacap to store the rendered data
![WechatIMG21](https://user-images.githubusercontent.com/35727769/188325311-4321e6ff-ee94-4a1d-b5cf-f976d17cfff8.png)
5. I won't.
6. I will allocate to as many miners as possible. I have the intention to allocate to specific miners, but it is not confirmed yet, which depends on how well the cooperation goes afterwards.
7. Yes, I can provide execution details if necessary.

**Comment by Cats-On-Mars** [comment]
@neogeweb3 Hello, I have submitted the detailed information, Please let me know as soon as you take the review. Thanks!

**Comment by neogeweb3** [comment]
Hey @Cats-On-Mars, thanks for waiting.  Can you provide some proof that you are working for Shanghai IThelp Network Technology Co..? What is the best email I could reach out to you, I will need a work email under the domain http://www.renderhelp.com/

**Comment by Cats-On-Mars** [comment]
Sure. This is my email address: shh@ithelp.cn

**Comment by neogeweb3** [comment]
Do you own the domain ithelp.cn as well? The ithelp.cn says "The website has not obtained an ICP filing according to the law of the Ministry of Industry and Information Technology of the People's Republic of China." Is there another way I could verify your identity?
