### ISSUE TITLE
Client Allocation Request for: Dekun cloud data technology

### ISSUE THREAD

**Issue by taskerone** [filecoin-project/filecoin-plus-client-onboarding#2398]
# Client Allocation Questions 

## Core Information
- Name: Dekun cloud data tecnology 
- Website / Social Media: https://dekun.decoo.io/
- Region:  Greater China 
- DataCap Requested: 450 TiB
- Addresses to be Notarized: f1n6lyl2qcxnjn2aoiinmrux6rnumxnzdyoslcpmi
- Notary Requested: neogeweb3

-------------------------

**Comment by neogeweb3** [comment]
Hey, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1.	Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2.	If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3.	In which region(s) do you intend to use the DataCap? 
4.	What is your use case for the DataCap being requested? 
5.	Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6.	How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7.	Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?

Moreover, I encourage you to take a look of my allocation [strategy ](https://github.com/filecoin-project/notary-governance/issues/11) and [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)which shows how I utilize the assessment. Thanks.

**Comment by neogeweb3** [comment]
Also, could you resubmit your application through https://plus.fil.org/, as I cannot see your application in the app. Thanks.

**Comment by taskerone** [comment]
Hi there
It's my honor to answer the questions that you need to know

1.Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.)
Dekun Cloud Data Technology is a company focusing on web3.0 distributed storage. We are constantly exploring and expanding distributed and decentralized storage technology's development potential and application boundaries.
Our project, Dekun Cloud, is a cloud storage service that creates professional cloud storage products for large-scale commercial scenarios and provides a new option for meeting the storage needs of enterprises and individuals.
You can find us at https://twitter.com/D_TigerResearch and searching dekunshukuang from our public account on Wechat 

2.If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
Dekun Cloud Data Technology Co., Ltd., limited liability and a private company, China, since its establishment in September 2020 (two years).

3.In which region(s) do you intend to use the DataCap?
great china

4.What is your use case for the DataCap being requested?
general, blockchain data, storage for the company and individual users

5.Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
We don't know what are the advanced features when utilizing a DataCap in your storage deal. Could you please give us some examples?

6.How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify.
Actually, we chose storage suppliers depending on the different conditions. There are two options we are going to consider, one is the degree of reputation for storage providers and their ability of stabilization, which could ensure they will help us to store data securely and stably. Another is that the provided prices offered by the miners are relatively within our acceptable range.

7.Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?
 We agree that

Then, there is a  problem we met. Should we upload our information on  https://plus.fil.org/ or https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/896 or both? Cuz we find they have the same questions.

**Comment by neogeweb3** [comment]
I cannot open the following link: https://dekun.decoo.io/. Could you double-check for me? 

Some storage providers offer advanced features like fast retrieval to clients with or without additional costs. It would be something you could discuss with storage providers.

https://plus.fil.org/ is where you should submit your application. The other link you posted is for LDN.

**Comment by taskerone** [comment]
Hi there,
Since our server is not located in mainland China, you may need a VPN or wait longer. At the same time, we are rewriting the code of the project and looking for a mainland server for it, we will have a new access address in two or three weeks: https://dekun.baitech-ipfs.net/

Of course, if storage providers support these advanced features like fast retrieval, we would like to use them.

We submitted my application on https://plus.fil.org/,please check it.

**Comment by taskerone** [comment]
@neogeweb3 Hi there, 
we are so sorry that we submitted the request incorrectly, but now we resubmit the request and you can see it from https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/2480
