### ISSUE TITLE
Client Allocation Request for: eco village

### ISSUE THREAD

**Issue by diskplus77** [filecoin-project/filecoin-plus-client-onboarding#2437]
---

# Client Allocation Questions 

## Core Information
- Name: eco village
- Website / Social Media: https://upovill.cng.go.kr/html/main/
- Region: Asia (excl. Greater China)
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1x3w37bndhb2eq7b6sfqz36gfycwv7f4z4t2yjhi
- Notary Requested: MasaakiNawatani

@diskplus77 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MasaakiNawatani** [comment]
Hello @diskplus77 

Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

```
Please answer here.
```

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 

```
Please answer here.
```

**Allocation Strategy
Do you intend to store your data in a single geography or many?

```
Please answer here.
```

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

```
Please answer here.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
Please answer here.
```

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

```
Please answer here.
```

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

```
Please answer here.
```

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

```
Please answer here.
```

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

```
Please answer here.
```

Are there any disputes open against you from your previous DataCap allocations?

```
Please answer here.
```

Have you ever previously violated:

- Your own attested allocation / audit plan?
- Been found to be in violation of the Principles of Filecoin Plus?

```
Please answer here.
```

**Comment by diskplus77** [comment]
> Hello @diskplus77
> 
> Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!
> 
> Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.
> 
> ```
>Established in 2011, the company is playing a publicity role for nature conservation. Upo Wetland is a company for management and subtotal in order to preserve and maintain a variety of creatures in their natural state.
https://upovill.cng.go.kr/img/sub/01/img0101_03.jpg
https://upovill.cng.go.kr/servlet/BoardImagePrint?gcode=1007&name=DSC_51311.JPG
https://upovill.cng.go.kr/servlet/BoardImagePrint?gcode=1007&name=DSC_4451.JPG
https://upovill.cng.go.kr/servlet/BoardImagePrint?gcode=1007&name=DSC_4554.JPG
https://upovill.cng.go.kr/servlet/BoardImagePrint?gcode=1007&name=DSC_4347.JPG
https://upovill.cng.go.kr/servlet/BoardImagePrint?gcode=1007&name=DSC_3560.JPG
[멸종위기및보호야생동식물.pdf](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/9502526/default.pdf)

> ```
> 
> Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)?
> 
> ```
> There is not.
> ```
> 
> **Allocation Strategy Do you intend to store your data in a single geography or many?
> 
> ```
> Asia or Korea
> ```
> 
> Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?
> 
> ```
> I know this problem.
If your storage provider has a quick search feature, use it.
> ```
> 
> How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
> 
> ```
> We keep the original files on an external hard drive. I want to make a backup through a storage provider.
> ```
> 
> Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?
> 
> ```
> As many as possible (at least 2 people)
> ```
> 
> For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?
> 
> ```
> Not applicable
> ```
> 
> Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?
> 
> ```
> Yes.
> ```
> 
> **Track Record Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.
> 
> ```
> NO.
> ```
> 
> Are there any disputes open against you from your previous DataCap allocations?
> 
> ```
> NO
> ```
> 
> Have you ever previously violated:
> 
> * Your own attested allocation / audit plan?
> * Been found to be in violation of the Principles of Filecoin Plus?
> 
> ```
> NO
> ```

**Comment by MasaakiNawatani** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceax3vky2jjgi6imtohhk5apxz2absj2xfg7vwt6dv633giy46ybm4 
#### Address 
> f1x3w37bndhb2eq7b6sfqz36gfycwv7f4z4t2yjhi
#### Datacap Allocated
> 10.00TiB
#### Signer Address
> f1ciu27vn3r7htmanzvwrm6ksx6y774gqsz3cot3i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceax3vky2jjgi6imtohhk5apxz2absj2xfg7vwt6dv633giy46ybm4
