### ISSUE TITLE
Client Allocation Request for: natural environment

### ISSUE THREAD

**Issue by bicts** [filecoin-project/filecoin-plus-client-onboarding#2438]
---

# Client Allocation Questions 

## Core Information
- Name: natural environment
- Website / Social Media: https://www.gyeongnam.go.kr/forestrecreation/index.gyeong
- Region: Asia (excl. Greater China)
- DataCap Requested: 13TiB
- Addresses to be Notarized: f1zaiyu54rlfp2e7aktrvuzicvs65ewdylstmpoqa
- Notary Requested: IreneYoung

@bicts Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IreneYoung** [comment]
Hi @bicts  - Thanks for your application. Please answer the following questions to let us know about you, your company, and further information about the DataCap allocation.

Basic Info
What's your name and your position in your company?

Please introduce yourself and your team briefly. How many team members do you have in your R&D or core team? Could you provide several Github accounts or email addresses of them?

For your organization, Please describe its business, its history since inception, registration country, scale, employee counts, operation regions, named executive officers, relevant projects, industry reputation, etc.

Please show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links) to show your Web3 reputation or external reputation.

Please provide your company's business registration license. If you have any presentation documents about your business, please provide them to us. And also could send me via email for privacy concerns. My contact: [irene@12ships.com](mailto:irene@12ships.com)

How long have the team core members been engaged in development?

What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?

Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization?

Where is your data stored now? Whether the data is stored on a server or a cloud service provider?

Track Record
Has your organization obtained DataCap before? if so, please answer the following sub-questions.
1.1 Please share all the links and recordings of your applications before.
1.2 How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?
1.3 What was your allocation strategy plan then and how did you execute it?

Are there any disputes open against you from your previous DataCap allocations? If any, please describe any of your honors or disputes in the field of Filecoin.

Allocation Plan
Please describe your plan to use the DataCap as detailed as possible, including use case, amount, timespan, geography, storage providers, partners, etc.

How many regions do you plan to store the data in?

How many storage providers you intend to make dealing with?

Do you plan to record your allocation decisions and execution details in public? And how to realize it?

Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?

We may further ask some questions and then give an accurate score to the application. Thank you for your cooperation!

**Comment by bicts** [comment]
Basic Info
What's your name and your position in your company?

My position is the manager's name, Kim Jeong-ho.

Please introduce yourself and your team briefly. How many team members do you have in your R&D or core team? Could you provide several Github accounts or email addresses of them?

The core staff is 4 people. It's not huge, but everyone is working hard. Email is hahsoo0204@gmail.com.

For your organization, Please describe its business, its history since inception, registration country, scale, employee counts, operation regions, named executive officers, relevant projects, industry reputation, etc.

Established in 2004, the company is a mountain, tree, and nature management company. It monitors wildfires or landslides in real time and provides information to promote and manage human casualties and nature conservation. The total size is 13 people, and although it is not very large, we have a deep sense of mission.

Please show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links) to show your Web3 reputation or external reputation.

https://www.gyeongnam.go.kr/forestrecreation/index.gyeong
https://www.gyeongnam.go.kr/upload_data/board_data/BBS_0000596/160513659789308.jpg
https://www.gyeongnam.go.kr/upload_data/board_data/BBS_0000633/164118401415680.png
https://www.gyeongnam.go.kr/upload_data/board_data/BBS_0000596/160463724086928.jpg
https://www.gyeongnam.go.kr/upload_data/board_data/BBS_0000596/161102181227816.png
https://www.gyeongnam.go.kr/upload_data/board_data/BBS_0000596/161068519161782.png

Please provide your company's business registration license. If you have any presentation documents about your business, please provide them to us. And also could send me via email for privacy concerns. My contact: irene@12ships.com

We will send it to you by email.

How long have the team core members been engaged in development?

About 3 years.

What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?

Mountains, trees, rivers, nature conservation photography and video production.
Nature conservation promotional video, about 30 TiB is required.

https://www.gyeongnam.go.kr/upload_data/board_data/BBS_0000633/165216695445590.jpg
https://www.gyeongnam.go.kr/upload_data/board_data/BBS_0000596/160497073845422.jpg
https://www.gyeongnam.go.kr/upload_data/board_data/BBS_0000596/160497073845777.jpg
https://www.gyeongnam.go.kr/upload_data/board_data/BBS_0000596/163720125070127.jpg
https://www.gyeongnam.go.kr/upload_data/board_data/BBS_0000596/163720125070980.jpg
https://www.gyeongnam.go.kr/forestrecreation/board/download.gyeong?boardId=BBS_0000633&menuCd=DOM_000003905001000000&paging=ok&startPage=6&dataSid=41518020&command=update&fileSid=5214531

Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization?

stored on an external hard drive.
All data will be backed up using datacap.

All materials are promotional materials and are publicly available materials.
It is a nature conservation promotional material.
Production is a company.

Where is your data stored now? Whether the data is stored on a server or a cloud service provider?



Track Record
Has your organization obtained DataCap before? if so, please answer the following sub-questions.
1.1 Please share all the links and recordings of your applications before.
1.2 How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?
1.3 What was your allocation strategy plan then and how did you execute it?

First time.


Are there any disputes open against you from your previous DataCap allocations? If any, please describe any of your honors or disputes in the field of Filecoin.

none

Allocation Plan
Please describe your plan to use the DataCap as detailed as possible, including use case, amount, timespan, geography, storage providers, partners, etc.

How many regions do you plan to store the data in?

Asia, Korea

How many storage providers you intend to make dealing with?

As many as possible, or 3 miners

Do you plan to record your allocation decisions and execution details in public? And how to realize it?

reveal all

Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?

yes

We may further ask some questions and then give an accurate score to the application. Thank you for your cooperation!

**Comment by IreneYoung** [comment]
@bicts  The initial score of your DataCap request is 4.
13 TiB DataCap are being granted to you. Congratulate!
See more details here: https://docs.google.com/spreadsheets/d/1LL1j5ksJAEItfHEB8MpT9lUHdzSFPsuzohNJUGZfOpc/edit#gid=0

**Comment by bicts** [comment]
@IreneYoung thank you.

**Comment by IreneYoung** [comment]
@bicts Plz send the business registration license through your company's email to irene@12ships.com.

**Comment by bicts** [comment]
I have already sent the business registration certificate, and since it is a small business, there is no corporate email.

**Comment by IreneYoung** [comment]
Already sent 13 TiB DataCap to your address. Please check it out! https://filfox.info/en/message/bafy2bzaceanq6aqewc6joiir5csbsvielohdmn27hxi7berhj2cv3ny6opcom
