### ISSUE TITLE
Client Allocation Request for: EST Digital Co., Ltd.

### ISSUE THREAD

**Issue by fjoianginaiwsnggw** [filecoin-project/filecoin-plus-client-onboarding#2469]
---

# Client Allocation Questions 

## Core Information
- Name: EST Digital Co., Ltd.
- Website / Social Media: https://upplus.co.kr/index.html
- Region: Asia (excl. Greater China)
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1pszx3dhfpdwwwgzturzrb35dd4b7uc7xtma6ywq
- Notary Requested: MasaakiNawatani

@fjoianginaiwsnggw Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MasaakiNawatani** [comment]
Hello @fjoianginaiwsnggw 

Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

```
Please answer here.
```

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 

```
Please answer here.
```

**Allocation Strategy
Do you intend to store your data in a single geography or many?

```
Please answer here.
```

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

```
Please answer here.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
Please answer here.
```

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

```
Please answer here.
```

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

```
Please answer here.
```

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

```
Please answer here.
```

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

```
Please answer here.
```

Are there any disputes open against you from your previous DataCap allocations?

```
Please answer here.
```

Have you ever previously violated:

- Your own attested allocation / audit plan?
- Been found to be in violation of the Principles of Filecoin Plus?

```
Please answer here.
```

**Comment by fjoianginaiwsnggw** [comment]
@MasaakiNawatani Hi Thanks for your quick response. Please check our answers.

1. Founded in 2021, we provide products with creativity, usability and convenience at reasonable prices to impress users. As the fast cross-border bay, UP+ provides users with a variety of popular products abroad through full fulfillment system. Powered by an outstanding end-to-end e-commerce and logistics network and customer-centric culture, UP+ has broken tradeoffs around speed, selection and price. Today, we provide exceedingly fast shipping speeds on millions of items, delivered within hours nationwide, 365 days a year. we deliver products and services that make lives better, easier and happier though increased functionality and fun. Put simply, we offer the latest innovations to make “Life Good”– from home appliances, consumer electronics and B2B solutions to innovations in digital signage, air conditioning, solar and vehicle components. As a global leader, we strive for greatness in product leadership, market leadership and people leadership to realize our growth strategies.

2. No. We haven’t been approved for a DataCap before.

3. We plan to store data in regions where it is most needed. Mainly Asia.

4. Yes. Fast retrieval will be required. 

5. We are partnering with several SPs in Asia. We will manage the storage with them and expand to other countries with very important data, we would store it in other countries using the data cap we are requesting.

6. Redundancy: 3 copies.
Proportion: more than 3 miners who enjoy a great reputation and are willing to store real data with stable nodes.

7. We are acting as the client on behalf of our users.

8. Yes, we will abide by local regulations and in compliance with the recipient miner’s terms of service.

9. None.

10. None.

11. None.

**Comment by fjoianginaiwsnggw** [comment]
@MasaakiNawatani Hi everything okay with the request?
