### ISSUE TITLE
Client Allocation Request for: ChainUP

### ISSUE THREAD

**Issue by wianeigniengggoe** [filecoin-project/filecoin-plus-client-onboarding#2481]
---

# Client Allocation Questions 

## Core Information
- Name: ChainUP
- Website / Social Media: https://www.chainup.com/
- Region: Asia (excl. Greater China)
- DataCap Requested: 30TiB
- Addresses to be Notarized: f1kbd5gfrl7rnnfg7wzylsh2tuwcbtlik3usz244i
- Notary Requested: MasaakiNawatani

@wianeigniengggoe Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by wianeigniengggoe** [comment]
@MasaakiNawatani Hi this request needs progress please. Thx

**Comment by MasaakiNawatani** [comment]
Hello @wianeigniengggoe 

Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

```
Please answer here.
```

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 

```
Please answer here.
```

**Allocation Strategy
Do you intend to store your data in a single geography or many?

```
Please answer here.
```

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

```
Please answer here.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
Please answer here.
```

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

```
Please answer here.
```

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

```
Please answer here.
```

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

```
Please answer here.
```

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

```
Please answer here.
```

Are there any disputes open against you from your previous DataCap allocations?

```
Please answer here.
```

Have you ever previously violated:

- Your own attested allocation / audit plan?
- Been found to be in violation of the Principles of Filecoin Plus?

```
Please answer here.
```

**Comment by wianeigniengggoe** [comment]
@MasaakiNawatani Thanks for the timely response. Here is the information you need. 

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

- As the world's leading blockchain technology service provider, founded in 2017 and headquartered in Singapore, ChainUp is a leader in blockchain technology and crypto ecosystem solutions. We have continued to enhance a number of maturing products such as digital asset trading systems, fiat on-ramp, wallet, security, mining, digital assets custody, investment, and NFTs and we have built an end-to-end closed industrial loop of technical services, innovative research and development, and traffic-commercialization.. We have built an end-to-end closed industrial loop of technical services, innovative research and development, and traffic-commercialization. At present, ChainUp has provided blockchain technology services to 1000+ clients in both crypto/blockchain and traditional industries in more than 30 countries and regions including the US, the UK, Australia, Japan, Thailand, etc., with coverage of over 60 million users. 

- ChainUp has established subsidiaries in Korea, Singapore, Japan, Hong Kong and other places. Among the top 100 non-small exchanges, ChainUP accounts for more than 30% of its customers. With more than 200 employees, core members are from the global IT, finance, software engineering and other industries, who have worked in Amazon, Google, Tencent, Baidu, China Renaissance Capital, Huobi, FBGCapital and other enterprises, showing rich experience in traditional finance, securities, Internet, blockchain and other services. Technical R & D personnel account for more than 70%, of which the core R & D personnel have more than 10 years of R & D experience.

- ChainUP Liquidity Platform (BitWind) is a liquidity service provider that aggregates the traffic of the world's top exchanges and ChainUP ecological exchanges, mainly for small and medium-sized digital currency exchanges, and has provided stable liquidity services for more than 300 customers around the world. At the same time, it can also provide liquidity services for institutional investors, brokers and other financial institutions. The liquidity of the cryptocurrency market is dispersed among many cryptocurrency exchanges, and BitWind is connected with multiple exchanges to increase liquidity competition and reduce spreads, creating the world's largest cryptocurrency liquidity pool.

https://esxieej3ow.feishu.cn/file/boxcnuKznPeGJhiMVl477ZHzwDe 
https://www.facebook.com/ChainUpTechnology/
https://twitter.com/ChainUPOfficial
https://www.linkedin.com/company/chainup-technology/about/
https://t.me/ChainUp2022

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)?

- No. It’s our first time working with Filecoin.

****Allocation Strategy**
Do you intend to store your data in a single geography or many?

- We plan to store data in multiple regions but mainly in Asia.

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

- Yes. We’re developing API sets that can boost and make distributed storage a reality for all types of clients.  

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

- We will store multiple copies of data across different data centers, and perhaps even regions, to ensure our data is reliably stored.

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

- We will engage at least 4 SPs and no single SP ID should receive >30% of our allocated DataCap to reliably store data on the network long term. 

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

- We are acting as the client on behalf of our users.

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

- Yes, we agree.

****Track Record**
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

- None.

Are there any disputes open against you from your previous DataCap allocations?

- None.

Have you ever previously violated:
Your own attested allocation / audit plan?
Been found to be in violation of the Principles of Filecoin Plus?

- None.

**Comment by AnthnoySmith** [comment]
Why do you provide the dishonest answer? 
![image](https://user-images.githubusercontent.com/94275737/191023332-b1e2671a-4735-4722-ad00-0219ecc10f4e.png)

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/292

**Comment by Tom-OriginStorage** [comment]
I'm from chainup Com But I don't know wianeigniengggoe. We applied for https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/292

 but we didn't apply for this Client Allocation Request.   
I can prove myself by any means, such as email and company information

@ wianeigniengggoe    who are you
