### ISSUE TITLE
Client Allocation Request for: Cobak

### ISSUE THREAD

**Issue by tokencan1** [filecoin-project/filecoin-plus-client-onboarding#2482]
---

# Client Allocation Questions 

## Core Information
- Name: Cobak
- Website / Social Media: https://cobak.co.kr/
- Region: Asia (excl. Greater China)
- DataCap Requested: 10TiB
- Addresses to be Notarized: f14huykewyaqqdw2qkhvpjfwcdr5gxoqjdy2giyxi
- Notary Requested: MasaakiNawatani

@tokencan1 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by tokencan1** [comment]
@MasaakiNawatani hello please let me know if you need any info. This request needs some update. Thanks

**Comment by MasaakiNawatani** [comment]
Hello @tokencan1 

Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

```
Please answer here.
```

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 

```
Please answer here.
```

**Allocation Strategy
Do you intend to store your data in a single geography or many?

```
Please answer here.
```

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

```
Please answer here.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
Please answer here.
```

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

```
Please answer here.
```

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

```
Please answer here.
```

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

```
Please answer here.
```

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

```
Please answer here.
```

Are there any disputes open against you from your previous DataCap allocations?

```
Please answer here.
```

Have you ever previously violated:

- Your own attested allocation / audit plan?
- Been found to be in violation of the Principles of Filecoin Plus?

```
Please answer here.
```

**Comment by tokencan1** [comment]
Hello @MasaakiNawatani Thanks for the reply.

Cobak, with its underlying foundations based on token sales and crypto forums, is the largest crypto platform that has the greatest number of members and wallets. The growth of the crypto community is inevitably tied to the growth of the crypto industry as a whole, and Cobak, as the most influential crypto community in Korea, will be the epicenter of this exponential growth. Cobak, which has accrued 300,000 crypto users in Korea, has been rewarding its participants for contributing through activities for the past two years. The reward system proves its value by making Cobak the most influential crypto community. In addition, Cobak is the only crypto service provider in Korea that is generating substantial crypto transactions excluding cryptocurrency exchanges. Cobak's issuance of tokens will further strengthen its user reward system, induce larger amounts of transactions within the platform and serve as a stepping stone for future global expansion.

Cobak is the world's first community that has a built-in blockchain wallet that launched its service in March 2018 and currently has 300,000 members. At the time of its establishment, due to the exponential growth of the crypto industry the market was flooded with new exchanges, digital assets, and false advertisement which made it difficult to have access to refined information and a comprehensive view of the prices of digital assets. To solve this problem, Cobak launched its data aggregation service that allowed users to check various market prices around the world at once and established a clean community without advertisements.

Over the past two years, Cobak has become the only community platform in Korea that provides real-time news on coin investment, announcements of projects and exchanges, from 12 major crypto media sources. Users engage each other whether in relation to information gathering and/or dissemination of community driven and curated information on projects. 

The token sale service, first launched in 2019, has caused Cobak to evolve into the most influential token sale platform in Korea through various ICO project sales reviewed by professional analysts.There has been 40 sold-out token sales which amounts to tokens worth nearly 10 billion won in total.

https://storage.cobak.co/custom_upload/1599808473023280_729b6827ea.pdf  
https://twitter.com/CobakOfficial 
https://cobak.medium.com/ 
https://www.instagram.com/cobak_official/ 
https://www.facebook.com/coindaebak

No. We haven’t been approved for a DataCap before.

Preferably in Asia.

Yes. We will use fast retrieval with our storage deals.  

We will store multiple copies of data separately to ensure our data is reliably stored.

We will allocate DataCap to 3 top-ranking SPs in the Filecoin miner reputation system and distribute DataCap to them evenly. 

We are acting as the client.

We will abide by the rules and guidelines set out.

None.

None.

None.

**Comment by tokencan1** [comment]
@MasaakiNawatani Hello, I have submitted the detailed information, Please let me know as soon as you take the review. Thanks!
