### ISSUE TITLE
Client Allocation Request for: Chomsio

### ISSUE THREAD

**Issue by Stanton15** [filecoin-project/filecoin-plus-client-onboarding#2483]
---

# Client Allocation Questions 

## Core Information
- Name: Chomsio
- Website / Social Media: https://chomsio.com/
- Region: Greater China Region
- DataCap Requested: 100TiB
- Addresses to be Notarized: f122yjwsn7h4hmx4suhxo53msgdbbarg3ilkyontq
- Notary Requested: MatrixStorage

@Stanton15 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MatrixStorage** [comment]
Hey @Stanton15 , thank you for choosing IPFS. In order to ensure that I know enough about your company, please reply to my following questions, so that I can correctly judge whether DC can be assigned to you.
- Could you please introduce the term, nature and scale of your company in detail?
```
```
- What industries/how many people does the company mainly serve?
```
```
- Can you tell me about your future business or technology plans?
```
```
- Can you explain the data type and copyright ownership in detail?    How much data does your company store?
```
```
- Does your company need to invoke stored data, and if so, how often does this happen?
```
```
- How many miners do you want to select to store data?    How many DataCap will be assigned to each miner?
```
```
Looking forward to your reply.

**Comment by MatrixStorage** [comment]
Additional questions:
1. Do you accept random sample data inspection?
2. Have you applied for DataCap before? If so, please indicate.

**Comment by Stanton15** [comment]
We accept random data checks.This is our second application.  #2473

**Comment by MatrixStorage** [comment]
Thank you for your application, but I'm afraid I can't give you much DataCap this time, but you can apply to me or another notary after you've finished using it.
I expect to give you 50TiB for the first time

**Comment by MatrixStorage** [comment]
I have finished the approval.  If the system does not respond later, I will manually close this issue.
