### ISSUE TITLE
Client Allocation Request for: Coresight

### ISSUE THREAD

**Issue by Coresightscout** [filecoin-project/filecoin-plus-client-onboarding#2530]
---

# Client Allocation Questions 

## Core Information
- Name: Coresight
- Website / Social Media: http://www.coresight.io/
- Region: Asia (excl. Greater China)
- DataCap Requested: 30TiB
- Addresses to be Notarized: f1yjmos75r7zt5dpr4cal5jkkievflmqitasolbxa
- Notary Requested: MasaakiNawatani

@Coresightscout Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MasaakiNawatani** [comment]
Hello @Coresightscout 

Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

```
Please answer here.
```

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 

```
Please answer here.
```

**Allocation Strategy
Do you intend to store your data in a single geography or many?

```
Please answer here.
```

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

```
Please answer here.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
Please answer here.
```

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

```
Please answer here.
```

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

```
Please answer here.
```

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

```
Please answer here.
```

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

```
Please answer here.
```

Are there any disputes open against you from your previous DataCap allocations?

```
Please answer here.
```

Have you ever previously violated:

- Your own attested allocation / audit plan?
- Been found to be in violation of the Principles of Filecoin Plus?

```
Please answer here.
```

**Comment by Coresightscout** [comment]
@MasaakiNawatani Hi please refer to the following. Feel free to ping me should you need futher information. Thanks!

Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

~~~gfm
Founded in 2015 in Seoul, Republic of Korea, Coresight has been developing game analysis software intended to optimize real-time data analysis solutions for games. We collect all logs related to gameplay, such as level-up information, game quest statistics, and game money statistics, and analyze large amounts of data using big data-based real-time distributed processing technology, thereby allowing users to have fun by updating content. We give value to every action of game users. The Core of the game is fun, and Coresight will design these fun together. 
~~~

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)?

~~~gfm
No. It’s our first time working with Filecoin.
~~~

**Allocation Strategy**
Do you intend to store your data in a single geography or many?

~~~gfm
We intend to store data in Asia and mostly in Korea if possible.
~~~

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

~~~gfm
Yes. Fast Retrieval will be required.
~~~

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

~~~gfm
We will store the private key associated with the DataCap allocation address securely. 
~~~

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

~~~gfm
We’d like to work with 4-5 miners who enjoy a great reputation and are willing to store real data with each miner storing between 20-25% of the data.
~~~

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

~~~gfm
We are acting as the client on behalf of our users.
~~~

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

~~~gfm
Yes.
~~~

**Track Record**

Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

~~~gfm
None.
~~~

Are there any disputes open against you from your previous DataCap allocations?

~~~gfm
None.
~~~

Have you ever previously violated:

- Your own attested allocation / audit plan?
- Been found to be in violation of the Principles of Filecoin Plus?

~~~gfm
None.
~~~
