### ISSUE TITLE
Client Allocation Request for: GANADAIO CO.,LTD

### ISSUE THREAD

**Issue by Ganadaioly** [filecoin-project/filecoin-plus-client-onboarding#2558]
---

# Client Allocation Questions 

## Core Information
- Name: GANADAIO CO.,LTD
- Website / Social Media: http://www.ganadaio.net/ja-JP/case
- Region: Asia (excl. Greater China)
- DataCap Requested: 30TiB
- Addresses to be Notarized: f1pvqt754w3r6djygzmx4iqsiksr2p7qrvtpbpn5q
- Notary Requested: IreneYoung

@Ganadaioly Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IreneYoung** [comment]
Hi @Ganadaioly  - Thanks for your application. Please answer the following questions to let us know about you, your company, and further information about the DataCap allocation.

Basic Info
What's your name and your position in your company?

Please introduce yourself and your team briefly. How many team members do you have in your R&D or core team? Could you provide several Github accounts or email addresses of them?

For your organization, Please describe its business, its history since inception, registration country, scale, employee counts, operation regions, named executive officers, relevant projects, industry reputation, etc.

Please show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links) to show your Web3 reputation or external reputation.

Please provide your company's business registration license. If you have any presentation documents about your business, please provide them to us. And also could send me via email for privacy concerns. My contact: [irene@12ships.com](mailto:irene@12ships.com)

How long have the team core members been engaged in development?

What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?

Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization?

Where is your data stored now? Whether the data is stored on a server or a cloud service provider?

Track Record
Has your organization obtained DataCap before? if so, please answer the following sub-questions.
1.1 Please share all the links and recordings of your applications before.
1.2 How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?
1.3 What was your allocation strategy plan then and how did you execute it?

Are there any disputes open against you from your previous DataCap allocations? If any, please describe any of your honors or disputes in the field of Filecoin.

Allocation Plan
Please describe your plan to use the DataCap as detailed as possible, including use case, amount, timespan, geography, storage providers, partners, etc.

How many regions do you plan to store the data in?

How many storage providers you intend to make dealing with?

Do you plan to record your allocation decisions and execution details in public? And how to realize it?

Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?

We may further ask some questions and then give an accurate score to the application. Thank you for your cooperation!

**Comment by Ganadaioly** [comment]
@IreneYoung Hi, please refer to below for the requested information and do let me know should you need additional information.

**Basic Info**
What's your name and your position in your company?

- My name is Hiroto and I’m Team Manager.

Please introduce yourself and your team briefly. How many team members do you have in your R&D or core team? Could you provide several Github accounts or email addresses of them?

- Our team has been providing technology development services to medical, healthcare direction, financial direction, commercial transactions, international trade, etc. 
- We have 8 members in our R&D team.

For your organization, Please describe its business, its history since inception, registration country, scale, named executive officers, relevant projects, industry reputation, etc.

- GANADAIO CO., LTD (hereinafter abbreviated as GND) is a comprehensive system company engaged in FinTech application and software development. Our core business is to provide complete set services of FinTech technology and application solutions and software development services to traditional enterprises around the world, and provide FinTech technology and application consulting services to governments and industry authorities. At the same time, the GND will take full advantage of the cooperation advantages of China, Japan and South Korea to form a market of high-tech products and product interoperability, thereby forming comprehensive development advantages. 
- Founded in 2020 in Japan, GND established financial technology companies in Guiyang and Hainan, China, and then set up a subsidiary in Hong Kong. We work with strong companies from various industries in Japan to jointly create archetypal cases for financial technology applications. Cooperating with Japanese government agencies and leveraging the experience of cooperation with Guiyang government in China, we provide the government with typical solutions of financial technology for government, commercial and private use.
- On November 29, 2018, the attention-grabbing “Golden Stone Project Japan Press Conference” was held on the 28th floor of Tokyo Garden Terrace Kiimachi at 14:30 local time. The implementation plan for the world's first culture and health industry based on blockchain technology has been officially launched. In a homely atmosphere, guests from different countries experienced the fusion scene of Eastern cultural temperament and blockchain sentiment.


Please show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links) to show your Web3 reputation or external reputation.

- N/A

Please provide your company's business registration license. If you have any presentation documents about your business, please provide them to us. And also could send me via email for privacy concerns. My contact: [irene@12ships.com](mailto:irene@12ships.com)

- Will send by email.

How long have the team core members been engaged in development?

- Almost 2 years.

What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?

- User data, automation data, advance analytics data, financial data, financial applications data, identity management data, FinTech UI/UX and web design data, and digital banking data, etc.
- 30 TiB will be needed.

Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization?

- Data generated during the operation of our business.


Where is your data stored now? Whether the data is stored on a server or a cloud service provider?

- Company's server.

**Track Record**
Has your organization obtained DataCap before? if so, please answer the following sub-questions.
1.1Please share all the links and recordings of your applications before.
1.2How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?
1.3What was your allocation strategy plan then and how did you execute it?

- N/A

Are there any disputes open against you from your previous DataCap allocations? Please describe any of your honors or disputes in the field of Filecoin.

- N/A

**Allocation Plan**
Please describe your plan to use the DataCap as detailed as possible, including use case, amount, timespan, geography, storage providers, partners, etc.

How many regions do you plan to store the data in?

- Mostly in Japan.

How many storage providers you intend to make dealing with?

- More than 3 SPs in Asia with good reputation and stable nodes.

Do you plan to record your allocation decisions and execution details in public? And how to realize it?

- Yes. We plan to make our distribution records publicly accessible in GitHub.

Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?

- Yes, we agree to abide by relevant regulations and terms of service.

We may further ask some questions and then give an accurate score to the application. Thank you for your cooperation!
