### ISSUE TITLE
Client Allocation Request for: Server Building Training

### ISSUE THREAD

**Issue by ecology7** [filecoin-project/filecoin-plus-client-onboarding#2574]
---

# Client Allocation Questions 

## Core Information
- Name: Server Building Training
- Website / Social Media: http://ecology.kro.kr
- Region: Asia (excl. Greater China)
- DataCap Requested: 20TiB
- Addresses to be Notarized: f16kzs4xiymvou6wp3xplpomtimrhloqf2xmuh36a
- Notary Requested: IreneYoung

@ecology7 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IreneYoung** [comment]
Hi @ecology7  - Thanks for your application. Please answer the following questions to let us know about you, your company, and further information about the DataCap allocation.

Basic Info
What's your name and your position in your company?

Please introduce yourself and your team briefly. How many team members do you have in your R&D or core team? Could you provide several Github accounts or email addresses of them?

For your organization, Please describe its business, its history since inception, registration country, scale, employee counts, operation regions, named executive officers, relevant projects, industry reputation, etc.

Please show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links) to show your Web3 reputation or external reputation.

Please provide your company's business registration license. If you have any presentation documents about your business, please provide them to us. And also could send me via email for privacy concerns. My contact: [irene@12ships.com](mailto:irene@12ships.com)

How long have the team core members been engaged in development?

What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?

Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization?

Where is your data stored now? Whether the data is stored on a server or a cloud service provider?

Track Record
Has your organization obtained DataCap before? if so, please answer the following sub-questions.
1.1 Please share all the links and recordings of your applications before.
1.2 How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?
1.3 What was your allocation strategy plan then and how did you execute it?

Are there any disputes open against you from your previous DataCap allocations? If any, please describe any of your honors or disputes in the field of Filecoin.

Allocation Plan
Please describe your plan to use the DataCap as detailed as possible, including use case, amount, timespan, geography, storage providers, partners, etc.

How many regions do you plan to store the data in?

How many storage providers you intend to make dealing with?

Do you plan to record your allocation decisions and execution details in public? And how to realize it?

Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?

We may further ask some questions and then give an accurate score to the application. Thank you for your cooperation!

**Comment by ecology7** [comment]
@IreneYoung  hello.
I am Minho Kim, the deputy director of global information companies.
It consists of a total of 20 people and 5 core engineers.
Company email : support@ecology.kro.kr


Founded in Korea in 2018, he is working on blockchain as a specialized electronic device company. The related project is trying to deliver filecoin information to Korea, gather investors, and continue to manufacture and sell servers.

The business registration certificate will be sent by email.
It's about 4 years.

http://ecology.kro.kr/room/20220811_191304228.MP4
http://ecology.kro.kr/room/T5788554.jpg
http://ecology.kro.kr/room/T8818559.jpg
http://ecology.kro.kr/room/T10025887.jpg
http://ecology.kro.kr/room/T10055887.jpg

All data is made by the company, and various materials such as promotional videos and block chain related information videos are directly produced and stored.

External hard drive, part of web server

I never got a data cap.

Korea or Asia

We are familiar with Filecoin, and the data cap will not exceed 30% of each storage provider.

Everything will be recorded publicly, and data will be saved if it complies with local regulations and the miner's terms and conditions.

**Comment by IreneYoung** [comment]
@ecology7 
1. How many storage providers you intend to make dealing with?
2. Plz send the business registration certificate through your company email as soon as possible.

**Comment by ecology7** [comment]
1. 4 or more companies
2. Email sent. If you haven't received it, please tell me.

**Comment by IreneYoung** [comment]
@ecology7 The initial score of your DataCap request is 4.
20 TiB DataCap are being granted to you. Congratulate!
See more details here:
https://docs.google.com/spreadsheets/d/1IItb4g6l9BVeqW_alowf9DtHc-KFUmT5PjLXu8VKt7Q/edit#gid=0

**Comment by ecology7** [comment]
@IreneYoung  hello.
Are there any problems with datacap assignment?

**Comment by IreneYoung** [comment]
@ecology7 Sorry, the notary's ledger is temporarily unavailable, plz wait for a while.

**Comment by IreneYoung** [comment]
@ecology7 Already sent 20 TiB DataCap to your address. Please check it out!

**Comment by ecology7** [comment]
@IreneYoung thank you
