### ISSUE TITLE
Remaining Datacap Allocation Issues: Ninth Heaven Guild

### ISSUE THREAD

**Issue by xiaoliuxiao6** [filecoin-project/filecoin-plus-client-onboarding#2591]
---

# Client Allocation Questions 

## Core Information
- Name: Ninth Heaven Guild
- Website / Social Media: https://ninthheaven.io/
- Region: North America
- DataCap Requested: 100TiB
- Addresses to be Notarized: f3wzua4wihcouehv5datojpgalyapegvdfkhkqamxdtr4tzcsn7kylkoaapmmxisbp3tzekgijb32lrswf5t5q
- Notary Requested: neogeweb3

@xiaoliuxiao6 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by xiaoliuxiao6** [comment]
I have applied for 100TiB before. After the application is approved, only 1TiB is allocated for the first time, and now the remaining quota needs to be allocated

@neogeweb3

**Comment by neogeweb3** [comment]
Hey, thanks for the request. Since you have requested DataCap from me before, I have some questions regarding your previous DataCap allocation. 
1.	How much cumulative DataCap was allocated to you from me?
2.	In which region(s) did you use the DataCap?
3.	What was your use case for the previous allocation? 
4.	Did you specify any advanced features for the previous allocation? 
5.	How many miners did you allocate the DataCap to? Please specify transaction links to the storage deals. 
6.	In your previous allocation, did you violent any community principles like excessive/unfair (20% of DataCap allocation) self-dealing?

**Comment by xiaoliuxiao6** [comment]
1. 1TiB
2. China
3. some database backups
4. No
5. https://filfox.info/zh/address/f0148494
6. No

**Comment by xiaoliuxiao6** [comment]
Do I need to provide additional information?
@neogeweb3

**Comment by neogeweb3** [comment]
Why you posted the link with f0148494, please specify transaction links to the storage deals.

**Comment by xiaoliuxiao6** [comment]
You only gave me a capacity of 1TiB, so I can only find one node and make the first storage attempt
What are you referring to transaction links?

**Comment by neogeweb3** [comment]
It looks like you chose SP f07919, is there any reasons why you posted f0148494 instead of f07919, what is the relationship between f07919 and f0148494? Transaction links refer to https://filplus.d.interplanetary.one/clients/f01852089

**Comment by xiaoliuxiao6** [comment]
f0148494 I don't know whose node

No special reason, only 1TiB of Datacap available, only enough for testing process

I just send all data to  f07919

**Comment by xiaoliuxiao6** [comment]
It was me who recorded the error, originally intended to give f0148494, but since the node has not responded, so I gave f07919, my local document has not been updated nor confirmed by FIlecoin

No special reason, only 1TiB of Datacap available, only enough for testing process，So I didn't think too much
