### ISSUE TITLE
Client Allocation Request for: natural environment big data

### ISSUE THREAD

**Issue by parimons** [filecoin-project/filecoin-plus-client-onboarding#2637]
---

# Client Allocation Questions 

## Core Information
- Name: natural environment big data
- Website / Social Media: nhncam.kro.kr
- Region: Asia excl. Greater China
- DataCap Requested: 30TiB
- Addresses to be Notarized: f1l6wqjuw7vz5brcmsxzre37j5agtr73ekjtosfjq
- Notary Requested: IreneYoung

@parimons Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IreneYoung** [comment]
Hi @parimons  - Thanks for your application. Please answer the following questions to let us know about you, your company, and further information about the DataCap allocation.

Basic Info
What's your name and your position in your company?

Please introduce yourself and your team briefly. How many team members do you have in your R&D or core team? Could you provide several Github accounts or email addresses of them?

For your organization, Please describe its business, its history since inception, registration country, scale, employee counts, operation regions, named executive officers, relevant projects, industry reputation, etc.

Please show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links) to show your Web3 reputation or external reputation.

Please provide your company's business registration license. If you have any presentation documents about your business, please provide them to us. And also could send me via email for privacy concerns. My contact: [irene@12ships.com](mailto:irene@12ships.com)

How long have the team core members been engaged in development?

What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?

Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization?

Where is your data stored now? Whether the data is stored on a server or a cloud service provider?

Track Record
Has your organization obtained DataCap before? if so, please answer the following sub-questions.
1.1 Please share all the links and recordings of your applications before.
1.2 How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?
1.3 What was your allocation strategy plan then and how did you execute it?

Are there any disputes open against you from your previous DataCap allocations? If any, please describe any of your honors or disputes in the field of Filecoin.

Allocation Plan
Please describe your plan to use the DataCap as detailed as possible, including use case, amount, timespan, geography, storage providers, partners, etc.

How many regions do you plan to store the data in?

How many storage providers you intend to make dealing with?

Do you plan to record your allocation decisions and execution details in public? And how to realize it?

Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?

We may further ask some questions and then give an accurate score to the application. Thank you for your cooperation!

**Comment by parimons** [comment]
I am Kim Hyuk-soo, and I am in charge of image information processing. The position is team leader, and the core number is 9 people.
J-mail is khs7855@nhncam.kro.kr
Company manager email: admin@nhncam.kro.kr

Our company is located in Korea and was established in July 2009. The total number of people is 32, video team 9 people, editing 2 people, audio 2 people, public relations team 5 people and other 15 people. We are promoting and filming related media videos ourselves.

https://nhncam.kro.kr/

We will send it to the official company email account.

9 years.


It is for the purpose of promoting cultural festivals or protecting nature, and requires a capacity of about 60 TiB.
This is a related video. Uploading to YouTube as well.

https://nhncam.kro.kr/mpss/manduck.mp4
https://nhncam.kro.kr/mpss/jirisan.mp4
https://nhncam.kro.kr/mpss/SeodoStation.mp4
https://nhncam.kro.kr/mpss/Wetland.mp4

All videos were shot on-site by the company's filming team, are for promotional purposes, and are owned by the company.


I'm keeping it on an external hard drive and server, and I want to use a datacap for data backup.

Track Record
Has your organization obtained DataCap before? if so, please answer the following sub-questions.
1.1 Please share all the links and recordings of your applications before.
1.2 How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?
1.3 What was your allocation strategy plan then and how did you execute it?

Are there any disputes open against you from your previous DataCap allocations? If any, please describe any of your honors or disputes in the field of Filecoin.

Not applicable.

Allocation Plan

I received a subtotal of the Filecoin project through an acquaintance, and I want to keep it in Asia if possible.\

4-5 companies

I will do it publicly if I can.

I agree to abide by local regulations in the use of data caps and to abide by the Terms of Service.

**Comment by parimons** [comment]
@IreneYoung hello. 
How long should I wait?

**Comment by IreneYoung** [comment]
@parimons The initial score of your DataCap request is 5.
30 TiB DataCap are being granted to you. Congratulate!
See more details here: https://docs.google.com/spreadsheets/d/1kwsVG8yiSNWXv6opoGPN0PBStx1vrxYW7y7aDtl70jY/edit#gid=0

**Comment by IreneYoung** [comment]
@parimons Already sent 30 TiB DataCap to your address. Please check it out!
