### ISSUE TITLE
Client Allocation Request for: Whyrusleeping

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/filecoin-plus-client-onboarding#266]
---

# Client Allocation Questions 

## Core Information
- Name: Whyrusleeping
- Website / Social Media: github.com/whyrusleeping
- Region: North America
- DataCap Requested: 20TiB
- Addresses to be Notarized: f3vnq2cmwig3qjisnx5hobxvsd4drn4f54xfxnv4tciw6vnjdsf5xipgafreprh5riwmgtcirpcdmi3urbg36a
- Notary Requested: andrewxhill

**Comment by whyrusleeping** [comment]
cc @andrewxhill I changed this request to you

**Comment by andrewxhill** [comment]
Hey @whyrusleeping , thanks for the request. To help with the verification process, could you please provide as thorough of answers as you can to the following questions.

1. Can you introduce yourself? Where can I find you online? Examples include Github, Twitter, LinkedIn, WeChat, etc., and more than one is encouraged.
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3. In which region(s) do you intend to use the DataCap?
4. What is your use case for the DataCap being requested?
5. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
6. How many miners do you plan on allocating the DataCap? Please specify if you have a specific miner(s) you would like to allocate the DataCap.
7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing? If so, how will you plan to report it?
8. Will your organization be responsible for allocating the full DataCap? Examples where this might not be the case, include app builders where the application end-users may have access to storage backed by the DataCap. Please read our full proposal for details on this approach. Unfortunately, our proposed multisig enabled DataCap provider is not ready today, but when it is, we will provider further documentation.
9. Please share any other information you believe is relevant to your application. If you or your org has received DataCap previously, could you share details on how this project differs or is an extension of those others.

Thanks,

Andrew

**Comment by whyrusleeping** [comment]
1.I'm @whyrusleeping, I make lots of cool software like IPFS, Libp2p and Filecoin
2. I work for Protocol Labs
3. I am located in north america, but will try to make deals with miners anywhere in the world.
4. I am going to be trying to store large machine learning datasets in filecoin
5. no, i dont know what advanced features those might be
6. No specific miners, currently just pulling from a fairly big list I have and round robining between them
7. Sure? I can provide access to my source code that will be doing the automated deal making
8. I am responsible
9. I'm @whyrusleeping,  I write code. People seem to have liked that so far.

**Comment by andrewxhill** [comment]
> 5. no, i dont know what advanced features those might be

K, i'll list examples in the future. Just things like offline vs online deals, using any auction or bidding with miners, unexpected things.

> 7. Sure? I can provide access to my source code that will be doing the automated deal making

Sounds perfect

**Comment by andrewxhill** [comment]
20TiB Confirmed

https://filfox.info/en/message/bafy2bzacedmzugpbvpol7zccug36o3jhfuo7sxfkb4v22kibbem72gziddb7s
