### ISSUE TITLE
Client Allocation Request for: PiKNiK

### ISSUE THREAD

**Issue by data-programs** [filecoin-project/filecoin-plus-client-onboarding#2676]
# Client Allocation Questions

## Core Information
- Name: PiKNiK
- Website / Social Media: [https://www.piknik.com/](https://www.piknik.com/), (https://www.linkedin.com/company/piknikus, LinkedIn)
- Region: North America
- DataCap Requested: 1.5 TiB
- Addresses to be Notarized: f1pakqdbs44c4vue4o527gzwckzn2orczq4d6e2ty
- Notary Requested: s0nik42
- Github handle: @PiKNiK-Company

**Comment by scharfstein** [comment]
@s0nik42 

Here are some additional details about our request:

1) Our relationship with the data, especially with regard to copyright

PiKNiK's customer is a company called Reelspot, a startup out of Bogota, Colombia that has relationships with many TV/movie companies in Central and South America. This 1.5 TiB is part of a proof of concept with one of these companies called Mega Global Entertainment [https://mgenetwork.tv/en/]. MGE owns the copyright to this data. Reelspot is in agreement with MGE and PiKNiK is under NDA with both companies to store this data. All information being presented here is approved for public display by Reelspot + MGE.

2) The data will be encrypted

3) How you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Since this is a proof of concept, we plan to store one copy in our Las Vegas, USA datacenter. Assuming that the proof of concept goes well, MGE will want to store several hundred TiB, and for this data set, we plan to store five copies, across multiple storage providers.

4) Previous datacap we have received. We have no ongoing requests.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/388
- Dcent - Wijnand
- Twin Quasar - Julien
- Fenbushi - Kobby
- Holon
- Kernelogic - Fei Yan

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/464
- Cabrina Huang
- Techgreedy - Xinan
- Fenbushi - Kobby
- Dcent - Wijnand
- Telnyx - Brandon

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/522
- Claudia Richoux
- Alex Kim
- Gary Gao

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/431
- Dcent - Wijnand
- Filswan - Charles Cao
- Fenbushi - Kobby
- Origin Storage
- Irene Young

STORAGE PROVIDERS :

How much data are you considering storing to your own miner ?

1.5TiB

Please describe the nature of the relationship you have with the miners you are going to store data to. Especially if you have any interests ?

For this 1.5 TiB data set, we only plan to store one copy.

**Comment by s0nik42** [comment]
Hi @scharfstein Ok to allocate 1.5TB to this POC.
