### ISSUE TITLE
Client Allocation Request for: Xinchuang Storage

### ISSUE THREAD

**Issue by xcstoage** [filecoin-project/filecoin-plus-client-onboarding#2693]
# Client Allocation Questions

## Core Information
- Name: Xinchuang Storage
- Website / Social Media: [https://xcstorage.eth.limo/](https://xcstorage.eth.limo/), (xcstoage, xcstoage)
- Region: Greater China
- DataCap Requested: 5 TiB
- Addresses to be Notarized: f3sdu7c4hkqrr6nejb7obawtnrexdfxcxaepxnui6zqzsgqv6dtd7vyklyzuetfcdqsrp3heey7tculohkdsqq
- Notary Requested: Anne

**Comment by 1ane-1** [comment]
Declaration：Get contact from Slack.
Hey @xcstoage , thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can.

1，Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.), 
2，If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3，In which region(s) do you intend to use the DataCap?,
4，What is your use case for the DataCap being requested?
5，Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.,
6，How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify.
7，Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?
Moreover, I encourage you to take a look of my allocation https://github.com/filecoin-project/notary-governance/issues/732 which shows how I utilize the assessment. Thanks.

**Comment by xcstoage** [comment]
> 
1.xcstorage is my github account name, and i am the person in charge of Data storage.
2.Our company name is 信创存储。We are registerd in China with 60+ members. 
3.Mainly in China
4.The use case for datacap is our charity data and our videoes that comes from the buildingand some movie videoes.
5.I don't plan to use specify advanced features when utilizing a DataCap.
6. at least 4 Sps
7.Yes, totally aggree with you.
Thanks~
