### ISSUE TITLE
Client Allocation Request for: Zoland-TV

### ISSUE THREAD

**Issue by zolandtv** [filecoin-project/filecoin-plus-client-onboarding#2694]
# Client Allocation Questions

## Core Information
- Name: Zoland-TV
- Website / Social Media: [http://www.zolandtv.com/ http://www.zolandanimation.com/](http://www.zolandtv.com/ http://www.zolandanimation.com/), (Social Media: https://twitter.com/ZolandGroup https://www.facebook.com/zolandanimation http://www.instagram.com/zolanddistribution http://www.youtube.com/c/zolandanimation https://www.linkedin.com/company/zolanddistribution/, web)
- Region: Greater China
- DataCap Requested: 5 TiB
- Addresses to be Notarized: f1ka66piios6kglll2ace2amu26kxl4m4rgh5m56q
- Notary Requested: Anne

**Comment by 1ane-1** [comment]
Declaration：Get contact from Slack.
Hey @zolandtv  , thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can.

1，Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.),
2，If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3，In which region(s) do you intend to use the DataCap?,
4，What is your use case for the DataCap being requested?
5，Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.,
6，How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify.
7，Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?
Moreover, I encourage you to take a look of my allocation https://github.com/filecoin-project/notary-governance/issues/732 which shows how I utilize the assessment. Thanks.

**Comment by 1ane-1** [comment]
@zolandtv  Any update?

**Comment by zolandtv** [comment]
@1ane-1 Sorry for the late reply.

You can contact me through github.
In 2003, ZolandTV Group realized cross domain industry upgrading and established ZhejiangZoland animation Co., Ltd. to build a pan entertainment ecosystem integrating animation creativity, animation distribution, authorized marketing, technology research and development, cultural tourism, animation performance and other industries. At present, it has become one of the largest original animation companies in China.

Our main name is: Zoland-TV. established in '03, and our main business is currently in China. The small 5t plan we are currently applying for is for use in China, and mainly stores public data from the work computers of corporate content employees.

**Comment by zolandtv** [comment]
I will send you more information via slack, please check it out.

**Comment by 1ane-1** [comment]
> I will send you more information via slack, please check it out.

Thank you! I will check it.

**Comment by 1ane-1** [comment]
signed, pls check it.
