### ISSUE TITLE
Client Allocation Request for: 河南中创算力信息科技有公司

### ISSUE THREAD

**Issue by KIMQI001** [filecoin-project/filecoin-plus-client-onboarding#362]
---

# Client Allocation Questions 

## Core Information
- Name: 河南中创算力信息科技有公司
- Website / Social Media: ZhongchuangIPFS on Slack
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3wwiudiv2vjdswtc4aab5o3qs6ygeujrrixyv6a2z4o6aoma34rjayapsmwvqxxgn7aavmzomfquzwd2dn3fa
- Notary Requested: neogeweb3

**Comment by neogeweb3** [comment]
Hey @KIMQI001, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1.	Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2.	If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3.	In which region(s) do you intend to use the DataCap? 
4.	What is your use case for the DataCap being requested? 
5.	Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6.	How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7.	Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

Moreover, I encourage you to take a look of my allocation [strategy ](https://github.com/filecoin-project/notary-governance/issues/11) and [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)which shows how I utilize the assessment. Thanks.

**Comment by KIMQI001** [comment]
I think maybe I should request another the cap after I read ur strategy
