### ISSUE TITLE
Client Allocation Request for: Chengdu Maitian Yunji Technology Co., Ltd

### ISSUE THREAD

**Issue by beyongo** [filecoin-project/filecoin-plus-client-onboarding#379]
---

# Client Allocation Questions 

## Core Information
- Name: Chengdu Maitian Yunji Technology Co., Ltd
- Website / Social Media: https://www.mtfs.top/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1sunlw7emt6sswtsusctngqmiynz5g6n4qmzi5ey
- Notary Requested: neogeweb3

**Comment by beyongo** [comment]
Plz change the _NAME_ to _Chengdu Maitian Yunji Technology Co., Ltd，_，thx.

**Comment by beyongo** [comment]
@neogeweb3 plz check，thx  : )

**Comment by neogeweb3** [comment]
Hey @beyongo, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1.	Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2.	If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3.	In which region(s) do you intend to use the DataCap? 
4.	What is your use case for the DataCap being requested? 
5.	Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6.	How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7.	Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

Moreover, I encourage you to take a look of my allocation [strategy ](https://github.com/filecoin-project/notary-governance/issues/11) and [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)which shows how I utilize the assessment. Thanks.

**Comment by beyongo** [comment]
Thank you，

**Comment by beyongo** [comment]
Thanks for your reply，

**Comment by neogeweb3** [comment]
Hey @beyongo, I will close this request due to a lack of response. Feel free to reopen again if you have answers to my questions.

**Comment by llb890427** [comment]
@neogeweb3 Hello, may I add your WeChat? In order to better and efficient communication of this problem. My WeChat number is 13730657072
