### ISSUE TITLE
Client Allocation Request for: USC Shoah Foundation

### ISSUE THREAD

**Issue by anitapac** [filecoin-project/filecoin-plus-client-onboarding#402]
---

# Client Allocation Questions 

## Core Information
- Name: USC Shoah Foundation
- Website / Social Media: SFI.USC.EDU
- Region: North America
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3w5fx6wta4ewl2iyf7xcogmzffz2fmrngpzdpduj3xmk3dwjxc6dyq36gdf3rflkkrblh5nci5xymc5hal3qq
- Notary Requested: andrewxhill

**Comment by andrewxhill** [comment]
Hi @anitapac, sorry for the delay, your application slipped through the cracks for a minute.

As part of the onboarding process, would you mind answering the following:

1. Can you introduce yourself? Where can I find you online? Examples include Github, Twitter, LinkedIn, WeChat, etc., and more than one is encouraged.
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3. In which region(s) do you intend to use the DataCap?
4. What is your use case for the DataCap being requested?
5. How many miners do you plan on allocating the DataCap? Please specify if you have a specific miner(s) you would like to allocate the DataCap.
6. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing? If so, how will you plan to report it?
7. Will your organization be responsible for allocating the full DataCap? Examples where this might not be the case, include app builders where the application end-users may have access to storage backed by the DataCap. Please read our full proposal for details on this approach. Unfortunately, our proposed multisig enabled DataCap provider is not ready today, but when it is, we will provider further documentation.

Thanks!

**Comment by anitapac** [comment]
Hello,
Thanks for getting back to me.   See my responses below.

As part of the onboarding process, would you mind answering the following:

  1.  Can you introduce yourself? Where can I find you online? Examples include Github, Twitter, LinkedIn, WeChat, etc., and more than one is encouraged.  Github - ***@***.***,  Linkedin anita pace
  2.  If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? USC Shoah Foundation,   Genocide Archive, USA, est 1994 CTO Sam Gustman
  3.  In which region(s) do you intend to use the DataCap? Global
  4.  What is your use case for the DataCap being requested? To distribute, store preserve testimony data
  5.  How many miners do you plan on allocating the DataCap? about 20 Please specify if you have a specific miner(s) you would like to allocate the DataCap.
  6.  Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing? yes If so, how will you plan to report it? tbd
  7.  Will your organization be responsible for allocating the full DataCap? yes Examples where this might not be the case, include app builders where the application end-users may have access to storage backed by the DataCap. Please read our full proposal for details on this approach. Unfortunately, our proposed multisig enabled DataCap provider is not ready today, but when it is, we will provider further documentation.

Regards,

Anita Pace
Managing Director of Technology
[cid:791fd0a2-60e3-4f12-a1f5-2ddbe8a75cf5]
    http://sfi.usc.edu/

________________________________

**Comment by andrewxhill** [comment]
Great, thanks! We've applied the Datacap, you should be good to go.

https://filfox.info/en/message/bafy2bzaceadecomlk4dhvemllx4njtd5dkz6wbki5siwq4ukvl4bwedpoeye6
