### ISSUE TITLE
Client Allocation Request for: Protocol Labs

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/filecoin-plus-client-onboarding#429]
---

# Client Allocation Questions 

## Core Information
- Name: Protocol Labs
- Website / Social Media: nft.storage
- Region: North America
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3taer3ffzqswg37e73h5kjd75pmnrckvyfhsonhlmvy4bzpyekbkv3d3gyxet4j2e4owndbaamvo447wzufrq
- Notary Requested: andrewxhill

@jnthnvctr Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by jnthnvctr** [comment]
A note - this is related to the issue that Mikeal originally filed [here](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/237). 

NFT.Storage has not burned through its original allocation yet - though based on our current estimates we will be through the majority of it by late this week, early next week. This ticket is to just kick off the process for a renewal process (so we can submit requisite information)

**Comment by andrewxhill** [comment]
Hi @jnthnvctr, thanks. I can use the original responses to continue the vetting process. Since this is a renewal, could you answer a couple of new questions before we move forward?

### Usage

1. What portion of the originally granted datacap have you used to date? 
2. If less than 100% could you provide a short justification for why the early application?
3. If less than 100% and using a new target address, do you still plan on utilizing the original datacap too?

### Deployment

1. Can you provide any information on the deals you've created and miners you've used with your previously allocated datacap?
2. Are there any significant changes to your original application in terms of use-case, data inputs, or miner allocation?

thanks!
