### ISSUE TITLE
Client Allocation Request for: McKurz Capital Incorporated

### ISSUE THREAD

**Issue by georgemac510** [filecoin-project/filecoin-plus-client-onboarding#497]
---

# Client Allocation Questions 

## Core Information
- Name: McKurz Capital Incorporated
- Website / Social Media: @mckurz
- Region: North America
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3vn6ehbqdfsw36272obqpmekuswz5pqs47mtk27h56tmgaltmderm5g5sfj77unb47oiyef4zeszbtqu4lt6a
- Notary Requested: andrewxhill

@georgemac510 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by georgemac510** [comment]
Hi Andrew,

Can I please change the DataCap requested to 1 TiB?

Thanks,

John McLaughlin

**Comment by andrewxhill** [comment]
Hi @georgemac510, 

I've made the edit to your application, please verify that everything above looks correct. 

I can use the original responses to continue the vetting process. Since this is a renewal (previous application here https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/341), could you answer a couple of new questions before we move forward?

### Usage

1. What portion of the originally granted datacap have you used to date? 
2. If less than 100% could you provide a short justification for why the early application?
3. If less than 100% and using a new target address, do you still plan on utilizing the original datacap too?

### Deployment

1. Can you provide any information on the deals you've created and miners you've used with your previously allocated datacap?
2. Are there any significant changes to your original application in terms of use-case, data inputs, or miner allocation?

thanks!

**Comment by georgemac510** [comment]
Hi Andrew,

Thank you so much for updating and considering my new verification
request.  The answers to the above follow:

*Usage*
           1)  I have 889.05 GiB left in my granted DataCap, so ~111 GiB's
used.
           2)  I have been using the granted allocation toward Slingshot
2.3 on the Fin-File Crypto project and due to a family emergency was not
                 able to finish and submit my work for 2.3. Having dealt
with family issue and getting back to development and hacking, I would
like                       to use the remainder of the granted allocation
for Slingshot 2.4 and my dataset Top 100 Crypto Investor Dataset. The new
application will be used for Sligshot 2.4 as well

**Comment by georgemac510** [comment]
Hi Andrew,

Thank you so much for updating and considering my new verification
request.  The answers to the above follow:

*Usage*
           1)  I have 889.05 GiB left in my granted DataCap. I have used
over 100 GiB's thus far.
           2)  I have been using the granted allocation toward Slingshot
2.3 on the Fin-File Crypto project and due to a family emergency
       was not able to finish and submit my work for 2.3. Having dealt with
the family issue and getting back to development and
 hacking, I would like to use the remainder of the granted allocation for
Slingshot 2.4 and my dataset Top 100 Crypto
 Investor Dataset. The new application will be used for Sligshot 2.4 as
well, but under a different project, Fin-File Stock
   Market under a the Textile Hub address

f3vn6ehbqdfsw36272obqpmekuswz5pqs47mtk27h56tmgaltmderm5g5sfj77unb47oiyef4zeszbtqu4lt6a.
            3)  I will absolutely finish utilizing the granted DataCap for
the Fin-File Crypto project and will probably ask for additional
                 datacap once the 889.05 GiB has been exhausted.

*Deployment*
             1)  Please refer to the following link which lists data such
as deal ID, miner ID, CID, etc. from the deals that were completed
             with the granted datacap:

https://docs.google.com/spreadsheets/d/1TlULkqwqQqflPVCdHkUH888J6ZlfDHNFH9kOl1mIjvc/edit?usp=sharing
             2)  There will be no changes to use-case, data inputs or miner
allocation with the exception of using a different dataset. In
             this case, Huge Stock Market Dataset will be used for Fin-File
Stock Market.

Thank you very much for your consideration. I am looking forward to
participating in Slingshot 2.4 and this additional datacap will allow me to
utilize two different datasets.

Best regards,

John McLaughlin
***@***.***
***@***.***
