### ISSUE TITLE
Client Allocation Request for: Terrada-Soko

### ISSUE THREAD

**Issue by terada-soko** [filecoin-project/filecoin-plus-client-onboarding#513]
---

# Client Allocation Questions 

## Core Information
- Name: Terrada-Soko
- Website / Social Media: https://www.terrada.co.jp/en
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1faypdbgzfb3epdqx4c34jry375liyt6nykgps2q
- Notary Requested: MasaakiNawatani

@terada-soko Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MasaakiNawatani** [comment]
Hello @terada-soko

Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

```
Please answer here.
```

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 

```
Please answer here.
```

**Allocation Strategy
Do you intend to store your data in a single geography or many?

```
Please answer here.
```

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

```
Please answer here.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
Please answer here.
```

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

```
Please answer here.
```

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

```
Please answer here.
```

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

```
Please answer here.
```

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

```
Please answer here.
```

Are there any disputes open against you from your previous DataCap allocations?

```
Please answer here.
```

Have you ever previously violated:

- Your own attested allocation / audit plan?
- Been found to be in violation of the Principles of Filecoin Plus?

```
Please answer here.
```

**Comment by terada-soko** [comment]
Thank you for your quick action @MasaakiNawatani 

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

```
Warehouse TERRADA was established in 1950. Our experience in warehousing has made us leaders in technology and expertise. We have integrated this with IT to bring you cloud warehousing, accessible anywhere, connecting people and things instantly. We have been in the Web 3.0 space with Filecoin and IPFS since the beginning.

Company Name	Warehouse TERRADA
Representative	President & CEO  Kohei Terada
Building Office	2-6-10 Higashi-Shinagawa, Shinagawa-ku, Tokyo 140-0002 JAPAN
```

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 

```
No. This will be our first time to request for DataCap.
```

**Allocation Strategy
Do you intend to store your data in a single geography or many?

```
We intend to store data in regions where it is most needed. Mainly within Asia.
```

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

```
Yes. We will use DIGITAL SOUKO API sets that can make a storage for all types of our data. 
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
We will set up a new storage as storage provider in Japan. We manage and maintain the storage by ourselves and other storage providers with Japan market. Also, when we found very important data, we would store it by the data cap.
```

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

```
We intend to spread it across multiple miners who are willing to accept our deals.
```

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

```
We are applying as the client on behalf of our users. 
```

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

```
Yes. We intend to fully adhere to local regulations and comply with the recipient miner's T.O.S.
```

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

```
None. This will be the first time. 
```

Are there any disputes open against you from your previous DataCap allocations?

```
None.
```

Have you ever previously violated:

- Your own attested allocation / audit plan?
- Been found to be in violation of the Principles of Filecoin Plus?

```
No. We are committed to upholding the values and principles of Filecoin. 
```

**Comment by MasaakiNawatani** [comment]
Hi @terada-soko , I will now close this application due to lack of response for 14 days. You may re-apply again when your team is ready. Thanks.
