### ISSUE TITLE
Client Allocation Request for: Paralym Art

### ISSUE THREAD

**Issue by kenparalymart** [filecoin-project/filecoin-plus-client-onboarding#541]
---

# Client Allocation Questions 

## Core Information
- Name: Paralym Art
- Website / Social Media: https://paralymart.or.jp
- Region: Asia excl. Greater China
- DataCap Requested: 120GiB
- Addresses to be Notarized: f1urqho5vnjwkjlx7ookv5lg2uf27f5ybu5rwdhsi
- Notary Requested: MasaakiNawatani

@kenparalymart Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MasaakiNawatani** [comment]
Hello @kenparalymart 

Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

```
Please answer here.
```

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 

```
Please answer here.
```

**Allocation Strategy
Do you intend to store your data in a single geography or many?

```
Please answer here.
```

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

```
Please answer here.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
Please answer here.
```

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

```
Please answer here.
```

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

```
Please answer here.
```

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

```
Please answer here.
```

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

```
Please answer here.
```

Are there any disputes open against you from your previous DataCap allocations?

```
Please answer here.
```

Have you ever previously violated:

- Your own attested allocation / audit plan?
- Been found to be in violation of the Principles of Filecoin Plus?

```
Please answer here.
```

**Comment by kenparalymart** [comment]
Hi @MasaakiNawatani 

Thank you for the quick response. Just a small issue, this is not our first time to request with you. However, the first 120 GiB datacap we receive from you is unusable since we lost our private key for that address. We would like to request again and ask to have the previous allocation burned. Is that possible?

Thank you so much.

**Comment by kenparalymart** [comment]
> Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.
> 
> ```
> Paralym Art is an organization that supports the financial independence of disabled artists by connecting them with companies and other organizations. We showcase original artworks by disabled artists to companies and other organizations and process the payment in a secured and efficient way. 
> ```
> 
> Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)?
> 
> ```
> This will be our 2nd time to request. Our first request was not used because we lost the private key to the address. 
> ```
> 
> **Allocation Strategy
> Do you intend to store your data in a single geography or many?
> 
> ```
> Single. We prefer to work with a storage provider that exists or based in Japan.
> ```
> 
> Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?
> 
> ```
> If the storage provider has Fast retrieval, it will be fine.
> ```
> 
> How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
> 
> ```
> After we decide which storage provider we use then actually store our data. Then we will show our web page which you can see our data can be retrieved from storage provider.
> ```
> 
> Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?
> 
> ```
> So far we will use all DataCap to a single provider but if our business goes smoothly and expands, we may consider storing our data with another provider as backup.
> ```
> 
> For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?
> 
> ```
> N/A
> ```
> 
> Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?
> 
> ```
> Yes. We intend to fully abide by the rules and guidelines set forth. 
> ```
> 
> **Track Record
> Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.
> 
> ```
> This will be our second time. You granted us 120 GiB but unfortunately, we lost our private keys for that address so we would like to request again. Please see issue #113. 
> ```
> 
> Are there any disputes open against you from your previous DataCap allocations?
> 
> ```
> None.
> ```
> 
> Have you ever previously violated:
> 
> Your own attested allocation / audit plan?
> Been found to be in violation of the Principles of Filecoin Plus?
> 
> ```
> We have no history of any sort of violation. This is our first time to submit a request.
> ```

**Comment by MasaakiNawatani** [comment]
Hi @kenparalymart 

Thank you for answering promptly. I will review the information you provided and the previous approved allocation that I have done.

**Comment by MasaakiNawatani** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaisygzcerblltzlppb5y2ejtdxxamzk45kxkky5w4i6wvmpnudgu 
#### Address 
> f1urqho5vnjwkjlx7ookv5lg2uf27f5ybu5rwdhsi
#### Datacap Allocated
> 120GiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaisygzcerblltzlppb5y2ejtdxxamzk45kxkky5w4i6wvmpnudgu
