### ISSUE TITLE
Client Allocation Request for: 

### ISSUE THREAD

**Issue by swatchliu** [filecoin-project/filecoin-plus-client-onboarding#577]
---

# Client Allocation Questions 

## Core Information
- Name: 
- Website / Social Media: 
- Region: North America
- DataCap Requested: 1TiB
- Addresses to be Notarized: 
- Notary Requested: philippbanhardt

@swatchliu Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Hiu @swatchliu, could you [resubmit](https://plus.fil.org/) with the address you would like the datacap to be allocated for in the "Datacap requested" field, and what the data will be?

(I'm closing this, because this application won't work correctly without a FIL address. Please do re-apply though!)

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
