### ISSUE TITLE
Client Allocation Request for: Santanu Das

### ISSUE THREAD

**Issue by d2as2** [filecoin-project/filecoin-plus-client-onboarding#604]
---

# Client Allocation Questions 

## Core Information
- Name: Santanu Das
- Website / Social Media: genrait.com
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: 
- Notary Requested: andrewxhill

@d2as2 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by andrewxhill** [comment]
Hi @d2as2, so I can evaluate your application, could you answer the following questions for me. 

1. Can you introduce yourself? Where can I find you online? Examples include Github, Twitter, LinkedIn, WeChat, etc., and more than one is encouraged.
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3. In which region(s) do you intend to use the DataCap?
4. What is your use case for the DataCap being requested?
5. How many miners do you plan on allocating the DataCap? Please specify if you have a specific miner(s) you would like to allocate the DataCap.
6. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing? If so, how will you plan to report it?
7. Will your organization be responsible for allocating the full DataCap? Examples where this might not be the case, include app builders where the application end-users may have access to storage backed by the DataCap. Please read our full proposal for details on this approach. Unfortunately, our proposed multisig enabled DataCap provider is not ready today, but when it is, we will provider further documentation.

thanks!

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
