### ISSUE TITLE
Client Allocation Request for: Almarship

### ISSUE THREAD

**Issue by EVE1011** [filecoin-project/filecoin-plus-client-onboarding#683]
---

# Client Allocation Questions 

## Core Information
- Name: Almarship
- Website / Social Media: http://www.almarship.biz
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1cuqelfynn5uhexdy53xonbdtn7f3c5atzcg7tna
- Notary Requested: Broz221

@EVE1011 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Broz221** [comment]
@EVE1011 
Hi, thanks for application!

Could you please introduce you and your company?

**Comment by phlippixo** [comment]
I am pleased to take this opportunity to introduce our company.

Almar Shipping Corporation, Panama, founded in 1996,We provide a full range of management services to a variety of leading companies in the shipping industry.

Our company arranges ship management and manning services through our own subsidiary company especially strategically located in Odessa, which is one of the biggest center of shipping business on Black Sea. There are many educational facilities in Odessa working in the heart of Black Sea shipping industry including Odessa National Maritime Academy, Odessa National Maritime University, Odessa Marine College, Odessa Marine College of Technical Fleet and many schools and training centers for education and certification of officers, ratings and specialists in any field of shipping field. Of course, all of them are certified in accordance with newest requirements of international conventions and latest regulations.

Our main specialization is multipurpose and ro-ro vessels. Our dedicated teams oversee all aspects of ship management from chartering and crewing to sophisticated repairing and financial issues as well.

I'm sure you're curious as to why we applied for DataCap.

In order to diversify our company, we are always looking for new economic opportunities in addition to our shipping business.We noticed Bitcoin, but unfortunately it was banned by several governments, but we think blockchain is really a great technology.After our research, we believe that Filecoin is relatively safe.And we are constantly trying new possibilities, thanks to Musk's Starlink, the cost of network transmission at sea is greatly reduced. We can try to run this program in low-cost regions of the world, which I think is very potentially promising.

**Comment by EVE1011** [comment]
I am pleased to take this opportunity to introduce our company.

Almar Shipping Corporation, Panama, founded in 1996,We provide a full range of management services to a variety of leading companies in the shipping industry.

Our company arranges ship management and manning services through our own subsidiary company especially strategically located in Odessa, which is one of the biggest center of shipping business on Black Sea. There are many educational facilities in Odessa working in the heart of Black Sea shipping industry including Odessa National Maritime Academy, Odessa National Maritime University, Odessa Marine College, Odessa Marine College of Technical Fleet and many schools and training centers for education and certification of officers, ratings and specialists in any field of shipping field. Of course, all of them are certified in accordance with newest requirements of international conventions and latest regulations.

Our main specialization is multipurpose and ro-ro vessels. Our dedicated teams oversee all aspects of ship management from chartering and crewing to sophisticated repairing and financial issues as well.

I'm sure you're curious as to why we applied for DataCap.

In order to diversify our company, we are always looking for new economic opportunities in addition to our shipping business.We noticed Bitcoin, but unfortunately it was banned by several governments, but we think blockchain is really a great technology.After our research, we believe that Filecoin is relatively safe.And we are constantly trying new possibilities, thanks to Musk's Starlink, the cost of network transmission at sea is greatly reduced. We can try to run this program in low-cost regions of the world, which I think is very potentially promising.

**Comment by Broz221** [comment]
@EVE1011 Hi. Then I would like to know your data related information.

Could you please send me some data demo?
What kind of data do you want to store?
Why you need 10 TiB datacap?

**Comment by Broz221** [comment]
@EVE1011 Hi. I also want to know your allocation decision.

How many miners do you want to store? For how many regions?
What questions would you ask the miners?
What do you do to prevent overallocation?

**Comment by EVE1011** [comment]
Dear@Broz221  Glad to see your reply

1.We think more than 3 is reasonable,It mainly depends on the scale of the miner and the price.

2.The price of their services geographical location and technical capabilities.

3.We will allocate DataCap reasonably to prevent overallocation.

**Comment by Broz221** [comment]
Hi, I read your website. Your company is an Ukrainian company. So we'd love to suggest you to find a Europe notary.
![1630375266(1)](https://user-images.githubusercontent.com/75763153/131429613-14867926-7740-4b2d-a7a0-8d4315d7927f.png)

**Comment by EVE1011** [comment]
I think there's some misunderstanding here, and I stated that we are a company from Panama.  @ialberquilla Can you help me with this?
