### ISSUE TITLE
Client Allocation Request for: Ecotek

### ISSUE THREAD

**Issue by AkilaCV** [filecoin-project/filecoin-plus-client-onboarding#684]
---

# Client Allocation Questions 

## Core Information
- Name: Ecotek
- Website / Social Media: http://ecotek-canada.vn/en/
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1jnyebzddyzchcsnducsfbfcn65hadyenuky2r4i
- Notary Requested: Broz221

@AkilaCV Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Broz221** [comment]
@AkilaCV 
Hi, thanks for application!

Could you please introduce you and your company?

**Comment by phlippixo** [comment]
Hi@Broz221

I am Alila, the technical manager of the Canadian branch of NGUYEN HA CO.，LTD. Our main business is the development, manufacture, production and sale of electronic components. We have branches in both the United States and Canada and have long-standing, stable relationships with local telecommunications and information technology companies. We learned about Filecoin from our business partners,

Our management center deletes a lot of device IoT information every year because we don't think this data is currently generating value. But Filecoin can store this data at a very low cost, and I think this is very necessary for us.

**Comment by AkilaCV** [comment]
Hi@Broz221

I am Alila, the technical manager of the Canadian branch of NGUYEN HA CO.，LTD. Our main business is the development, manufacture, production and sale of electronic components. We have branches in both the United States and Canada and have long-standing, stable relationships with local telecommunications and information technology companies. We learned about Filecoin from our business partners,

Our management center deletes a lot of device IoT information every year because we don't think this data is currently generating value. But Filecoin can store this data at a very low cost, and I think this is very necessary for us.

**Comment by Broz221** [comment]
@AkilaCV 
Hi. Then I would like to know your data related information.

Could you please send me some data demo?
What kind of data do you want to store?
Why you need 10 TiB datacap?

**Comment by Broz221** [comment]
@AkilaCV Hi, I viewed your website and found out it was a Vietnam company. So I suggest you to choose an Asia notary.
