### ISSUE TITLE
Client Allocation Request for: Contentos Foundation Ltd.

### ISSUE THREAD

**Issue by Zapataha** [filecoin-project/filecoin-plus-client-onboarding#718]
---

# Client Allocation Questions 

## Core Information
- Name: Contentos Foundation Ltd.
- Website / Social Media: https://www.contentos.io
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1mxyqm2afyy66ftc554iurq4pwjschzmeq7ke5zi
- Notary Requested: IreneYoung

@marfazyheir48 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IreneYoung** [comment]
@marfazyheir48  Thanks for your application. Please answer the following questions to let us know about you, your company, and further information about the DataCap allocation.

> ## Basic Info

1. What's your name and your position in your company? 

2. Please introduce yourself and your team briefly. 

3. For your organization, Please describe its business, its history since inception, registration country, scale, named executive officers, relevant projects, industry reputation, etc. 

4. Please provide your company's business registration license. And show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links). If you have any presentation documents about your business, please provide them to us.

5. What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?

6. Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization? 

> ## Track Record
1. How did you know about Filecoin? Please feel free to describe your understanding of Filecoin storage and the Filecoin Plus program.

2. Has your organization obtained DataCap before? if so, please answer the following sub-questions.
2.1 Please share all the links and recordings of your applications before.
2.2 How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?
2.3 What was your allocation strategy plan then and how did you execute it?

3. Are there any disputes open against you from your previous DataCap allocations? Please describe any of your honors or disputes in the field of Filecoin.

> ## Allocation Plan

1. Please describe your plan to use the DataCap as detailed as possible? (including use case, amount, timespan, geography, miner, partner, etc.)

2. Do you plan to record your allocation decisions and execution details in public? And how to realize it?
What's your plan to make sure the DataCap you have obtained will be used to its best advantage?

3. Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?

We may further ask some questions and then give an accurate score to the application. Thank you for your cooperation!

**Comment by marfazyheir48** [comment]
Basic Info

1.I’m Zac Nien, the Vice President in our company.

2.I ‘m VP of Product. I am mainly responsible for the product. Mick Tsai is the Co-Founder & CEO. Ava Wen is the VP of Marketing. Peter Wei is the VP of Engineering. This is our team.

3.Contentos is a blockchain-based decentralized content protocol. Our goal is to build a decentralized global content incentive and distribution system through blockchain technology and distributed storage. The agreement allows producers to no longer need to distribute and profit through the centralization platform channels, but can directly reach consumers or advertisers for free production, storage and distribution. Really realize a system of fair value measurement, open and transparent prices, large numbers of profit, and multiple win-win systems.We will have an accounting system, content publishing system, copyright registration, creator authentication, likes and comments forwarding, search components, etc.
Contentos will enable the state through official encrypted tokens, and use the tokens for rewards for use and all transactions and circulation within the state. The trading system also includes virtual gift trading rewards, advertising monetization, digital content trading, in-state payment purchases, digital asset wallets, etc.
Users can also post individual digital assets on the Contentos public chain, and purchasers and senders can automatically complete the purchase through smart contracts without the involvement of third-party intermediaries.
Contentos will provide a social network that connects all people, distribute and spread through socialized mass, and achieve close connections between users through rewards, revenue sharing, and the introduction of content partnerships.
Charles Fan is the founder and CEO of MemVerge. Hitters Xu is the founder of Nebulas. We began in May 2018. In September 2019, Contentos content public chain v1.0 was released.

4. I will send the business license by email. These link can help you to know briefly about our company. https://twitter.com/contentosio
https://medium.com/contentos-io

5. We mainly want to store videos. And we need more than 10 TiB. I will send the sample data by email too.

6. These data mainly came from users uploading by themselves. When users want to use our website to upload, it means that they agree with us to help them store and display.

Track Record

1. Via the internet.
I think Filecoin Plus is an additional program designed to strengthen the verification mechanism of valid data; and valid data that has passed the audit will be increased by 10 times the current "storage capacity". The purpose is to allow more real data to be stored in the Filecoin network, rather than the current running "junk data" occupying storage space.

2.No, we have never obtained DataCap before.

3.No, we have never obtained DataCap before.

Allocation Plan

1.We need more than 10TiB/ 2 months. We store the data in China. We need 4 miners.

2.Yes, we will. We will use github to record. We will estimate the required space and allocate it reasonably.

3.Yes, we will obey the rules.

**Comment by marfazyheir48** [comment]
Hey can we go on with this application? Is there any problem about it? @IreneYoung

**Comment by IreneYoung** [comment]
@marfazyheir48 Great! Please send your business license and sample data to the email address: contact@12ships.com

**Comment by marfazyheir48** [comment]
Hi. I have already sent it to you. Please check it.

**Comment by IreneYoung** [comment]
Hi @marfazyheir48, thanks for your request!  Your initial rounded score is 4. 

Per your application and the allocation rubric, you/your organization will be receiving an allocation of 10 TiB.

The initially scored rubric can be found here: https://docs.google.com/spreadsheets/d/1MWVjfRaZIQDB5y_Zg22Oqpy6iplUZBiaAygeP7vzlSM/edit?usp=sharing
Please take a look at the notes (column M) and share any relevant additional details here in the comments if you'd like us to update your score ideally within the next 3 days.

**Comment by marfazyheir48** [comment]
Thank you very much！

**Comment by IreneYoung** [comment]
OK! Therefore the final rounded score is 4. 
I will approve an allocation of 10TiB within 2 days. 

Thanks for your cooperation. If any problem, please contact me at any time.

**Comment by IreneYoung** [comment]
@Zapataha Please confirm your address :

Addresses to be Notarized: f1mxyqm2afyy66ftc554iurq4pwjschzmeq7ke5zi

**Comment by Zapataha** [comment]
Yes，that‘s the right address. Thanks a lot！

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6kateijklvmm7x2x2lmjgxf2xaorbfcelvhw7yr6622jsrqp4wy 
#### Address 
> f1mxyqm2afyy66ftc554iurq4pwjschzmeq7ke5zi
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6kateijklvmm7x2x2lmjgxf2xaorbfcelvhw7yr6622jsrqp4wy
