### ISSUE TITLE
Client Allocation Request for: grette.no

### ISSUE THREAD

**Issue by hymorbra** [filecoin-project/filecoin-plus-client-onboarding#828]
---

# Client Allocation Questions 

## Core Information
- Name: grette.no
- Website / Social Media: https://grette.no/en/
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1d77nswekbjcxtod5clv4bhubqonmsn7yv7rr54y
- Notary Requested: Broz221

@hymorbra Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Reiers** [comment]
_@Broz221 This is a Norwegian Company by the looks of it. This allocation request is under North America, not Europe. 
Since I'm from Norway I can have look at the Company as well._ 

Hi @hymorbra thank you for your request. 
I found a lot of info about **Advokatfirmaet Grette AS** on the website and I'd like to know more about your business. 
Please answer following questions:

- Some more info about yourself , e.g. include links to social media / news mentions etc.

- What’s the original source of the data, and do you have any proof of ownership or authorization?
_Public data vs Private data, your relationship with the data, especially with regard to copyright etc._

- Has your organization/company obtained DataCap before?

- Please describe your plan to use DataCap briefly?
_Such as use case, miner etc._

- How you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

- Have you already ask datacap to another notary that have been accepted or rejected?

Thanks!

-Nicklas

**Comment by dkkapur** [comment]
Will be reassigning to @TimWilliams00. Awaiting repo settings update.
