### ISSUE TITLE
Client Allocation Request for: LandSatFile/FilHub

### ISSUE THREAD

**Issue by LandsatFile20** [filecoin-project/filecoin-plus-client-onboarding#84]
---

# Client Allocation Questions 

## Core Information
- Name: LandSatFile
- Website / Social Media: https://preview.filhub.com
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3qaj4wnnkv6ptwfxqzbnwd3acgzwzmj77eygtwatkm2omh6emgvtoszgedvfxfxv5ibf42ivlrr6kfz6x5tyq
- Notary Requested: NeoGe-IPFSMain

**Comment by NeoGe-IPFSMain** [comment]
Hey @LandsatFile20, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1. Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3. In which region(s) do you intend to use the DataCap? 
4. What is your use case for the DataCap being requested? 
5. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6. How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

Before starting to answer questions, I encourage you to take a look of our allocation strategy [here ](https://github.com/filecoin-project/notary-governance/issues/11)which shows how we utilize the assessment.

Thanks.

**Comment by LandsatFile20** [comment]
**0. Filhub DataCaps History**
[2021-2-8  5T Used ](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/115) [No fil was charged from miners]

> there must be controversy in the market (#fil-deal-market on slack).
> Filhub is willing to put it into practice.
> However, some miners are particularly disgusted with this behavior (Selling Datacaps),
> I think let them receive  datacaps (low price or free) first.
> If verified clients and miners complete a large number of datacaps storage.
> More datacaps was stored  , more easier  to discussions about the market  .
> Verified client needs to store and transmit data at cost (different region), they want some profit or at least cover.
> Miners also want to share the revenue from datacaps .
discuss in slack  [link1](https://filecoinproject.slack.com/archives/C01KCAAURAN/p1612899254127200)
**For new datacap , I will contact 5 new miners to store 1tib copies . Minerx first [ 0 Fil from them]**

**1. yourself, e.g. include links to social media/news mentions, etc**

Landsatfile team has been in Filecoin ecosystem from 2020-6-1, we established Fuzhou HaoNengCloud Technology Co., Ltd, and began to work as start-up company.
Since September 2020, we participated in Slingshot competition by Protocol Labs and developed an application named LandSatFile.
And then Start-up project: FilHub @ 2021-1-20 http://preview.filhub.com

Slingshot project link : [https: //slingshot.filecoin.io/project/5fc274a7bb7b32dc2a0841d2](https: //slingshot.filecoin.io/project/5fc274a7bb7b32dc2a0841d2)
Project website: http://preview.filhub.com
Slack: @Hao-FilHub

**2. your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc**

Participating in Slingshot 2.2 with over 400 TiB data
Participated in Slingshot 2.1
Eligible Data: over 100TiB
Storage Awards: 2nd Place

Start-up project: FilHub @2021-1-20 http://preview.filhub.com
@Hao-FilHub : Actively help folks in the slack community, you can search for.

**3.type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data, etc**

All of the data on Landsatfile are useful and valid, and from public datasets, which are on the list of Filecoin Slingshot curated datasets.
_Dataset Desc_
- name : **CCAFS-Climate Data**
> High resolution climate data to help assess the impacts of climate change primarily on agriculture. These open access datasets of climate projections will help researchers make climate change impact assessments.
website: ttp://www.ccafs-climate.org/
- Dataset size : 6.8 TiB ( 1TiB was stored on Filecoin)


**4.your relationship with the data, especially with regard to copyright**

All data are from public open datasets, as a result, there is no copyright issue involved.

**5.how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc**
Redundancy: at least 3 copies
Location: intend to store data  EU/CN .  **datacenter in EU :  2Gbps in  / datacenter in CN : 2Gbps**
Miner: have a great reputation and contribution in Filecoin Community, accept real data deals during Slingshot Competition, or are willing to store real data on Filecoin Network.

**6.Would you be OK in posting deal transactions here?**
Sure.

**Comment by neogeweb3** [comment]
Hey @LandsatFile20, are you experiencing any difficulties while collecting answers? Let me know if I could help.
