### ISSUE TITLE
Client Allocation Request for: Re-invention Japan

### ISSUE THREAD

**Issue by reinventionjp** [filecoin-project/filecoin-plus-client-onboarding#869]
---

# Client Allocation Questions 

## Core Information
- Name: Re-invention Japan
- Website / Social Media: http://www.re-invention.jp/
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f1zuevr32ju6w76g5nosztp4fhj3kmrbzvz3u3wzy
- Notary Requested: MasaakiNawatani

@reinventionjp Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MasaakiNawatani** [comment]
Hi @reinventionjp, 

Please respond to the questions below in paragraph form, replacing the text saying 'Please answer here'. Include as much detail as you can in your answer!

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

```
Please answer here.
```

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 

```
Please answer here.
```

**Allocation Strategy
Do you intend to store your data in a single geography or many?

```
Please answer here.
```

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

```
Please answer here.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
Please answer here.
```

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

```
Please answer here.
```

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

```
Please answer here.
```

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

```
Please answer here.
```

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

```
Please answer here.
```

Are there any disputes open against you from your previous DataCap allocations?

```
Please answer here.
```

Have you ever previously violated:

- Your own attested allocation / audit plan?
- Been found to be in violation of the Principles of Filecoin Plus?

```
Please answer here.
```

**Comment by reinventionjp** [comment]
Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

```
I am the external affairs officer of Re-Invention Co., Ltd. which was duly established on July 30, 2013 by CEO Dr. Keiji Ohta and COO Taro Tomio. We are in the business of planning, production and consultation of XR (extended reality) entertainment contents. 
We are challenging the global XR market through products, content and services themselves. We are creating a new culture and implementing the “re-invention” of products, content and services in the global market via the collaboration of members with diverse backgrounds with a high level of business acumen and fresh ideas. 

```

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)? 

```
No. This will be our first request. 
```

**Allocation Strategy
Do you intend to store your data in a single geography or many?

```
We are planning to save massive XR contents and files. However, as of now, it takes time to recover from Filecoin, therefore we will use a hybrid method for fast retrieval by using both local and online platforms. Once Filecoin stabilizes the retrieval protocols, we will use Filecoin exclusively.  

```

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

```
If the storage provider has Fast retrieval, it will be fine.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

```
After we decide which storage provider we use, we actually store our data. Then we will show our web page where you can see our data can be retrieved from a storage provider.
```

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

```
So far we will use all DataCap to a single provider but if our business goes smoothly and expands, we may consider storing our data with another provider as backup.
```

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

```
We are acting as the client on behalf of our end-users.
```

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

```
Yes.
```

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

```
N/A
```

Are there any disputes open against you from your previous DataCap allocations?

```
None.
```

Have you ever previously violated:

- Your own attested allocation / audit plan?
- Been found to be in violation of the Principles of Filecoin Plus?

```
No
```

**Comment by MasaakiNawatani** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbkutl7bt5cecbymqxilzwm4omgnmk3e7d2o6h3ao2gkjwx6443s 
#### Address 
> f1zuevr32ju6w76g5nosztp4fhj3kmrbzvz3u3wzy
#### Datacap Allocated
> 1TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbkutl7bt5cecbymqxilzwm4omgnmk3e7d2o6h3ao2gkjwx6443s
