### ISSUE TITLE
Client Allocation Request for: SAO Network

### ISSUE THREAD

**Issue by SAONetwork01** [filecoin-project/filecoin-plus-client-onboarding#897]
---

# Client Allocation Questions 

## Core Information
- Name: SAO Network
- Website / Social Media: 
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1e7yni2vwywcvfaanmywooca6hubousyevwnbqry
- Notary Requested: IreneYoung

@Adele0x Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IreneYoung** [comment]
@Adele0x    Thanks for your application. Please answer the following questions to let us know about you, your company, and further information about the DataCap allocation.

> ## Basic Info

1. What's your name and your position in your company? 

2. Please introduce yourself and your team briefly. 

3. For your organization, Please describe its business, its history since inception, registration country, scale, named executive officers, relevant projects, industry reputation, etc. 

4. Please provide your company's business registration license. And show us some of your web pages, Github, social media accounts such as Twitter, Facebook, Naver blog, WeChat official account, etc. Please include as many relevant details to provide contextual information (with external links). If you have any presentation documents about your business, please provide them to us.

5. What types of data do you plan to store with the DataCap and how many do you need? Could you please send us some of your sample data?

6. Regarding the data you intend to store, What’s the original source of those data, and do you have any proof of the ownership or authorization? 

> ## Track Record
1. How did you know about Filecoin? Please feel free to describe your understanding of Filecoin storage and the Filecoin Plus program.

2. Has your organization obtained DataCap before? if so, please answer the following sub-questions.
2.1 Please share all the links and recordings of your applications before.
2.2 How about your DataCap usage? Is there any remaining? Is there any information on the deals you've done and the miners you've allocated your DataCap to?
2.3 What was your allocation strategy plan then and how did you execute it?

3. Are there any disputes open against you from your previous DataCap allocations? Please describe any of your honors or disputes in the field of Filecoin.

> ## Allocation Plan

1. Please describe your plan to use the DataCap as detailed as possible? (including use case, amount, timespan, geography, miner, partner, etc.)

2. Do you plan to record your allocation decisions and execution details in public? And how to realize it?
What's your plan to make sure the DataCap you have obtained will be used to its best advantage?

3. Do you agree to use the DataCap to only store data that abide by local regulations and is in compliance with the recipient miner’s terms of service?

We may further ask some questions and then give an accurate score to the application. Thank you for your cooperation!

**Comment by IreneYoung** [comment]
@SAONetwork01 Hello, sorry you have to reply in the comment. Regarding the request is closed, you can re-open or start a new application.

**Comment by IreneYoung** [comment]
Oh, I re-opened the issue, so please leave your answers here. Thanks
