### ISSUE TITLE
Client Allocation Request for: Samjung

### ISSUE THREAD

**Issue by Samjungee** [filecoin-project/filecoin-plus-client-onboarding#947]
---

# Client Allocation Questions 

## Core Information
- Name: Samjung
- Website / Social Media: http://e-samjung.co.kr/gnuboard4/
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3vnnnt6zokj2bfplbzrqiwukdi6y7xprt36vdrnljw752hturceqql5z4grkdwhqws4zxrly5ymyjptdv5oma
- Notary Requested: neogeweb3

@Samjungee Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by neogeweb3** [comment]
Hey @Samjungee, thanks for the request. I have some questions regarding your request. Please describe answers as much specificity as you can. 
1.	Can you introduce yourself? Where can I find you online? (Github, Twitter, Linkedin handle, Wechat, etc.) 
2.	If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization? 
3.	In which region(s) do you intend to use the DataCap? 
4.	What is your use case for the DataCap being requested? 
5.	Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature. 
6.	How many miners do you plan on allocating the DataCap? If you have a specific miner(s) you would like to allocate a DataCap, please specify. 
7.	Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair (20% of DataCap allocation) self-dealing?

Moreover, I encourage you to take a look of my allocation [strategy ](https://github.com/filecoin-project/notary-governance/issues/11) and [flow ](https://ipfs.io/ipfs/QmdseAWQFVm8ntLZ5mkHyYRs6bB3g2LACT44wjB5zPv4rq)which shows how I utilize the assessment. Thanks.

**Comment by doowha** [comment]
Thank you for your answer.

I'm Sooyoung Choi, a member of the technology management team. Please refer to our company's website. (http://e-samjung.co.kr/gnuboard4/)

I'm not the CEO, we're Samjeong Trading Co., Ltd., and we're a cosmetics raw material company. We are located in Gyeonggi-do, South Korea, and was established in 2009, and was converted into a corporation in 2011 and has been growing steadily so far.

Likewise, we will use in South Korea.

We research and develop cosmetics raw materials and receive supplies from our partners and trade with manufacturers such as LG Household & Health Care. We will store all the data generated in this process in the Datacap. There are more than a thousand products that our company has researched and manufactured, and more products will continue to come out in the future. Inform our company and data (efficacy or research data) for each product will be publicly stored in the Datacap.

Advanced functions will not be specified yet. Next time, if necessary, I will designate it.

We are planning on 5 miners. There is no specific minor yet.

I agree.   

Thank you.

**Comment by Samjungee** [comment]
I'm sorry for the late response. 

However, since I am a technology management team, I have not received anything from the web form. 
Can we move on in a different way?
